* 2015 OAC Regionals – Round 8
** Round One
*** American Literature: Give the following related to 19th century poetry.
**** Team A:                                                          :drill:
What 19th century author wrote the poetry collection The Black Riders,
 which includes a poem that imagines a bestial creature who eats his
 own heart?
***** ANSWER:
Stephen Crane
**** Team B:                                                          :drill:
What other 19th century author wrote about a “true daughter of old
 time” in his poem “Sonnet -To Science”?  Other poems by this author
 include “Al Aaraaf” (al uh-rawf) and “Tamerlane”.
***** ANSWER:
Edgar Allan Poe
**** Tossup:                                                          :drill:
This poem describes a “last onset” that occurs “when the king be
 witnessed in the room.” Its speaker describes how “I willed my
 Keepsakes” and “signed away what portion of me be assignable” before
 noting how the title figure “was there interposed.” That figure is
 described as “blue” and “uncertain”, and it occupies a space “between
 the light and me” where the speaker realizes “and then I could not
 see to see.” This poem opens by describing a “stillness in the room”
 between “the heaves of storm.” Name this poem by Emily Dickinson
 titled for the noise a creature makes when the speaker perishes.
***** ANSWER:
“I heard a fly buzz - when I died” [accept Poem 465 or Poem 591]
*** Mathematics: Answer the following about conic sections.
**** Team B:                                                          :drill:
By definition, a conic section is formed by intersecting a cone with
what other geometric object?
***** ANSWER:
plane [do not accept a “square” or other answers]
**** Team A:                                                          :drill:
The conic section defined by x2
 + y2
 = 0 (“x squared plus y squared equals zero”) is described by what word that
 also describes a triangle whose points are collinear (KOH-lin-ee-ur)?
***** ANSWER:
degenerate [accept word forms; accept degenerate triangle]
**** Tossup:                                                          :drill:
This conic section gives its name to both quadrics that are
 doubly-ruled surfaces. This is the most eccentric conic section that
 was used by Apollonius [app-uh-LOH-nee-uss] of Perga to trisect an
 angle; Apollonius used one with an eccentricity of two. They are
 defined by a plane that cuts through both halves of a cone. The
 equation f(x) = 1/x (“f of x equals one over x”) is the simplest
 example of this conic section, which has an undefined value at some
 point. Two asymptotes (ASS-im-totes) characterize what conic section
 with an eccentricity greater than a parabola?
***** ANSWER:
hyperbolas or hyperbolae
*** World History: Name these medieval European leaders.
**** Team A:                                                          :drill:
This German King was victorious at the Battle of Lechfeld seven years
 before Pope John XII (the twelfth) crowned him as Holy Roman Emperor
 in 962.
***** ANSWER:
Otto I or Otto the Great or Otto der Grosse [prompt on “Otto”]
**** Team B:                                                          :drill:
In 1002, this Wessex King of England ordered what became known as the
 St. Brice’s Day Massacre, which prompted Danish King Sweyn Forkbeard
 to invade England and briefly exile this man.
***** ANSWER:
Ethelred the Unready or Ethelred II [prompt on “Ethelred”]
**** Tossup:                                                          :drill:
This ruler was the oldest son of a woman nicknamed “Bertha Broadfoot,”
 most likely because she was born with a clubfoot. This leader deposed
 Desiderius while successfully conquering the Kingdom of the
 Lombards. The Life of this man was the subject of a biography by
 Einhard, and his forces were defeated by Basques at the Battle of
 Roncevaux (rawn-suh-VOH) Pass, which was described in The Song of
 Roland. Twenty-nine years after his death, three of this ruler’s
 grandkids divided his kingdom in the 843 Treaty of Verdun. Pepin the
 Short was the father and predecessor of what Frankish King whom Pope
 Leo III (the third) crowned Holy Roman Emperor on Christmas Day of
 the year 800?
***** ANSWER:
Charlemagne (SHAHR-luh-“main”) [or Charles the Great or Charles I or Carolus ***Magnus or Karl der
 Grosse; prompt on “Charles”]
 Fine Arts: Name these musical instruments.
**** Team B:                                                          :drill:
This instrument plays at its highest register in the opening to The
 Rite of Spring and represents the grandfather in Peter and the Wolf.
***** ANSWER:
bassoon
**** Team A:                                                          :drill:
Georg Philipp Telemann wrote the first extant concerto for this
 instrument, which plays the solo part in Harold in Italy.
***** ANSWER:
viola
**** Tossup:                                                          :drill:
Along with the timpani, Francis Poulenc (POO-lonk) wrote a
 single-movement concerto for this instrument in G
 minor. Charles-Marie Widor’s (vee-DORZ) fifth symphony for this
 instrument ends with his famous “Toccata.” A performance of John
 Cage’s ASLSP (“A” “S” “L” “S” “P”) on this instrument will end in the
 year 2640. Because two sections of it use this instrument, Camille
 Saint-Saens’ third symphony is nicknamed after it. J.S. Bach
 supposedly traveled a few hundred miles to see Dieterich Buxtehude
 (BOOKS-tuh-HOO-duh) perform on this instrument and later wrote his
 Toccata and Fugue in D minor for it. Name this large instrument often
 found in churches.
***** ANSWER:
pipe organ
*** Life Science: Answer the following regarding lab techniques.
**** Team A:                                                          :drill:
In this technique, often done in mice, a gene is made unusable in an
 organism. This is done to study the function of the removed gene.
***** ANSWER:
gene knockout
**** Team B:                                                          :drill:
This technique allows one to separate molecules such as DNA by size by
 sending an electrical current through a medium made of agarose or
 poly·acryl·amide.
***** ANSWER:
gel electro·phoresis
**** Tossup:                                                          :drill:
Magnesium chloride is an important reagent in this technique since the
 magnesium cat·ion is a cofactor of the central enzyme. A variant of
 this technique is used to check for the presence of specific mRNA,
 and it can be used to detect and quantify certain viruses. This
 process was devised by Kary Mullis. An enzyme essential to this
 process is taken from the bacterium Thermus aquaticus. This technique
 takes place in a thermal cycler, which allows it to repeatedly cycle
 through denaturation, annealing, and elongation steps. Name this
 technique in which a piece of DNA is copied millions of times.
***** ANSWER:
polymerase chain reaction or PCR [accept real time PCR or RT-PCR]
** Round Two
*** English / World Literature: Give the following related to illustrators of English literature.
**** Team B:                                                          :drill:
Hablot Browne illustrated the novels of what author, whose works
include Martin Chuzzlewit and Bleak House?
***** ANSWER:
Charles John Huffam Dickens
**** Team A:                                                          :drill:
John Tenniel illustrated what Lewis Carroll novel, whose characters
included the Red Queen and Tweedledum?
***** ANSWER:
Through the Looking Glass, and What Alice Found There
**** Tossup:                                                          :drill:
At the end of this story, which was illustrated by Sidney Paget
 (PUH-jay), a sea-battered stern post with the letters “L.S.” painted
 on it is discovered. This story is told through the character of John
 Openshaw, who describes how his Uncle Elias is a former colonel that
 is given an envelope with the title objects; that envelope causes him
 to burn some secret papers and pace frantically before he is found
 dead in his own pool. Name this short story in which Sherlock Holmes
 deduces that a boat captain and his two mates are members of the
 K.K.K. and thus responsible for two murders.
***** ANSWER:
“The Five Orange Pips”
*** American Government / Economics: Name these current U.S. Senators.
**** Team A:                                                          :drill:
The most senior member of the Senate is this Democrat from Vermont who
 was replaced as president pro tempore in January 2015.
***** ANSWER:
Patrick Joseph Leahy (LAY-hee)
**** Team B:                                                          :drill:
This woman, who became Mayor of San Francisco following the 1978
 assassination of George Moscone and Harvey Milk, is currently the
 senior Senator from California.
***** ANSWER:
Dianne Goldman Berman Feinstein [or Dianne Emiel Goldman]
**** Tossup:                                                          :drill:
This politician first entered the Senate by winning an election
 against Richard Kimball. In September 2014, this Senator battled
 rumors that he met and took a photograph with ISIS leader Abu Bakr
 al-Baghdadi (AH-boo BAH-kur ahl- bahg-DAH-dee). Early in his career,
 this Senator was cleared of wrongdoing after becoming embroiled in a
 scandal involving Charles Keating. The memoir Faith of My Fathers
 recounted the military service of this man, who co-authored a 2002
 campaign finance reform law with Russ Feingold. More recently, this
 Senatorial successor to Barry Goldwater ran for president on a ticket
 with Sarah Palin. The loser to Barack Obama in the Election of 2008
 was what former Vietnam War POW and current Senator from Arizona?
***** ANSWER:
John Sidney McCain III
*** Physical Science: Answer the following about iron.
**** Team B:                                                          :drill:
Iron is the main component of steel, which is made through this
process that creates steel out of pig iron.
***** ANSWER:
Bessemer process
**** Team A:                                                          :drill:
To prevent iron from rusting, one can perform galvanization on it,
 which means plating the iron with this other element.
***** ANSWER:
zinc
**** Tossup:                                                          :drill:
An iron-containing chemical named after this color is used medically
 to remove cesium and thallium from the body. A compound named after
 this color is used to treat methemo·globinemia. In a Bradford assay,
 solutions that contain protein will turn into this color; the reagent
 used in Bradford assays is a dye called Coomassie brilliant. A
 solution of copper in water turns this color. An iron-containing
 pigment is called the Prussian type of this color. In gaseous and
 liquid phases, ozone has this color. An indicator named after this
 color is called bromo·thymol. Name this color that litmus paper turns
 into when dipped into a basic solution.
***** ANSWER:
blue
*** Geography: Name these U.S. states.
**** Team A:                                                          :drill:
Fort Pulaski National Monument is within this state, which has part of
 its western border former by the Chattahoochee River.
***** ANSWER:
Georgia
**** Team B:                                                          :drill:
Most of prehistoric Lake Bonneville was located within the existing
 boundaries of this state, which contains both Capital Reef and
 Canyonlands National Parks.
***** ANSWER:
Utah
**** Tossup:                                                          :drill:
The Chena Hot Springs are found within a resort in this state, in
 which much of the Kobuk River Valley is protected before emptying
 into the Kotzebue Sound. This state controls Little Diomede
 (DY-uh-meed) Island, and in 1964 the Good Friday Earthquake led to
 the relocation of its city of Valdez (val-DEEZ), which receives an
 oil pipeline that originates in Prudhoe Bay and crosses the Brooks
 Range. Prince William Sound and Kodiak Island are off the southern
 coast of this state, which is bisected by the Yukon River. Mount
 McKinley is the highest point in what northernmost U.S state whose
 capital is Juneau?
***** ANSWER:
Alaska
*** American History: Name these things related to the American West.
**** Team B:                                                          :drill:
San Antonio, Texas and Abilene, Kansas were at either end of this 19th
 century trail used primarily by cowboys for the transportation of
 cattle.
***** ANSWER:
Chisholm (CHIZ-um) Trail
**** Team A:                                                          :drill:
Much of the American West was settled due to the provisions of this
 1862 legislation which provided 160 acres for free to individuals
 willing to improve and live on the land for five years.
***** ANSWER:
Homestead Act of 1862
**** Tossup:                                                          :drill:
Jack Walton was impeached while serving as the governor of this
 state. Sarah Page and Dick Rowland were involved in an elevator
 incident that triggered a 1921 race riot in this state, part of which
 was the site for the proposed state of Sequoyah. Before achieving
 statehood, much of its Unassigned Lands were settled by the Land Rush
 of 1889. The Alfred P. Murrah Federal Building was located in this
 state until it was bombed by Terry Nichols and Timothy McVeigh.  The
 terminus of the Trail of Tears led to the settlement of the Indian
 Territory that went on to become this state. Name this plains state
 north of Texas which contains Tulsa and a namesake capital city.
***** ANSWER:
Oklahoma
** Alphabet Round – Letter L
*** Give                                                              :drill:
 (MULTI-WORD ANSWER) – This pirate and villain of Treasure Island owns
 a parrot named Captain Flint that repeats many things that are said
 to it. Jim Hawkins joins his crew in search of treasure.
**** ANSWER:
Long John Silver (MULTI-WORD ANSWER)
*** Give                                                              :drill:
 In mathematical proof theory, this term refers to some statement that
 must be proven so that it can be used as part of a proof. One named
 for Euclid is used in the proof of the fundamental theorem of
 arithmetic.
**** ANSWER:
lemmata
*** Give                                                              :drill:
 Trojan priest from Greek mythology who was killed by sea serpents
 after warning against acceptance of the Trojan horse.
**** ANSWER:
Laocoon
*** Give                                                              :drill:
 (HYPHENATED ANSWER) – 1941 act by which the U.S. provided supplies to
 the Allied nations during World War II.
**** ANSWER:
Lend-Lease Act (HYPHENATED ANSWER)
*** Give                                                              :drill:
 (MULTI-WORD ANSWER) – Joseph Kony is the current leader of this
 organization in Uganda which employs child soldiers and espouses a
 militaristic view of Christianity.
**** ANSWER:
Lord’s Resistance Army or Lord’s Resistance Movement (MULTI-WORD ANSWER)
*** Give                                                              :drill:
 (TWO WORD ANSWER) – Reactant that is completely consumed at the end
 of a chemical reaction.
**** ANSWER:
limiting reagent or limiting reactant (TWO WORD ANSWER)
*** Give                                                              :drill:
 (MULTI-WORD ANSWER) – The artist’s wife, Aline Charigot, plays with a
 dog in the foreground of this 1881 painting which depicts a meal
 taking place along the Seine River.
**** ANSWER:
Luncheon of the Boating Party [title must be exact] (MULTI-WORD ANSWER)
*** Give                                                              :drill:
 (TWO WORD ANSWER) – This Edward Bellamy novel follows Julian West,
 who puts himself asleep in 1887 and wakes up in the year 2000 to
 discover a utopia in the U.S.
**** ANSWER:
Looking Backward: 2000-1887 (TWO WORD ANSWER)
*** Give                                                              :drill:
 1925 treaties which sought to establish peace and settled
 international borders in Western Europe.
**** ANSWER:
Locarno Treaties or Locarno Pact
*** Give                                                              :drill:
 Method of viral replication in which the virus stays latent by
 incorporating itself into the host genome.
**** ANSWER:
lysogenic cycle or lysogeny
*** Give                                                              :drill:
 This psychosurgical technique, which was developed by Antonio Egas
 Moniz, was a way of treating psychological disorders. It often
 involves cutting away the prefrontal cortex of a brain.
**** ANSWER:
lobotomy [or leucotomy or leucotomy]
*** Give                                                              :drill:
 (MULTI-WORD ANSWER) – This film is the masterpiece of Alain Resnais
 and focuses on “the man” who mysteriously reunites with a woman he
 met at the title location.
**** ANSWER:
Last Year at Marienbad or Last Year in Marienbad [or L'Année dernière à Marienbad] (MULTI-WORD
*** Give                                                              :drill:
 This author’s experiences in concentration camps led him to write a
 short story collection structured around the Periodic Table. He also
 wrote the memoir If This is a Man, a book about his survival in
 Auschwitz.
**** ANSWER:
Primo Michele Levi
*** Give                                                              :drill:
 Abolitionist newspaper co-founded by William Lloyd Garrison in 1831.
**** ANSWER:
The Liberator
*** Give                                                              :drill:
 Nickname given to Shostakovich’s 7th symphony, which was written
 during the Second World War.
**** ANSWER:
Leningrad
*** Give                                                              :drill:
 Biblical character whose wife was turned into a pillar of salt during
 the destruction of Sodom and Gomorrah.
**** ANSWER:
Lot
*** Give                                                              :drill:
 (MULTI-WORD ANSWER) – This autobiographical play, which is set at the
 Monte Cristo Cottage, was written by Eugene O’Neill and follows a
 single day in the life of the Tyrone family.
**** ANSWER:
Long Day’s Journey into Night (MULTI-WORD ANSWER)
*** Give                                                              :drill:
 Mountain along the China-Nepal border which, at 27,940 feet above sea
 level, is the 4th highest mountain in the world.
**** ANSWER:
Lhotse
*** Give                                                              :drill:
 Primary military leader in the fight for Haitian independence; he
 died in a French prison in 1803.
**** ANSWER:
Francois Dominique Toussaint Louverture
*** Give                                                              :drill:
 (TWO WORD ANSWER) – This largest particle collider in the world was
 built by CERN and does actually produce micro-black holes.
**** ANSWER:
Large Hadron Collider (TWO WORD ANSWER)
** Lightning Round
*** Give                                                              :drill:
It’s not Brazil, but a composer from this country interspersed a
 melody repeated in every major key with Brazilian tunes. This home of
 the composer of The Ox on the Roof is also the birthplace of a man
 who used a “Passepied” (PAHSS- pee-ay) to conclude his Suite
 Bergamasque, which contains “Clair de Lune” (klair duh loon). Name
 this country that was home to the composers Darius Milhaud (mee-YOH)
 and Claude Debussy (deh-BYOO-see).
**** ANSWER:
France [or French Republic or Republique francaise]
*** Give                                                              :drill:
The opera based on this novella had its libretto written by
 E.M. Forster and was composed by Benjamin Britten. The last chapter
 of this book is a ballad describing the struggles of the title
 character, who makes an enemy after accidentally spilling over a
 shipmate’s soup. Its title character serves aboard the HMS
 Bellipotent and states “God Bless you, Captain Vere” as he is
 executed for striking Claggart. Name this Herman Melville novella
 about an alliteratively named sailor.
**** ANSWER:
Billy Budd, Foretopman [or Billy Budd, Sailor: An Inside Narrative]
*** Give                                                              :drill:
One assassination plot against this ruler resulted in the forced exile
 of his vice president Francisco Santander. While leading the
 Admirable Campaign, this leader consented to the killing of civilians
 in his “Decree of War to the Death.”  This ruler later fought
 alongside Antonio Jose de Sucre (SOO-kray), who won the Battle of
 Ayacucho (“eye”-uh-KOO- choh), while serving as the first president
 of Gran Colombia. Name this early 19th century leader who fought for
 South American independence from Spain, earning him the nickname “The
 Liberator”?
**** ANSWER:
Simon Bolivar (see-MOHN boh-LEE-var) [or Simon Jose Antonio de la
 Santisima Trinidad Bolivar y Palacios Ponte y Blanco]
*** Give                                                              :drill:
These data structures are necessary to implement the breadth-first
 search algorithm for a graph. Circular buffers are actually circular
 kinds of this data structure, which in some cases, may be
 “double-ended.” They have the last-in first-out property, unlike the
 similar stacks. Name these abstract containers used in computer
 science, which share their name with a line, usually of people
 waiting.
**** ANSWER:
queues
*** Give                                                              :drill:
This term originally referred to one of the two main methods of
 sacrificing an animal in Greek religion. As opposed to thyesthai
 (“THIGH”-es-“thigh”) sacrifices, this type of sacrifice completely
 burns an animal whole. For the Romani peoples, the modern usage of
 this term is equivalent to the Porajmos (por-AYE-muss). That modern
 day usage of this term is also equivalent to the Hebrew word Shoah,
 which means “the catastrophe.” Name this once religious term, which
 now is used to identify the genocide of the Jews by the Nazi.
**** ANSWER:
holocaust
*** Give                                                              :drill:
This author’s first novel follows the soldier Andreas, who journeys to
 Poland aboard the title conveyance. In addition to The Train was on
 Time, this writer of “rubble-literature” wrote a novel that features
 a family who has built St. Anthony’s Abbey. That book by this author
 follows the Faehmel (FAY-muhl) family, whose patriarch Robert plays
 the title game every morning. Name this German winner of the 1972
 Nobel Prize in Literature who authored Billiards at Half-Past Nine.
**** ANSWER:
Heinrich Theodore Boll
*** Give                                                              :drill:
This conflict ended shortly after one side rebuffed an offer of peace
 following the Battle of the Great Plains, which forced the retreat of
 Syphax (“SIGH”-fax). One side in this conflict developed the Fabian
 strategy after their defeat at the Battle of Lake Trasimene
 (TRAZ-ih-meen). Generals in this war included Hasdrubal and his more
 famous brother, who unsuccessfully deployed elephants against Scipio
 Africanus (SKIH-pee-oh aaf-rih-KAHN-uss) at the Battle of Zama.  Name
 this 3rd century BC conflict, during which Hannibal crossed the Alps
 to attack Rome.
**** ANSWER:
Second Punic War [prompt on “Punic War(s)”]
*** Give                                                              :drill:
This compound is combined with hydrogen gas to produce organic
 molecules in the Fischer-Tropsch process. It forms a coordination
 complex with nickel in the Mond process. Along with hydrogen, this
 compound makes up syngas (“sin”- “gas”). This gas forms during
 incomplete combustion, and it binds to hemoglobin more strongly than
 oxygen. Name this poisonous gas which consists of carbon triple
 bonded to oxygen.
**** ANSWER:
carbon monoxide [or CO]
*** Give                                                              :drill:
This city was where the musician King Buddy Bolden played a cornet for
 the entirety of his life. The bandleader King Oliver first came to
 prominence playing in the bordellos of this city’s red light
 district, Storyville. Another musician who was born in this American
 city was taught by King Oliver and first recorded a song that begins
 “I see trees of green, red roses too.” Name this southern city that
 was the birthplace of the artist who recorded “What a Wonderful
 World,” Louis “Satchmo” Armstrong.
**** ANSWER:
New Orleans, Louisiana
*** Give                                                              :drill:
This author’s nonfiction works include The Romantic Manifesto as well
 as a series of essays promoting egoism entitled The Virtue of
 Selfishness. One of this author’s characters completely dynamites the
 Cortland housing project after Peter Keating ruins it. Another of her
 books begins with the question “Who is John Galt?”. Howard Roark was
 created by this author in her book The Fountainhead. Name this
 Russian-American author who also wrote Atlas Shrugged.
**** ANSWER:
Ayn Rand [or Alisa Zinov’yevna Rosenbaum]
*** Give                                                              :drill:
This man obtains a horse named Grani from a disguised Odin. An enemy
 of this man tricks him into marrying Gudrun.  After slaying one foe,
 this man learns that his foster-father will betray him after he has a
 taste from that foe’s heart, allowing him to understand birds. Hagen
 kills this man, who is raised by Regin and wields the sword
 Gram. Name this hero of Norse mythology who slays the dragon Fafnir.
**** ANSWER:
Sigurd [or Siegfried]
*** Give                                                              :drill:
One archaeological site in this country, Maiden Castle, was formally
 inhabited by the Durotriges (dur-oh-TREE-gehs).  A ship burial
 featuring numerous embossed helmets in this country is suspected to
 be the tomb of King Raedwald (“RAID”-wald). This country, which is
 home to Sutton Hoo, is also home to a large prehistoric monument that
 consists of many standing stones quarried from Marlborough
 Downs. Name this country that is home to Stonehenge.
**** ANSWER:
England or United Kingdom of Great Britain and Northern Ireland or U.K. [accept any underlined portion]
*** Give                                                              :drill:
This group was originally to have been led by the 1st Marquis
 (marr-“KEY”) of Santa Cruz, who died three months before its
 formation. The appearance of this group prompted one leader to give
 the Tilbury Speech. After failing to rendezvous (RON-day-voo) with
 the Duke of Parma in Dunkirk, this group lost the Battle of
 Gravelines (GRAH-vuh- leen). The Duke of Medina-Sidonia led this
 force, which was repulsed with the help of Sir Francis Drake. King
 Philip II (the second) ordered the launch of what naval fleet that
 failed to invade England in 1588?
**** ANSWER:
Spanish Armada [or Grande y Felicisima Armada or Armada Invencible]
*** Give                                                              :drill:
This physicist proposed that it was possible to extract useful work
 from random collisions by imagining a device called a Brownian
 Ratchet. He immersed a seal in a glass of ice water to demonstrate a
 flaw in the so-called “O-Rings” while he was a part of the Rogers
 Commission, which investigated the Challenger accident. Name this
 scientist, who developed the path integral formulation of quantum
 mechanics, and whose namesake diagrams illustrate the behavior of
 subatomic particles.
**** ANSWER:
Richard Phillips Feynman (“FINE”-mun)
*** Give                                                              :drill:
The north part of this nation contains the Plateau of the Tamarugal
 (tuh-MAH-rue-gall). Alexander Selkirk was shipwrecked on an
 archipelago currently controlled by this nation: the Juan Fernandez
 Islands. It controls an island that is the site of sculptures known
 as moai (MOH-“eye”), which were created by the Rapa Nui people. This
 nation, which controls Easter Island, shares Tierra del Fuego with
 its eastern neighbor, Argentina. Name this South American nation that
 is over ten times longer than it is wide.
**** ANSWER:
Republic of Chile (CHEE-lay) [or Republica de Chile]
*** Give                                                              :drill:
This author fictionalized the trial of Count Guido Franceschini
 (gee-DO fran-chess-CHEE-nee), who apparently murdered his wife
 Pompilia Comparini (pom-pill-EE-uh com-puh-REE-nee), in The Ring and
 the Book. One of this author’s poems mentions the Claus of
 Innsbruck’s sculpture of Neptune and features a woman whose heart was
 “too soon made glad.” Name this author of dramatic monologues
 featuring tormented narrators, such as “My Last Duchess.”
**** ANSWER:
Robert Browning
*** Give                                                              :drill:
 One work by this author is a refutation of the virtues of monarchy
 that are presented in Sir Robert Filmer’s Patriarcha
 (PAY-tree-AR-kuh). Another of this philosopher’s works uses the
 example of an apple on a tree to argue that a man owns an apple after
 he has picked it, due to the labor that is needed to acquire it. That
 book argues that all humans have the right to life, liberty, and the
 right to own property. Name this English philosopher who authored Two
 Treatises on Government.
**** ANSWER:
John Locke
*** Give                                                              :drill:
 Sitting Secretary of the Navy Smith Thompson aspired to run in this
 election before his appointment to the Supreme Court. Prior to this
 election, Nathaniel Macon replaced Albert Gallatin as the vice
 presidential candidate on a ticket with William Crawford. Henry Clay
 finished fourth in this election, which was decided by the House of
 Representatives in what detractors dubbed the “corrupt bargain.”
 Despite receiving the most popular and electoral votes, Andrew
 Jackson lost what election which conferred the presidency to John
 Quincy Adams?
**** ANSWER:
Presidential Election of 1824
*** Give                                                              :drill:
One figure in this painting was the subject of another work by its
 artist entitled Head of a Negro. In the top right of this painting,
 Morro Castle appears in the background. The primary figure in this
 work grasps for a rope held by a black man, who stands next to a man
 about to plunge a spear into the creature below him. The event in
 this painting took place in Havana Harbor in 1749 and resulted in the
 title figure losing his right foot. Name this John Singleton Copley
 painting that depicts an attack by a carnivorous fish.
**** ANSWER:
Watson and the Shark
*** Give                                                              :drill:
One method of doing this task sees the release of pyro·phosphate,
 which is converted to ATP that causes the emission of light. Another
 method for performing this technique is to use radio·labeled or
 fluorescently-labeled ddNTP’s (“d”-“d”- “N”-“T”-“P’s”), which will
 cause chain termination and allow one to see what the last
 nucleo·tide added is; that is the Sanger method of doing this. Name
 this technique of determining the order in which base pairs are
 arranged.
**** ANSWER:
DNA sequencing or gene sequencing or genome sequencing [prompt on “sequencing”]
 
