* 2015 OAC Regionals – Round 7
** Round One
*** American Literature: Name these authors who wrote works of nonfiction.
**** Team A:                                                          :drill:
What author of the novel A Bell for Adano wrote about six atomic bomb
 survivors in his book-length work Hiroshima?
***** ANSWER:
John Richard Hersey
**** Team B:                                                          :drill:
What author of the novel Rabbit, Run chronicled Ted Williams’ final
 home run in his essay “Hub Fans Bid Kid Adieu”?
***** ANSWER:
John Hoyer Updike
**** Tossup:                                                          :drill:
This author wrote the statement “Nobody can add to the absurdity of
 this book” in regards to the hilariously- translated phrase book
 English As She is Spoke. Another of his nonfiction works is an essay
 attacking the rules of literary art that The Deerslayer
 violated. This author of “Fenimore Cooper’s Literary Offenses” wrote
 about a town that tries to resist temptation in “The Man that
 Corrupted Hadleyburg.” In another of his stories, Jim Smiley captures
 the title animal, names it Dan’l (“daniel”) Webster, and teaches it
 to jump. Name this humorist who wrote “The Celebrated Jumping Frog of
 Calaveras County.”
***** ANSWER:
Mark Twain [or Samuel Langhorne Clemens]
*** Mathematics: Pencil and paper ready. Give the following related to permutations. You will have 30 seconds for
 each team question.
**** Team B:                                                          :drill:
Six friends compete in an apple-picking competition at the local
 hootenanny and a gold, silver, and bronze medal are awarded to first,
 second, and third places, respectively. How many possible ways can
 the three medals be distributed?
***** ANSWER:
120
**** Team A:                                                          :drill:
A panda bear has five different foraging spots. If he goes to a
 different one for morning, noon, twilight, and dusk, how many daily
 unique permutations does he have?
***** ANSWER:
120
**** Tossup:                                                          :drill:
Pencil and paper will not be necessary. A permutation is made from the
 Fischer-Yates algorithm, which requires numbers with this property as
 an input. Variables with this property are functions that map from
 the set of all outcomes to the real numbers. Markov and Weiner
 processes possess this property. Generating numbers with this
 property is actually impossible; thus the “pseudo-” version of this
 property is desired instead. This property is synonymous with
 stochastic. Name this property of certain sequences of numbers which
 makes them unpredictable.
***** ANSWER:
random [accept pseudo-random numbers or random variables]
*** World History: Name these leaders of the ancient world.
**** Team A:                                                          :drill:
The 587 BC destruction of Jerusalem was overseen by this Babylonian
 king perhaps best known for constructing the Hanging Gardens of
 Babylon.
***** ANSWER:
Nebuchadnezzar II (NEH-buh-kud-NEZ-zur “the second”) [accept Nebuchadrezzar II or Nabu-kudurri-
 usur; prompt on “Nebuchadnezzar” or “Nebuchadrezzar”]
**** Team B:                                                          :drill:
This 19th Dynasty Egyptian pharaoh, who ruled in the 13th century BC,
 allegedly fathered over 100 children, including several with
 Nefertiti, during his sixty-six year reign.
***** ANSWER:
Ramses II [RAM-zeez “the second”] [or Ramesses II or Ramses the Great or Ramesses the Great or
 Ozymandias; prompt on "Ramses" or "Ramesses"]
**** Tossup:                                                          :drill:
This leader melted down a large gold statue of Marduk after his
 son-in-law, Megabyzus, successfully sacked Babylon. This son of
 Atossa finished construction of a building known as the Gate of All
 Nations and was murdered by Artabanus (ar-tuh-BAY-nus). This leader
 cut one of his military campaigns short and left control with his
 general, Mardonius, who was shortly thereafter defeated and killed at
 the Battle of Plataea (pluh-TEE-uh). That campaign began with this
 ruler building two pontoon bridges across the Hellespont, and it also
 saw his forces lose at the naval Battle of Salamis. Name this Persian
 ruler who succeeded his father, Darius I (the first), and failed in
 his 5th century BC invasion of Greece.
***** ANSWER:
Xerxes I (ZURK-seez “the first”) of Persia [or Xerxes the Great; prompt on ***“Xerxes”]
 Fine Arts: Name these European artists.
**** Team B:                                                          :drill:
Several nude women gather around a body of water in The Bathers, a
 work by this French artist known for his several paintings of Mont
 Sainte-Victoire (mawn sant-veek-TWAR).
***** ANSWER:
Paul Cezanne (say-zahn)
**** Team A:                                                          :drill:
Adele Bloch-Bauer was the subject of two portraits by this Austrian
 painter best known for depicting two figures clad in gold while
 performing the title activity in The Kiss.
***** ANSWER:
Gustav Klimt
**** Tossup:                                                          :drill:
This artist depicted a levitating man who contorts his body to kiss a
 woman holding a bouquet in a painting entitled Birthday. In another
 work by this artist, a purple-dressed man carrying scrolls, a group
 of soldiers waving red flags, and a burning synagogue topped by a
 Lithuanian flag are among various scenes that surround the colorful
 title event. A man carrying a scythe and an upside down woman playing
 the violin both appear in his best known painting, which shows a
 green-faced man staring into the eyes of a goat. Name this
 Russian-born Jewish painter of White Crucifixion and I and the
 Village.
***** ANSWER:
Marc (Zaharovich) Chagall (shuh-GAHL)
*** Life Science: Answer the following about the eye.
**** Team A:                                                          :drill:
This liquid, found between the cornea and iris, is constantly
 produced. Irregular levels of its production or drainage can lead to
 glaucoma.
***** ANSWER:
vitreous (VIT-ree-uss) humor
**** Team B:                                                          :drill:
This portion of the retina contains the fovea and is its most
 sensitive portion. Vision impairment in older individuals can be
 caused by its degeneration.
***** ANSWER:
macula
**** Tossup:                                                          :drill:
These animals have eyes with light sensors that directly receive
 incoming light instead of reflecting it off the back first, and they
 move their lens instead of changing its shape. It’s not fish, but
 Vibrio fischeri is found within one member of this class. Some
 members of this animal class have a tube running from the center of
 their body to the outside of their shell called a siphuncle. A
 still-living early example of this class of invertebrates is the
 nautilus. They have the most advanced eye out of all
 invertebrates. When escaping, these animals can release a cloud of
 ink. Name this class of mollusks which includes cuttlefish and squid.
***** ANSWER:
cephalopods or cephalopoda
** Round Two
*** English / World Literature: Name these European authors.
**** Team B:                                                          :drill:
What Czech author never finished his novel about K., who tries to
enter the title structure, titled The Castle?
***** ANSWER:
Franz Kafka [or Franz Anschel]
**** Team A:                                                          :drill:
What Czech author wrote about Tomas and Teresa, who live during the
 Prague Spring, in The Unbearable Lightness of Being?
***** ANSWER:
Milan Kundera
**** Tossup:                                                          :drill:
This author adapted Arthur Schnitzler’s (SHNITZ-lurz) play The Distant
 Land into his own play The Undiscovered Country. The events that lead
 to the Russian Revolution are the subject of his three plays Voyage,
 Shipwreck, and Salvage. In another play by this author, the title
 characters and the Tragedians (tra-juh-DEE-unz) hide in barrels while
 pirates attack their boat. In that play by this author, the two title
 characters perform The Murder of Gonzago after flipping a coin 92
 times and seeing it land on heads every time. Name this author of
 Rosencrantz and Guildenstern are Dead.
***** ANSWER:
Tom Stoppard [or Tomáš Straussler]
*** American Government / Economics: Name these Cabinet-level positions
**** Team A:                                                          :drill:
In 2014, former Kansas Governor Kathleen Sibelius resigned from this
 position, which led to the appointment of its current holder, Sylvia
 Burwell.
***** ANSWER:
Secretary of Health and Human Services or Health and Human Services Secretary [prompt on “HHS”]
**** Team B:                                                          :drill:
A 2014 scandal led to Eric Shinseki’s resignation of this office,
 which was the most recent to be added as a Cabinet level position
 until the 2001 creation of the Department of Homeland Security.
***** ANSWER:
Secretary of Veterans Affairs or Veterans Affairs Secretary [prompt on “VA”]
**** Tossup:                                                          :drill:
In 1989 the U.S. Senate denied the appointment of John Tower to this
 position. Charles Wilson was pressured to resign as CEO of General
 Motors after being nominated for this position, which was first held
 by a man who is presumed to have committed suicide by jumping out of
 a hospital window. Caspar Weinberger held this office under Ronald
 Reagan until his resignation amid the Iran-Contra Affair. This
 position was held two separate times, twenty-four years apart, by
 Donald Rumsfeld, and its longest holder was Robert McNamara. In 2015,
 Chuck Hagel was replaced by Ashton Carter in what Cabinet-level
 office that was created in 1947 to replace the position of Secretary
 of War?
***** ANSWER:
Secretary of Defense [accept Defense Secretary; prompt on “SecDef”; do not ***accept or prompt on “Secretary
 of War”]
 Physics: Questions in this category will deal with the physics of momentum transfer.
**** Team B:                                                          :drill:
What quantity, which is given as the time integral of force, is
 defined as the vector change in an object’s linear momentum?
***** ANSWER:
impulse
**** Team A:                                                          :drill:
For a two object system, this property of a system does not change in
 a collision since momentum is always conserved. For a rigid body,
 this property is the centroid.
***** ANSWER:
center of mass [do not accept “center of gravity”]
**** Tossup:                                                          :drill:
The maneuvers of these objects can be mathematically expressed by the
 Tsiolkovsky (SEAL-koff-skee) equation, which is derived by the
 conservation of momentum. Robert Forward proposed a specific type of
 this object known as a fission sail. These objects can have their
 momentum altered via staging, in which their excess weight is shed.
 A theory relating to these objects was outlined in A Method of
 Reaching Extreme Altitudes by Robert Goddard. Typically, they use
 liquid or solid fuel to provide thrust. Name these spacecraft which
 have engines that eject propellant and were studied by Wernher von
 Braun (VAIR-err vahn brahn).
***** ANSWER:
rockets
*** Geography: Name these Asian nations.
**** Team A:                                                          :drill:
This country’s exclave of Musandam borders the south side of the
 Strait of Hormuz, which is at the west end of a gulf named after this
 nation.
***** ANSWER:
Sultanate of Oman [or Saltanat Uman]
**** Team B:                                                          :drill:
This nation, which contains Lake Balkhash, is the world’s largest
landlocked nation.
***** ANSWER:
Republic of Kazakhstan (KAH-zak-STAN) [or Qazaqstan Respublikasy]
**** Tossup:                                                          :drill:
The eastern part of this nation is dominated by the Khorat
 Plateau. Many tourists to this nation flock to the island of Phuket,
 and its capital, which houses royalty in the Grand Palace, is located
 on the Chao Phraya (“chow” PRY-uh) River. With its western neighbor,
 this nation shares the Isthmus of Kra, which borders the Andaman Sea
 and a gulf sharing its name with this country. This nation is at the
 south end of the opium-production area known as the Golden Triangle,
 which also includes the nations of Laos (“louse”) and Burma. Siam was
 the former name of what Southeast Asian nation whose capital is
 Bangkok?
***** ANSWER:
Kingdom of Thailand [or Prathet Thai or Ratcha Anachak Thai]
*** American History: Name these events that took place during the colonial era.
**** Team B:                                                          :drill:
Accusations by Abigail Williams and Betty Parris helped lead to this
 1692 event which resulted in the execution of Giles Corey, who
 continuously asked for “more weight” during the process of being
 pressed to death.
***** ANSWER:
Salem witch trials (prompt on partial answer)
**** Team A:                                                          :drill:
Colonial Governor William Berkeley’s failure to protect against Native
 American attacks played a part in the start of this 1676 rebellion
 which resulted in Jamestown, Virginia being burned to the ground.
***** ANSWER:
Bacon's Rebellion
**** Tossup:                                                          :drill:
One trial in the aftermath of this event was impacted by the testimony
 of Dr. John Jeffries, who relayed the deathbed testimony of Patrick
 Carr. An investigatory committee headed by James Bowdoin (BOH-din)
 was established after this event, which stemmed from a disagreement
 over a wigmaker’s bill. Hugh Montgomery and Matthew Kilroy were
 convicted of manslaughter and branded following this event. Eight
 soldiers are shrouded in smoke on the right side of a notable
 engraving of this event created by Paul Revere. John Adams defended
 the British soldiers accused of murdering Crispus Attucks and four
 others in what 1770 event that occurred in the capital of
 Massachusetts?
***** ANSWER:
Boston Massacre [accept Incident on King Street]
** Alphabet Round – Letter S
*** Give                                                              :drill:
 Civil War colonel who commanded the 54th Massachusetts Infantry, an
 all African-American military unit, until his death at the Second
 Battle of Fort Wagner.
**** ANSWER:
Robert Gould Shaw
*** Give                                                              :drill:
 This term refers to philosophical activities, such as Zeno’s tortoise
 and hair race, which consist of an infinite number of little
 sub-actions. Their solubility is up for philosophical debate.
**** ANSWER:
supertasks
*** Give                                                              :drill:
 In William Blake’s “The Tyger”, the author asks “What immortal hand
 or eye could frame thy fearful [this]?”
**** ANSWER:
symmetry
*** Give                                                              :drill:
 Desert in northern Africa that is the world’s largest hot desert.
**** ANSWER:
Sahara Desert
*** Give                                                              :drill:
 Group of bacteria that have long, coiled cell shapes and include the
 causative agents of syphilis and Lyme disease.
**** ANSWER:
spirochetes
*** Give                                                              :drill:
 (TWO WORD ANSWER) – Nation whose 26-year civil war was ended in 2009
 with the defeat of the rebel group known as the Tamil Tigers.
**** ANSWER:
Democratic Socialist Republic of Sri Lanka (shree LAHN-kuh) [or Shri
Lamka Prajatantrika Samajaya di Janarajaya]
*** Give                                                              :drill:
 This photographer and museum curator took the photograph The
 Pond-Moonlight and organized The Family of Man exhibit at the Museum
 of Modern Art.
**** ANSWER:
Edward Jean Steichen
*** Give                                                              :drill:
 This poet wrote the influential collection Harmonium, which contains
 his poem “Thirteen Ways of Looking at a Black Bird.”
**** ANSWER:
Wallace Stevens
*** Give                                                              :drill:
 (TWO WORD ANSWER) – In probability, this is the set of all possible
 outcomes of a random variable. For a die, this set consists of the
 numbers {1,2,3,4,5,6}.
**** ANSWER:
sample space [do not accept “sample set”] (TWO WORD ANSWER)
*** Give                                                              :drill:
 Egyptian God of the Nile who has the head of a crocodile.
**** ANSWER:
Sobek [or Sebek or Sochet or Sobk or Sobki or Suchos]
*** Give                                                              :drill:
Artistic technique, the name of which comes from the Italian word for
“to fade out,” in which colors are blended so as to prevent sharp
outlines, thereby resulting in a painting that looks hazy.
**** ANSWER:
sfumato
*** Give                                                              :drill:
 American woman whose engagement to British king Edward VIII resulted
 in the latter’s abdication of the throne in
 1936.
**** ANSWER:
Bessie Wallis Warfield Simpson or Bessie Wallis Warfield Spencer
*** Give                                                              :drill:
 The final words of T.S. Eliot’s “The Wasteland” are in what language,
 which was also used to write The Recognition of Sakuntala?
**** ANSWER:
Sanskrit
*** Give                                                              :drill:
 Discoverer of many actinide elements while at the University of
 California at Berkeley.
**** ANSWER:
Glenn Theodore Seaborg
*** Give                                                              :drill:
 Place that inspired Felix Mendelssohn’s 3rd symphony and a fantasy by
 Max Bruch.
**** ANSWER:
Scotland
*** Give                                                              :drill:
 Surname of the family that succeeded the Visconti family as rulers of
 Milan during the 15th and 16th century.
**** ANSWER:
Sforza family [accept Sforzas]
*** Give                                                              :drill:
 This quantum number, the fourth one, can take on values of 1/2 or
 -1/2 for fermions. It is sometimes called “intrinsic angular
 momentum.”
**** ANSWER:
spin quantum number
*** Give                                                              :drill:
 This author of Lie Down in Darkness and Darkness Visible wrote a book
 narrated by Thomas Gray that was the Pulitzer-Prize winning The
 Confessions of Nat Turner.
**** ANSWER:
William Clark Styron Jr.
*** Give                                                              :drill:
 Term used to describe the Biblical Gospels of Matthew, Mark and Luke
 due to their similarity to one another.
**** ANSWER:
Synoptic Gospels
*** Give                                                              :drill:
 Beyond Freedom and Dignity is a book by this behaviorist
 psychologist, who created a namesake box for conditioning test
 subjects.
**** ANSWER:
Burrhus Frederic Skinner
** Lightning Round
*** Give                                                              :drill:
Early in his reign, one king with this name and number quashed a
 rebellion known as the Epiphany Rising. A Holy Roman Emperor with
 this name and number travelled to Canossa to put an end to the
 Investiture Controversy with Pope Gregory VII (the seventh). The
 English king with this name and number became the first ruler of the
 House of Lancaster after deposing Richard II (the second). Give this
 name and number of France’s first Bourbon king, who issued the Edict
 of Nantes and noted that “Paris is well worth a mass.”
**** ANSWER:
Henry IV (the fourth) [prompt on “Henry”]
*** Give                                                              :drill:
According to one legend, this figure possessed the Ring of Aandaleeb
 (AND-uh-lib), which was used to control genies.  While coming into
 power he was opposed by his half-brother Adonijah (ad-oh-NY-juh), and
 shortly after dying, his kingdom was split during the rule of his
 son, Rehoboam. This ruler once proposed cutting a baby in half in
 order to determine its real mother. The Biblical books Song of Songs
 and Proverbs were supposedly authored by what wise king of Israel who
 succeeded his father, David?
**** ANSWER:
Solomon [or Shlomo or Sulayman]
*** Give                                                              :drill:
One type of this reaction is the hydrogenation of unsaturated
 compounds. Molecules that can readily react in this manner include
 hydrides. In electrochemistry, the potentials of half reactions are
 always written out for this type of reaction. An example of this type
 of reaction is when iron III (three) is converted to iron II
 (two). Name this type of reaction in which a species gains electrons,
 as opposed to oxidation.
**** ANSWER:
reduction reaction [accept word forms; prompt on “redox reaction”]
*** Give                                                              :drill:
This peninsula was once named after explorer Nathaniel Palmer. One
 portion of this peninsula is known as Graham Land, and it is located
 just south of the South Shetland Islands. It borders the Erebus and
 Terror Gulf, which is named after two ships commanded by James Ross
 during an exploration of this peninsula. It is situated between the
 Bellingshausen (BEH-lings-how-sehn) and Weddell Seas, and the Drake
 Passage separates it from South America. Name this most prominent
 peninsula on the landmass that contains the South Pole.
**** ANSWER:
Antarctic Peninsula
*** Give                                                              :drill:
This author wrote “Thou two-faced year, Mother of Change and Fate” in
 the poem “1492.” Another sonnet by this author of the collection
 Songs of a Semite features a woman who states “Keep ancient lands,
 your storied pomp” as well as “Give me your tired, your poor, your
 huddled masses, yearning to breathe free.” Name this female author
 who wrote the poem found on the Statue of Liberty, “The New
 Colossus.”
**** ANSWER:
Emma Lazarus
*** Give                                                              :drill:
One action taken by this group led to the Supreme Court case
 U.S. v. Cecil Price et. al. Indiana schoolteacher Madge Oberholtzer
 was raped and murdered by one of its leaders, D.C. Stephenson. The
 Force Act of 1871 attempted to curb the power of this group, members
 of which carried out a 1963 bombing of the 16th Street Baptist Church
 in Birmingham. The Birth of a Nation glorified what racist
 organization first led by Nathan Bedford Forrest and known for
 donning white robes and masks?
**** ANSWER:
KKK or Ku Klux Klan
*** Give                                                              :drill:
Guillame (GEE-yahm) Dufay’s motet Nuper Rosarum Flores (NEW-purr
 ROH-sar-um “FLOOR”-ays) was composed for the completion of this
 building, whose original design was made by Arnolfo di Cambio. This
 building is part of a complex that also includes Andrea Pisano’s
 campanile. Located in the Piazza del Duomo, it is sometimes named for
 St.  Mary of the Flower. Across from this building is a baptistery
 whose doors were designed by Lorenzo Ghiberti (gih-
 “BEAR”-tee). Filippo Brunelleschi (FILL-ipp-oh BREW-nuh-less-key)
 designed the dome of what religious building in a north Italian city?
**** ANSWER:
Florence Cathedral [or Cattedrale di Santa Maria del Fiore; prompt on “cathedral”]
*** Give                                                              :drill:
This figure was conceived after his father was tricked into becoming
 drunk by the Troezen (TRAY-zen) King Pittheus.  He killed the
 Cromyonian Sow and the tree-bending bandit Sinis after recovering a
 sword and sandals that had been buried under a rock. This figure was
 tricked by his wife, Phaedra (FAY-druh), into fatally cursing his
 son, Hippolytus (hih-PAH-lih-tuss). This son of Aegeus (uh-JEE-us)
 used a ball of string to help him kill the inhabitant of the
 Labyrinth.  Name this mythical Greek hero who slayed the Minotaur.
**** ANSWER:
Theseus (THEE-see-us)
*** Give                                                              :drill:
In the early 20th century, bismuth was removed from this element
 through the use of the Betterton process. Historically, the alloy
 solder (SAH-dur) was made from tin and this other metal. With sulfur,
 this metal can be found in the ore galena, and it is often made in
 bricks for use in radiation shielding. This element was called
 plumbum by the Romans, since it was used in pipes. Name this heavy
 metallic element whose symbol is Pb (“P” “B”).
**** ANSWER:
lead (led)
*** Give                                                              :drill:
 This philosopher considered whether the Fregean (FRAY-gee-an) theory
 of names is correct by considering the sentence “The King of France
 is bald” in his essay “On Denoting.” His namesake paradox asks if the
 set of all sets which does not contain itself can contain itself;
 that work on set theory led to a collaboration with Alfred North
 Whitehead.  Name this philosopher who wrote “Why I am not a
 Christian” and who was one of the co-authors of the Principia
 Mathematica (PREEN-kipp-ee-uh MATH-uh-matt-ick-uh).
**** ANSWER:
Bertrand Arthur William Russell, 3rd Earl Russell
*** Give                                                              :drill:
This poem’s narrator “met a lady in the meads” whose “hair was
 long…foot was light, and...eyes were wild.” Later, “pale kings and
 princes” note that the title figure “hath thee in thrall!” Its second
 stanza asks “O what can ail thee, knight- at-arms, so haggard and so
 woe-begone?” This poem is set where the “sedge is wither’d from the
 lake, and no birds sing.”  Name this poem by John Keats about a
 beautiful lady without mercy.
**** ANSWER:
“La Belle Dame Sans Merci”
*** Give                                                              :drill:
This ruler expanded the Marmaris Castle to utilize it as a military
 base, and he led several campaigns against Tahmasp I (TAH-mosp “the
 first”), a shah of the Safavid Dynasty. This ruler expelled the
 Knights Hospitaller (hoss-PIT-tuh-lur) from the island of Rhodes, and
 troops under his leadership killed Louis II (the second) of Hungary
 during the Battle of Mohacs (moh-HAHCH). This successor of Selim I
 (suh-LEEM “the first”) unsuccessfully besieged Vienna in 1529.  Name
 this longest-reigning Ottoman sultan known by the epithet
 “magnificent.”
**** ANSWER:
Suleiman (SOO-luh-mahn) the Magnificent [or Suleiman I or Suleiman the
 Lawgiver or Suleiman Kanuni; accept Suleiman by end of question;
 prompt on “Suleiman” before end of question]
*** Give                                                              :drill:
This man’s namesake equation states that an object’s final velocity
 squared equals the initial velocity squared plus two times
 acceleration times the change in position. The speed of a fluid
 leaving an opening is given by this scientist’s namesake law. One of
 his inventions makes use of an inverted column of air in a pool of
 liquid mercury. Name this Italian physicist who invented the
 barometer and who gives his name to the unit of pressure called the
 torr.
**** ANSWER:
Evangelista Torricelli (taw-rih-CHEL-ee)
*** Give                                                              :drill:
This composer wrote the first symphony to begin in a major key and end
 in a minor key; that symphony ends with a “Saltarello” movement. The
 first two books of six songs by this composer each end with a
 “Venetian Boat Song.” His incidental music to a William Shakespeare
 play contains a famous “Wedding March” in C major. Name this German
 composer of the Italian Symphony, Songs without Words, and A
 Midsummer Night’s Dream.
**** ANSWER:
Jakob Ludwig Felix Mendelssohn-Bartholdy (MEN-dul-sun)
*** Give                                                              :drill:
A mischievous man tours this country while flying wild geese in the
 novel The Wonderful Adventures of Nils. An author from this country
 wrote a play named for a woman who insists that her dog Diana was
 unfaithful. That play from this country, whose characters include the
 valet Jean, ends with its title character being given a razor to
 commit suicide.  Name this country of origin of the author of Miss
 Julie, August Strindberg.
**** ANSWER:
Kingdom of Sweden [or Konungariket Sverige]
*** Give                                                              :drill:
Movement of these objects is divided into types called autochory and
 allochory. One part of their structure is covered by a coleoptile
 (koh-lee-OP-“tile”). These objects contain a micropyle, which allows
 water to enter them. These objects are mostly comprised of endosperm,
 and the first portion to emerge out of it is the radicle, which will
 grow into a root.  Name this result of plant fertilization, which can
 grow into a new plant upon germination.
**** ANSWER:
seeds
*** Give                                                              :drill:
One of these events interrupted a 1903 showing of the play
 Mr. Bluebeard at Chicago’s Iroquois Theater; another one occurred at
 Stone Bridge following the Johnstown Flood. Max Blanck and Isaac
 Harris faced criminal charges after one that occurred at the Asch
 Building. Another of these events began at Thomas Farriner’s bakery
 on Pudding Lane and destroyed St. Paul’s Cathedral in 1666
 London. Name this type of disaster that destroyed much of Chicago in
 1871 and was supposedly started by Mrs. O’Leary’s cow.
**** ANSWER:
fire [or conflagration; accept Iroquois Theater fire or Triangle
 Shirtwaist Factory fire or Great Fire of London or Great Chicago
 Fire]
*** Give                                                              :drill:
 One work by this thinker makes the claim that social facts are
 inherently constraining. In another of his works, he distinguished
 between organic and mechanical solidarity. This sociologist wrote an
 essay that seeks to examine why Catholics have higher social cohesion
 than Protestants. In that book, he listed altruistic, anomic,
 fatalistic, and egoistic as the four types of the title action. Name
 this French thinker, sometimes called the “father of sociology”, who
 authored The Division of Labor in Society and Suicide.
**** ANSWER:
David Emile Durkheim (DUR-kem)
*** Give                                                              :drill:
This work’s protagonist is given some armor after leaving the House of
 the Palace Beautiful, which he uses against the monster
 Apollyon. Nathaniel Hawthorne updated this work in his short story
 “The Celestial Railroad.” Its protagonist meets Hopeful, who came
 from the City of Destruction, but that character is burned at the
 stake when they come to Vanity Fair. Name this allegory about the
 everyman Christian, a work of John Bunyan.
**** ANSWER:
The Pilgrim’s Progress from This World to That Which Is to Come;
 Delivered under the Similitude of a Dream
*** Give                                                              :drill:
One work by this artist of View of Fort Samson depicts three nude
 women, one of whom is seated while taking off green stockings. That
 work, The Models, depicts a part of his best known painting, in which
 a black dog sniffs the grass directly behind a lounging man who
 smokes a pipe. Several people relax in or near the Seine (sen) River
 in his Bathers at Asnieres (ahn-YAIR), and his best known work
 features a woman holding the leash of a monkey. Name this French,
 pointillist painter of A Sunday Afternoon on the Island of La Grande
 Jatte (lah grahnd zhaht).
**** ANSWER:
Georges-Pierre Seurat (zhorzh-pee-AIR suh-RAH)
 
