* 2015 OAC Regionals – Round 6
** Round One
*** American Literature: Name these Pulitzer Prize-winning authors.
**** Team A:                                                          :drill:
What author won the 1976 Pulitzer Prize for his novel about a
 fictional version of Delmore Schwartz entitled Humboldt’s Gift?
***** ANSWER:
Saul Bellow [or Solomon Bellows]
**** Team B:                                                          :drill:
The novella Pale Horse, Pale Rider and the novel Ship of Fools were
 written by what author who won the 1965 Pulitzer Prize for her
 collected short stories?
***** ANSWER:
Katherine Anne Porter [or Callie Russell Porter]
**** Tossup:                                                          :drill:
 This author won the Pulitzer Prize for writing a work that examines
 “corporation land” and “technology land”; that work examines the
 March on the Pentagon. Ramses IX (the ninth) tells tales of time past
 in this author’s novel set in ancient Egypt; that work is Ancient
 Evenings. One of his last novels, which focuses on Dieter (DEE-tur),
 who notes that a demon possessed Adolf Hitler in his youth, is titled
 The Castle in the Forest. This author of Armies of the Night won
 another Pulitzer Prize for his nonfiction novel about Gary
 Gilmore. Name this author who wrote The Executioner’s Song.
***** ANSWER:
Norman Kingsley Mailer
*** Mathematics: Answer some questions about mathematical proofs.
**** Team B:                                                          :drill:
At the end of some mathematical proofs, you may find these three
 letters, representing a Latin abbreviation, which indicates that the
 proof is over.
***** ANSWER:
Q.E.D. [accept quod erat demonstrandum]
**** Team A:                                                          :drill:
In this proof technique, you assume that the opposite of what you are
 trying to prove is true, then show that an absurd result occurs; thus
 your original statement must be true.
***** ANSWER:
proof by contradiction [accept indirect proof or apagogical argument or reductio ad impossibilem]
**** Tossup:                                                          :drill:
 This technique is demonstrably valid via the well-ordering
 principle. Often used to verify a summation formula, many
 mathematicians make use of this technique’s strong form, so that all
 statements from “1 to n” are true. This technique starts with proving
 a base case and then assuming that a statement at n is true; all that
 is needed to be done is to show that the correctness of n implies the
 correctness of “n + 1” (“n plus one”). Name this mathematical proof
 technique which shares its name with a type of reasoning that makes
 generalizations from the specific.
***** ANSWER:
proof by induction [accept word forms]
*** World History: Name the following related to events that occurred during the 17th century.
**** Team A:                                                          :drill:
Ieyasu’s (ee-ay-AH-sooz) victory at the Battle of Sekigahara paved the
 way for the 1603 establishment of this Japanese shogunate which ruled
 during the Edo period for over two and a half centuries.
***** ANSWER:
Tokugawa Shogunate [or Tokugawa Bakufu]
**** Team B:                                                          :drill:
The first Europeans to sight New Zealand did so in 1642 under the
 command of this Dutch explorer who also discovered and named Van
 Diemen’s Land, which was later renamed after him.
***** ANSWER:
Abel Janszoon Tasman [do not accept or prompt on “Tasmania”]
**** Tossup:                                                          :drill:
 Anne Vaux (VOO) was arrested following this event, which resulted in
 the execution of Edward Oldcorne after he was discovered hiding at
 Hindlip Hall with Henry Garnet. Several men involved in this event
 were killed during a skirmish at the Holbeche House. Some historians
 believe that Francis Tresham was responsible for sending the
 anonymous letter that warned Lord Monteagle of this event. Robert
 Catesby (KAYTS-bee) organized this event, which was effectively ended
 when a search of an undercroft below the House of Lords revealed Guy
 Fawkes. Name this 1605 plot to assassinate King James I (the first)
 by using a certain explosive.
***** ANSWER:
Gunpowder Treason Plot
*** Fine Arts: Name these American artists
**** Team B:                                                          :drill:
This artist depicted fellow Hudson River School painter Thomas Cole
 and poet William Cullen Bryant standing on a cliff in the painting
 Kindred Spirits.
***** ANSWER:
Asher Brown Durand
**** Team A:                                                          :drill:
This early American painter is best known for his painting Declaration
 of Independence, which graces the backside of the two-dollar bill.
***** ANSWER:
John Trumbull
**** Tossup:                                                          :drill:
 The first book by art historian Lloyd Goodrich dealt with the Life
 and Work of this artist, who painted the Biglin brothers in several
 of his works. This artist had his wife, Susan, paint himself into the
 right end of a work that shows Dr.  David Agnew holding a
 scalpel. This artist and five other young men are shown enjoying Dove
 Lake while naked in the painting The Swimming Hole. The Schuylkill
 (SKOOL-“kill”) River was the setting of another of his paintings
 which shows a single scull being used by Max Schmitt. In his best
 known work, a woman cringes as a crowd witnesses a surgery being
 performed by the title doctor. Name this artist of The Gross Clinic.
***** ANSWER:
Thomas Cowperthwait Eakins (AY-kinz)
*** Life Science: Name these structures found within a typical cell.
**** Team A:                                                          :drill:
This portion of the cyto·skeleton is organized by MTOCs. Dynein
(“DIE”-neen) and kinesin move across them.
***** ANSWER:
microtubules
**** Team B:                                                          :drill:
This part within the nucleus is the location where ribosomes are
synthesized.
***** ANSWER:
nucleolus
**** Tossup:                                                          :drill:
 L-form bacteria are artificially created to lack this structure,
 while mycoplasmas are bacteria that naturally do not have
 it. Vanco·mycin is a glyco·peptide antibiotic that inhibits its
 synthesis. In some organisms, the outermost portion of it is called
 the middle lamella. This structure can be bypassed using
 plasmodesmata and sometimes contains a waxy portion called the
 Casparian strip. In diatoms, this structure is called a frustule
 (FRUST-yule) and is comprised of silica. The lignin is found in this
 structure in plants. Name this protective layer of the cell, which is
 made of pep·tido·glycan in bacteria and cellulose in plants.
***** ANSWER:
cell walls [prompt on “walls”]
** Round Two
*** English / World Literature: Give the following related to lunar references in works of literature.
**** Team B:                                                          :drill:
From the Earth to the Moon is one of the many science fiction novels
 in which what author depicts journeys to the moon?
***** ANSWER:
Jules Gabriel Verne
**** Team A:                                                          :drill:
What author of Comical History of the States and Empires of the Moon
 is better known for appearing in a 19th century play in which he
 secretly loves Roxane?
***** ANSWER:
Hercule-Savinien Cyrano De Bergerac
**** Tossup:                                                          :drill:
The oldest piece of prose in this country’s literary tradition
 describes a girl that is found in a plant leaf as a youth and raised
 by human foster-parents before becoming Princess of the Moon. A
 novelist from this country wrote about an old man, who visits an
 establishment in which all of the young girls have been drugged, in
 the novella The House of the Sleeping Beauties. That author from this
 nation also wrote Snow Country, which is set in a hot springs town,
 or onsen.  Name this country that was home to the writer Yasunari
 Kawabata.
***** ANSWER:
Japan [or Nihon-koku or Nippon-koku]
*** American Government / Economics: Name the following related to the economics of living.
**** Team A:                                                          :drill:
The Case-Shiller metric is an example of what measure of the cost of
 living, which is calculated for a “basket of goods”?
***** ANSWER:
consumer price index or CPI
**** Team B:                                                          :drill:
What economic variable in the cost of living is often controlled
 through the use of namesake price ceilings? For a business, this cost
 is often tax-deductible.
***** ANSWER:
rent
**** Tossup:                                                          :drill:
The golden rule of this quantity is used to figure out what is the
 ideal macroeconomic level of it for growth. This quantity, which is
 the S in the IS-LM model, is the upper bound on the so-called
 “reserve ratio”, which is defined as the amount of money the Federal
 Reserve mandates that banks keep on hand. A financial institution
 that specializes in mortgages is called a “[this] and loan
 bank”. Accounts named for this quantity feature a rate of return that
 ideally beats the inflation rate. Name this quantity, which is
 defined as the portion of income one keeps for future use.
***** ANSWER:
savings rate
*** Physical Science: Name these acids.
**** Team B:                                                          :drill:
This strong acid, which was called oil of vitriol in antiquity, is
made by the lead chamber and contact processes.
***** ANSWER:
sulfuric acid [or H2SO4]
**** Team A:                                                          :drill:
This other strong acid, which is formed from the Ostwald process, can
come in red and white fuming varieties.
***** ANSWER:
nitric acid [or HNO3]
**** Tossup:                                                          :drill:
A “trifluoro” derivative of this acid is used in reverse phase HPLC to
 increase resolution. When combined with sodium bi·carbonate, this
 acid reacts to form short-lived carbonic acid as one of its
 products. If no water is present in a solution of this acid, it is
 termed “glacial.” An outdated process for synthesizing this acid
 makes use of a catalyst containing rhodium, and that process was
 supplanted by one that uses an iridium catalyst; both of those
 processes add a carbonyl group to methanol. This acid is made through
 the Monsanto and Cativa processes. Name this carboxylic acid, which
 is found in low concentrations in vinegar.
***** ANSWER:
acetic (uh-SEE-tik) acid [or ethanoic acid or CH3COOH or CH3CO2H or C2H4O2]
*** Geography: Name these islands.
**** Team A:                                                          :drill:
The Mona Passage separates Puerto Rico from this Caribbean island that
 contains the nations of Haiti and Santo Domingo.
***** ANSWER:
Hispaniola (hih-span-YOH-lah) [or La Espanola]
**** Team B:                                                          :drill:
The Strait of Malacca separates the Malay Peninsula from this largest
 all-Indonesian island whose most populous city is Medan.
***** ANSWER:
Sumatra [or Sumatera]
**** Tossup:                                                          :drill:
The remains of a human known as the Cheddar Man were discovered in a
 namesake gorge on this island. To the northwest of this island is a
 strait known as The Minch, and the western terminus of its Penwith
 Peninsula is known as “Land’s End.” The body of water directly east
 of this island has a shallow area known as Dogger Bank. Ben Nevis is
 the highest mountain on this island, which is directly south of the
 Orkney Islands. The Severn is the longest river on this island, which
 the Strait of Dover separates from France. The River Thames (temz)
 flows through the most-populous city on what largest European island
 which is directly east of Ireland?
***** ANSWER:
Great Britain [do not accept or prompt on “United Kingdom,” “England,” “Scotland,” or “Wales”]
*** American History: Name these events in which many people were killed.
**** Team B:                                                          :drill:
Several hundred members of the Lakota tribe were killed during this
 1890 skirmish which began after an attempt to disarm a Lakota man
 named Black Coyote led to the discharge of a rifle.
***** ANSWER:
Wounded Knee Massacre [or Battle of Wounded Knee Creek or Chankpe Opi Wakpala]
**** Team A:                                                          :drill:
Thirty-six people were killed in this 1937 incident in Lakehurst, New
 Jersey that prompted reporter Herbert Morrison, whose news team was
 recording at the time, to exclaim “Oh the humanity!”
***** ANSWER:
Hindenburg disaster [accept Hindenburg explosion or other equivalent answers that mention Hindenburg]
**** Tossup:                                                          :drill:
The remains of many of those killed during this event were first
 discovered at the Fresh Kills landfill. Operation Yellow Ribbon was
 initiated in response to this event, which was the subject of an
 investigation by a group headed by Thomas Kean. One casualty of this
 event was Todd Beamer, who spoke the phrase “let’s roll” shortly
 before being killed outside of Shanksville, Pennsylvania. This event
 was chiefly planned by Khalid Sheikh Mohammed (kah-LEED “shake”
 moh-HAH-med), and it led directly to passage of the PATRIOT Act. Name
 this 2001 event in which al-Qaeda (al-KYE- duh) terrorists flew
 airplanes into the Pentagon and World Trade Center towers.
***** ANSWER:
9/11 attacks [accept equivalents such as September 11th attacks or more specific equivalents such as the
 World Trade Center attacks]
** Alphabet Round – Letter F
*** Give                                                              :drill:
 Type of mutation in which a nucleotide base is added or deleted,
 causing a change in the codon sequence.
**** ANSWER:
frameshift
*** Give                                                              :drill:
 This language group, which is spoken in a similarly named northerly
 Dutch province, is the living language that is the closest
 linguistically to English.
**** ANSWER:
Frisian
*** Give                                                              :drill:
 Retired English professor who is too apprehensive to directly fight
 against the book burners in Ray Bradbury’s Fahrenheit 451.
**** ANSWER:
Faber
*** Give                                                              :drill:
 (TWO WORD ANSWER) – U.S. political party of the 1840s and 1850s which
 opposed expansion of slavery into western territories.
**** ANSWER:
Free Soil Party (TWO WORD ANSWER)
*** Give                                                              :drill:
 This neoclassical sculptor is known for his sculpture The Minuteman
 as well as the statue of Abraham Lincoln in the Lincoln Memorial.
**** ANSWER:
Daniel Chester French
*** Give                                                              :drill:
 (HYPHENATED OR TWO WORD ANSWER) – These diagrams in physics are used
 to illustrate all the possible forces acting on an object, allowing
 for the equilibrium condition or magnitude of forces to be
 determined.
**** ANSWER:
free body diagrams or free-body diagrams (HYPHENATED OR TWO WORD ANSWER)
*** Give                                                              :drill:
 After his victory in the Spanish Civil War, this man ruled as
 Dictator of Spain from 1939 to 1975.
**** ANSWER:
Francisco Franco y Bahamonde
*** Give                                                              :drill:
 Belgian composer best-known for his Violin Sonata in A Major and
 Symphony in D Minor.
**** ANSWER:
Cesar-Auguste-Jean-Guillaume-Hubert Franck
*** Give                                                              :drill:
 Klaus Mann’s novel about a clown is one of the many adaptations of
 the legend of this man, who sells his soul to the devil for knowledge
 in a play by Goethe.
**** ANSWER:
Faust [accept Faustus or Dr. Faust]
*** Give                                                              :drill:
 (TWO WORD ANSWER) – Occupation of the two men shown Descending the
 Missouri in an 1845 painting by George Caleb Bingham.
**** ANSWER:
fur traders [accept fur trading] (TWO WORD ANSWER)
*** Give                                                              :drill:
 This scientist’s namesake paradox addresses the mathematical
 improbability of detecting extra-terrestrial life, given the speed of
 interstellar travel and potential number of stars.
**** ANSWER:
Enrico Fermi
*** Give                                                              :drill:
 (TWO WORD ANSWER) – Compatibilism is defined as the philosophical
 position that this idea is reconcilable with determinism. It is
 commonly defined as the ability for a human to make their own
 decisions.
**** ANSWER:
free will (TWO WORD ANSWER)
*** Give                                                              :drill:
 Group from Greek mythology whose members were Clotho, Lachesis, and
 Atropos.
**** ANSWER:
Fates
*** Give                                                              :drill:
(MULTI-WORD ANSWER) – Taking its title from Thomas Gray’s “Elegy
 Written in a Country Churchyard”, this novel focuses on Bathsheba
 Everdene and her three potential suitors: Gabriel Oak, Sergeant Troy,
 and William Boldwood.
**** ANSWER:
Far From the Madding Crowd (MULTI-WORD ANSWER)
*** Give                                                              :drill:
 Former U.S. Secretary of the Interior who was sent to prison for his
 role in the Teapot Dome Scandal.
**** ANSWER:
Albert Bacon Fall
*** Give                                                              :drill:
 (MULTI-WORD ANSWER) – “All temporary things create suffering” and “we
 desire these things, thus we are constantly reincarnated” are two
 statements of this Buddhist quartet of principles.
**** ANSWER:
Four Noble Truths (MULTI-WORD ANSWER)
*** Give                                                              :drill:
 European gulf which receives the Neva River.
**** ANSWER:
Gulf of Finland
*** Give                                                              :drill:
 (TWO WORD ANSWER) – Quantity equal to the number of valence electrons
 minus the sum of the number of lone pairs and half the number of
 bonding electrons.
**** ANSWER:
formal charge (TWO WORD ANSWER)
*** Give                                                              :drill:
 This man, the son of Japanese parents, served as President of Peru
 between 1990 and 2000.
**** ANSWER:
Alberto Fujimori
*** Give                                                              :drill:
 This English novelist wrote a novel about Tom Jones, a lothario who
 develops feelings for his neighbor’s daughter, Sophia Western.
**** ANSWER:
Henry Fielding
** Lightning Round
*** Give                                                              :drill:
Parts of this novel are set at the Palazzo Roccanera (PUH-lats-oh
 roh-cuh-NAIR-uh), which the author describes as dungeon-like. Late in
 this novel, it is revealed that Pansy is the illegitimate daughter of
 Madame Merle. Though this novel’s title character rejects the
 proposals of Lord Warburton and Caspar Goodwood, she does accept the
 marriage proposal of Gilbert Osmond. Name this novel that documents
 the choices of Isabel Archer and was written by Henry James.
**** ANSWER:
The Portrait of a Lady
*** Give                                                              :drill:
The Cosiguina (KOSS-ih-gween-uh) Peninsula contains the westernmost
 point of this nation, which controls the Little and Big Corn
 Islands. This nation is on the south side of the Gulf of Fonseca, and
 its city of Bluefields is the most populous along the Mosquito
 Coast. In December 2014, the Hong Kong-based HKND Group began
 construction on a canal that will run through its namesake lake,
 which is the largest in Central America. Situated between Costa Rica
 and Honduras is what nation whose capital is Managua (mah-NAH-gwah)?
**** ANSWER:
Republic of Nicaragua [or Republica de Nicaragua]
*** Give                                                              :drill:
The date that ends this period is determined by the appearance of the
 paschal full moon, and some groups recognize the start of this period
 on Clean (*) Monday. The RCIA program concludes at the end of this
 period in the Catholic Church, whose adherents often give up meat on
 Fridays during this period. This period includes Palm Sunday, and for
 many faiths it begins on Ash Wednesday. Name this approximately 40
 day Christian season which ends at Easter.
**** ANSWER:
Lent [accept Easter Triduum (TRID-ew-um) or Paschal Triduum or Holy Triduum before (*); prompt on
 “Triduum” before (*); do not accept or prompt on any of the aforementioned answers after (*)]
*** Give                                                              :drill:
This standard does not currently support the use of the marquee
 element, which was introduced with the first iteration of Microsoft’s
 IE. This language, whose formalisms are maintained by the W3C, is
 currently in its fifth iteration. This language’s layout can be
 modified by cascading style sheets, and it typically uses tags
 denoted by angle brackets to modify content that is retrieved from a
 web server. Name this language that is used to make web documents.
**** ANSWER:
HTML 5 [or Hypertext Markup Language 5]
*** Give                                                              :drill:
One ruler of this empire utilized the talents of painter Ustad Mansur
 (OOSE-tod mahn-“SORE”). The Sayyid (“sigh”- YEED) brothers briefly
 held influence over this empire, one ruler of which was deposed by
 members of the Suri Dynasty.  It was formed after the First Battle of
 Panipat (PAH-nih-paht), and its ruler Jahangir (juh-HAHN-geer) was
 succeeded by the man who commissioned construction of a mausoleum for
 his wife in the city of Agra, India. Name this Muslim Empire of India
 ruled by such men as Humayun (hoo-MAH-yoon), Babur (BAH-boor), and
 Shah Jahan (juh-HAHN).
**** ANSWER:
Mughal (MOH-gul) Empire [or Mogul Empire; accept Mughal Dynasty or Mogul Dynasty or Gurkani]
*** Give                                                              :drill:
This poet recalled the smell of green tamarinds elating his nostrils
 in a poem set on a hot autumn night; that poem is entitled “Exotic
 Perfume.” Another of his poems is addressed to the “Hypocrite
 reader, - my fellow, - my brother!” That poem, “Au Lecteur” (oh
 LEK-tur), appears in a collection by this author whose sections
 include “Revolt”, “Wine”, “Death”, and “Spleen and Ideal.” Name this
 author whose poetry appears in the collection Flowers of Evil.
**** ANSWER:
Charles Pierre Baudelaire (boh-duh-“LAIR”)
*** Give                                                              :drill:
This man composed the film score to the movie The Secret Agent and a
 film depicting life out of balance titled Koyaanisqatsi
 (coy-ahn-iss-KAHT-zee). One of his operas opens a trilogy that
 includes Akhenaten (AWK-en-aht-en) and Satyagraha (sawt-yuh-GRA-hah);
 that opera includes a scene in which the name “Mr. Bojangles” is
 repeated fifty-eight times. That opera by this composer is punctuated
 by knee plays and cryptically makes reference to the title physicist.
 Name this composer of the opera Einstein on the Beach.
**** ANSWER:
Philip Morris Glass
*** Give                                                              :drill:
To make a graph named after this equation, one takes the natural log
 of both sides and plots temperature to the minus one power on the x
 axis. A quantity in this equation is found by multiplying the
 frequency factor and steric factor, which take into account molecular
 collisions. The namesake of this equation formulated the idea of
 activation energy, which appears in it. Name this equation that is
 used to find the rate constant of a reaction and named after a
 Swedish scientist.
**** ANSWER:
Arrhenius equation
*** Give                                                              :drill:
This leader installed Manco (MAHN-koh) as the puppet ruler of a
 certain empire, and he was the leader of a group dubbed the “Famous
 Thirteen.” He was killed in response to his brothers’ decision to
 execute Diego de Almagro. Prior to his execution, Vasco Nunez de
 Balboa (VOSS-coh NOON-yez day bal-BOH-uh) was captured by troops led
 by this man.  his victory at the Battle of Cajamarca
 (kah-hah-MAR-kah), he received a room full of gold from a captive
 leader whom he subsequently executed in 1533. Name this Spaniard who
 killed Atahualpa (ah-tah-WAHL-pah) in his conquest of the Incan
 Empire.
**** ANSWER:
Francisco Pizarro Gonzalez
*** Give                                                              :drill:
This man classified automata (aw-TOM-uh-tuh) as recursively
 enumerable, context-sensitive, context-free, and regular in a
 hierarchy of formal grammars. He wrote about the “political economy
 of the mass media” in Manufacturing Consent. This student of Zellig
 Harris examined the nonsensical sentence “colorless green ideas sleep
 furiously” in Syntactical Structures, which outlines his theory of
 transformational grammars. Name this influential linguist who taught
 at MIT.
**** ANSWER:
Avram Noam Chomsky
*** Give                                                              :drill:
Peter Tchaikovsky’s (chy-KOFF-skeez) The Seasons was written for this
 instrument. Carl Czerny (“CHAIR”-nee) and Muzio Clementi both wrote
 works called Gradus ad Parnassum, which contain pieces meant to teach
 technique for it.  John Cage inserted various objects in the strings
 of this instrument, which are called the “prepared” type. Scott
 Joplin’s ragtime music was written for what keyboard instrument?
**** ANSWER:
pianoforte
*** Give                                                              :drill:
This poem states “Thanks for the heavenly message brought by thee,
 child of the wandering sea” at the beginning of its fourth
 stanza. Its title object is composed of “webs of living gauze [that]
 no more unfurl.” This poem commands “Leave thy low-vaulted past” and
 “Build thee more stately mansions, O my soul.” It opens by comparing
 the title animal to a “ship of pearl.” A mollusk is the subject of
 what poem authored by Oliver Wendell Holmes?
**** ANSWER:
“The Chambered Nautilus”
*** Give                                                              :drill:
In catalase, atoms of this element switch between +3 and +4 oxidation
 states in de·toxifying hydrogen peroxide. The most common form of
 anemia is one in which this element is deficient in the body. This
 element is combined with sulfur in proteins such as Co·enzyme Q. This
 metal is found in the middle of a porphyrin (POR-fuh-rin) ring in a
 protein that binds to oxygen. Name this metal found in hemoglobin.
**** ANSWER:
iron
*** Give                                                              :drill:
This leader once got into a verbal altercation with Filipino
 politician Lorenzo Sumulong at a U.N. meeting. This leader’s
 agricultural policies were influenced by his visit to the Garst
 family farm. He received spy Rudolf Abel in an exchange for Gary
 Powers following the U-2 incident. This leader denounced his
 predecessor in the Secret Speech, and he was ultimately pressured to
 retire and succeeded by Leonid Brezhnev (LEY-uh-nid BREZH-nef)
 in 1964. Name this leader of the Soviet Union who succeeded Joseph
 Stalin.
**** ANSWER:
Nikita Sergeyevich Khrushchev (KROOSH-choff)
*** Give                                                              :drill:
During this event, all Title IX (nine) claims involving sexual
 assaults went uninvestigated by the Department of Education. It was
 presaged with Ted Cruz’s 21-hour long filibuster and the placing of
 800,000 federal workers on furlough. It ended on October 17th, 2013
 after Obama signed a law that extended the debt limit to February of
 the next year. Name this incident in which bipartisan cooperation
 broke down, leading to the executive branch’s inability to function.
**** ANSWER:
U.S. government shutdown of 2013 [accept obvious equivalents]
*** Give                                                              :drill:
At the top of this painting a group of people attempt to enter a
 broken eggshell lying along the shore of a lake. A nude woman
 balancing a die on her head and a pig wearing a nun’s headdress
 appear in a portion of this painting that also includes a pair of
 human ears brandishing a knife. Various figures eat giant fruit in
 this work, which depicts God’s presentation of Eve to Adam in its
 left panel. The title location comprises the center panel of what
 16th century triptych (TRIP-tik) by Hieronymous Bosch
 (hee-eh-ROHN-ee-“muss” “bosh”)?
**** ANSWER:
The Garden of Earthly Delights [or Tuin der lusten]
*** Give                                                              :drill:
In a contest, this deity used a sword to create three goddesses while
 her competitor used a necklace to create five gods.  deity was born
 from the left eye of her father and is worshiped at the Ise (EE-say)
 Shrine. Uzume’s (oo-ZOO-mayz) dancing helped lead this goddess out of
 a cave in which she hid after acts of rage from her brother Susanowo
 (soo-SAH- noh-oh). Name the Shinto goddess of the sun.
**** ANSWER:
Amaterasu-Omikami (ah-MAH-teh-rah-soo)
*** Give                                                              :drill:
The Rankine-Froude (ran-KEEN frowd) model of these devices is used to
 describe their behavior, as is blade element theory. Underwater
 vehicles often make use of a type of this device whose pitch can be
 controlled; contra-rotation can be achieved in the “scimitar” type of
 them. Turbines are often connected to these types of fans, which
 convert rotational motion into thrust. Name these devices which can
 be found on the front of airplanes.
**** ANSWER:
propellers [or propeller blade]
*** Give                                                              :drill:
One account of this event was written by Reverend William
 Carwardine. Justice David Brewer issued the unanimous opinion in a
 Supreme Court case which confirmed Attorney General Richard Olney’s
 right to obtain an injunction in response to this event. Against the
 wishes of Governor John Altgeld, this event was ended by Federal
 troops sent in by Grover Cleveland. Eugene V. Debs led the American
 Railway Union in the organization of what 1894 strike against a
 namesake, Chicago railroad company?
**** ANSWER:
Pullman Strike
*** Give                                                              :drill:
In one of this author’s plays, characters discuss an old man that
 crawls under a lorry. In that play by this author, the two main
 characters argue about the phrase “light the kettle” and “light the
 gas.” That drama by this author focuses on two hitmen named Ben and
 Gus, who receive commands through the title conveyance. The 2005
 Nobel Prize in Literature was awarded to what British author of
 “comedies of menace” such as The Dumbwaiter?
**** ANSWER:
Harold Pinter
 
