* 2015 OAC Regionals – Round 3
** Round One
*** American Literature: Name these Pulitzer Prize-winning authors.
**** Team A:                                                          :drill:
The only writer to have won both the Pulitzer Prize for Poetry and the
 Novel is what author of All the King’s Men?
***** ANSWER:
Robert Penn Warren
**** Team B:                                                          :drill:
What poet of “Miniver Cheevy” won three Pulitzer Prizes for Poetry,
 one of which was for his Arthurian poem Tristram.
***** ANSWER:
Edwin Arlington Robinson
**** Tossup:                                                          :drill:
 This Pulitzer Prize winner’s only novella is set in a place called
 the Mecca and describes Maud Martha’s experiences in Chicago. This
 author wrote a poetic sequence that describes Chicago in A Street in
 Bronzeville before becoming Poet Laureate of Illinois. One of her
 poems describes “this old yellow pair” for whom “dinner is a casual
 affair.” In addition to penning “The Bean Eaters,” this author
 created a poem which describes “seven at the golden shovel” that
 “lurk late,” “sing sin,” “jazz june” and “die soon.” Name this
 African-American author who wrote “We Real Cool.”
***** ANSWER:
Gwendolyn Elizabeth Brooks
*** Mathematics: Pencil and paper ready. Give the following related to matrices (MAY-trih-seez). You will have 30 seconds for each team question.
**** Team B:                                                          :drill:
What is the determinant of a two by two matrix whose first row
 consists of “1, 3” (“one comma three”) and whose second row is “6, 6”
 (“six comma six”)?
***** ANSWER:
-12 or negative twelve or minus twelve
**** Team A:                                                          :drill:
What is the determinant of a two by two matrix whose first row
 consists of “4, 2” (“four comma two”) and whose second row is “5, 6”
 (“five comma six”)?
***** ANSWER:
14 or fourteen
**** Tossup:                                                          :drill:
 Pencil and paper will not be necessary. Jacobi’s theorem states that
 for odd square matrices with the “skew” type of this property, its
 determinant is equal to zero. Generally speaking, these matrices
 equal their own transpose. In set theory, a relation has this
 property if for every element “B” and element “A”, if “A” relates to
 “B” then it must be the case that “B” relates to “A”. An equivalence
 relation requires this property along with transitivity
 (trans-ih-TIV-ih-tee) and reflexivity. What is this mathematical
 property that in geometry refers to the ability to fold a shape onto
 itself?
***** ANSWER:
symmetry [accept word forms, such as symmetric]
*** World History: Name these European conflicts.
**** Team A:                                                          :drill:
The release of the Ems Dispatch by Otto von Bismarck helped lead to
 this 1870 to 1871 war which ended shortly after the capture of
 Emperor Napoleon III (the third) at the Battle of Sedan.
***** ANSWER:
Franco-Prussian War [accept Franco-German War]
**** Team B:                                                          :drill:
Giuseppe Garibaldi (joo-ZEP-pee gar-uh-BAWL-dee) led troops in all
 three of this 19th century series of wars which culminated in the
 unification of a certain nation under the rule of Victor Emmanuel II
 (the second).
***** ANSWER:
Wars of Italian Independence [accept Wars for the Independence of Italy or other equivalents; prompt on partial answers]
**** Tossup:                                                          :drill:
 A manuscript known as the Codex Gigas was plundered at the end of
 this conflict, during which two participants cemented their alliance
 with the Treaty of Barwalde. Ferdinand II’s (the second’s) succession
 of Matthias as Holy Roman Emperor intensified a part of this conflict
 that ended after the Battle of White Mountain. During its Battle of
 Breitenfeld, the Count of Tilly was defeated by a Swedish leader who
 was later killed at the Battle of Lutzen, Gustavus Adolphus.  This
 war, which began after the Defenestration of Prague, was ended by the
 Peace of Westphalia in 1648. Name this 17th century religious war
 which lasted three decades.
***** ANSWER:
Thirty Years’ War
*** Fine Arts: Name these Russian composers.
**** Team B:                                                          :drill:
This composer's String Quartet No. 2 features a famous nocturne. He
 also composed In the Steppes of Central Asia and the Polovtsian
 Dances.
***** ANSWER:
Alexander Porfiryevich Borodin (bor-uh-DEEN)
**** Team A:                                                          :drill:
This man used a recurring motif played by the violin to represent the
 title storyteller in Scheherazade (shuh- “HAIR”-uh-zahd). Among the
 work he did on other composers’ music was an orchestration of
 Mussorgsky’s Night on Bald Mountain.
***** ANSWER:
Nikolai Andreyevich Rimsky-Korsakov (RIM-skee-KOR-suh-koff) [prompt on partial answer]
**** Tossup:                                                          :drill:
 A tone poem by this composer uses a rhythm in 5/8 (“five” “eight”)
 time to depict rowing and was inspired by an Arnold Bocklin (BEK-lin)
 painting of the same name. A solo piano work by this composer opens
 with the notes A, G sharp, C sharp. He went through a depression that
 only ended after hypnotherapy and the success of a concerto that
 opens with eight crescendoing (cruh-SHEN-doh-ing) chords. This
 composer of Isle of the Dead inverted the theme for the eighteenth
 variation in a piece based off the twenty-fourth caprice of an
 Italian violin virtuoso. Name this composer, whose output includes
 four piano concertos, “Prelude in C sharp minor,” and Rhapsody on a
 Theme of Paganini.
***** ANSWER:
Sergei Vasilyevich Rachmaninoff (rock-MAHN-ih-nahff)
*** Life Science: Answer the following about viruses.
**** Team A:                                                          :drill:
This outer layer of a virus surrounds its genetic material. It is made
 up of proteins, sometimes arranged in shapes such as icosahedrons or
 cylinders.
***** ANSWER:
capsid
**** Team B:                                                          :drill:
Viruses that infect bacteria are specifically known by this term.
***** ANSWER:
bacteriophages
**** Tossup:                                                          :drill:
 This virus attaches to host cells using the surface glyco·protein
 gp120. Genes essential to this virus’s function and replication are
 tat and rev. People resistant to this virus are known as long term
 non·progressors, since they fail to show the most severe symptoms it
 causes. Drugs used to combat this virus include Combivir, which
 includes the molecule AzT.  This virus’s pol gene encodes for an
 integrase and reverse transcriptase. This lenti·virus causes low
 levels of helper T cells, which in turn severely weakens the body’s
 immune response. Name this retrovirus that is the causative agent of
 AIDS.
***** ANSWER:
HIV or human immunodeficiency virus [do not accept or prompt on “AIDS”]
** Round Two
*** English / World Literature: Name these authors who wrote about large beasts.
**** Team B:                                                          :drill:
What soldier, prisoner, and author wrote about the “questing beast” in
 his compilation of Arthurian myth, Le Morte Darthur (luh mort
 DAR-thur)?
***** ANSWER:
Thomas Mallory
**** Team A:                                                          :drill:
What author wrote about a giant bear who is exposed to the politics of
 the Beklan Empire in Shardik? A rabbit named Hazel is the protagonist
 of his novel Watership Down.
***** ANSWER:
Richard George Adams
**** Tossup:                                                          :drill:
 In one work this author wrote about Calidore (CAL-ih-door), a knight
 whose mission is to slay the Blatant Beast.  In that poem by this
 author, the recurring character of Colin Clout plays songs on his
 bagpipe. This man’s love for Elizabeth Boyle inspired his sonnet
 sequence Amoretti (ah-moh-RET-ee). Holiness, Temperance, Chastity,
 Friendship, Justice, and Courtesy are the themes of his masterpiece,
 which makes use of the ABABBCBCC (“A-B-A-B-B-C-B-C-C”) rhyme scheme
 and idealizes Queen Elizabeth as the title figure. Name this 16th
 century author of the epic poem The Faerie Queene.
***** ANSWER:
Edmund Spenser
*** American Government / Economics: These questions will involve the economics of society’s ability to make goods.
**** Team A:                                                          :drill:
What diagrams depict two goods, such as guns and butter, and a
 society’s ability to make them? They are generally used to illustrate
 the tradeoffs between making said two goods.
***** ANSWER:
production possibility frontier [or ppf, accept production possibilities frontier or production possibility
 diagram or production possibilities diagram]
**** Team B:                                                          :drill:
The production possibilities frontier illustrates this type of cost of
 making a good, which is defined as the alternatives one foregoes to
 engage in an activity.
***** ANSWER:
opportunity cost
**** Tossup:                                                          :drill:
 In agreement with the views of the libertarian Richard Cobden, this
 economist argued that England’s ability to make technological
 advances were hampered by its desire to keep import duties high. He
 extended Ferdinand Lasalle’s (LUH-“Sal’s”) argument that payments to
 laborers would, in the long run, tend toward the level necessary for
 subsistence, which became known as his iron law of wages. Name this
 British economist who wrote Principles of Political Economy and
 Taxation and Rent in addition to developing a theory of international
 trade.
***** ANSWER:
David Ricardo
*** Physics: Answer the following related to James Clerk Maxwell.
**** Team B:                                                          :drill:
What scientist names the one of Maxwell’s equations that states that
 the divergence of a magnetic field must equal zero?
***** ANSWER:
Johann Carl Friedrich Gauss (gowss)
**** Team A:                                                          :drill:
This French scientist’s namesake law, which Maxwell re-derived,
 relates the current passing through a circuit to the strength of the
 magnetic field in the circuit.
***** ANSWER:
Andre-Marie Ampere (am-PEER)
**** Tossup:                                                          :drill:
 Along with James Clerk Maxwell, Wilhelm Wien (veen) names a type of
 this device that is unusually used to measure inductance. A
 Kelvin-Varley divider is an analog of this device that is used to
 split a circuit’s voltage. They were invented by Samuel Christie and
 rely on Kirchoff’s (KEER-coffz) laws to measure an unknown
 quantity. They are similar to a potentiometer
 (poh-TEN-“she”-om-ih-tur) and are used to measure the electrical
 resistance of an unknown component. Name these diamond-shaped
 configurations that consist of four resistors and are a type of
 bridge circuit.
***** ANSWER:
Wheatstone bridge [prompt on “bridge” or “bridge circuits”]
*** Geography: Name these American rivers.
**** Team A:                                                          :drill:
The cities of Laredo and El Paso lie along the banks of this river
 which forms the border between Texas and Mexico.
***** ANSWER:
Rio Grande [or Rio Bravo del Norte]
**** Team B:                                                          :drill:
The Shenandoah and Anacostia Rivers are tributary to this waterway
 that empties into Chesapeake Bay and separates Arlington County,
 Virginia from Washington D.C.
***** ANSWER:
Potomac (puh-TOH-mik) River
**** Tossup:                                                          :drill:
 The shipwreck of the Peter Iredale is visible near the mouth of this
 river, which forms the southern and eastern borders of the Colville
 Indian Reservation. This river receives flow from the Multnomah Falls
 just downstream from the Bonneville Dam within its namesake
 gorge. The cities of The Dalles and Astoria border this river, on
 which the Franklin D. Roosevelt Lake is located. The Snake River is
 this river’s largest tributary, and it is harnessed for hydroelectric
 power by the Grand Coulee Dam. Name this chief river of the Pacific
 Northwest which forms much of the border between Oregon and
 Washington.
***** ANSWER:
Columbia River
*** American History: Name these military generals.
**** Team B:                                                          :drill:
The American Expeditionary Forces during World War I were commanded by
 this general, nicknamed “Black Jack,” who also led the Punitive
 Expedition that sought to capture Mexican revolutionary Pancho Villa
 (PAHN-choh VEE-yah).
***** ANSWER:
John Joseph Pershing
**** Team A:                                                          :drill:
This general, who was called upon by Herbert Hoover to intervene
 against the Bonus Army in 1932, was commander of the U.N. forces that
 took part in the Korean War until being controversially replaced by
 Matthew Ridgway.
***** ANSWER:
Douglas MacArthur
**** Tossup:                                                          :drill:
Early in his military career, this man served as an aide on the
 Braddock Expedition. This commander was victorious at the Battle of
 Jumonville Glen, which led directly to an attack against him and his
 ultimate surrender at the Battle of Fort Necessity. The Conway Cabal
 became opposed to this commander after he lost a series of battles,
 including Brandywine, during the Philadelphia Campaign. This leader
 encamped his troops at Valley Forge a year after surprising Hessian
 troops at the Battle of Trenton. Name this commander-in-chief of the
 Continental Army during the Revolutionary War who went on to become
 the first U.S. President.
***** ANSWER:
George Washington
** Alphabet Round – Letter O
*** Give                                                              :drill:
Hyperbolic and Parabolic are two types of these trajectories; the
 Hohmann transfer is used to move between two different types of these
 trajectories.
**** ANSWER
orbits
*** Give                                                              :drill:
This author of The Life You Save May Be Your Own is perhaps better
 known for writing about a serial killer called the Misfit in her
 story “A Good Man is Hard to Find.”
**** ANSWER
Mary Flannery O’Connor
*** Give                                                              :drill:
Figure from Greek mythology who was the first wife of Paris before
being abandoned in favor of Helen of Troy.
**** ANSWER
Oenone (oh-NOH-nee)
*** Give                                                              :drill:
Santa Fe, New Mexico contains a museum dedicated to this American
 artist best known for paintings of flowers and images related to the
 American west.
**** ANSWER
Georgia Totto O'Keeffe
*** Give                                                              :drill:
Constellation which contains the stars Alnilam, Alnitak, and Mintaka.
**** ANSWER
Orion
*** Give                                                              :drill:
British general who led troops to victory at the Battle of Bloody
Marsh during the War of Jenkins’ Ear.
**** ANSWER
James Edward Oglethorpe
*** Give                                                              :drill:
MULTI-WORD ANSWER) – This “Hermetic” group’s leaders included Evelyn
 Underhill and Aleister Crowley. The hierarchy within this movement
 features so-called Secret Chiefs.
**** ANSWER
Hermetic Order of the Golden Dawn (MULTI-WORD ANSWER)
*** Give                                                              :drill:
The Black Box is one of many novels by what contemporary Israeli
 novelist, born with the surname Klausner, who is a perennial
 frontrunner for the literature Nobel Prize?
**** ANSWER
Amos Oz
*** Give                                                              :drill:
This philosophical argument, which is presented in St. Anselm’s
 Proslogium, uses “levels of conception” to argue that God must exist.
**** ANSWER
ontological argument
*** Give                                                              :drill:
Woodwind instrument to which orchestras often tune to.
**** ANSWER
oboe
*** Give                                                              :drill:
German term for the policy that was launched by Willy Brandt in 1969
 to improve relations between East and West Germany.
**** ANSWER
ostpolitik
*** Give                                                              :drill:
Body of water whose northernmost arm is the Shelikhov Gulf.
**** ANSWER
Sea of Okhotsk
*** Give                                                              :drill:
In arthropods, the individual unit of a compound eye.
**** ANSWER
ommatidium or ommatidia
*** Give                                                              :drill:
This sort of creature is the culprit that committed the crimes in the
 first story of ratiocination about C. Auguste Dupin, “Murders in the
 Rue Morgue.”
**** ANSWER
orangutang
*** Give                                                              :drill:
This man, who authored Journeys and Explorations in the Cotton
 Kingdom, was the landscape architect who designed much of Central
 Park in New York City.
**** ANSWER
Frederick Law Olmstead
*** Give                                                              :drill:
TWO WORD ANSWER) – 19th century route through the American west that
 connected Independence, Missouri to the Willamette Valley.
**** ANSWER
Oregon Trail (TWO WORD ANSWER)
*** Give                                                              :drill:
This gorge in Tanzania was inhabited by Homo Habilis a million years
 ago. Louis and Mary Leakey discovered some of the most notable human
 fossils here.
**** ANSWER
Olduvai Gorge
*** Give                                                              :drill:
TWO WORD ANSWER) – Field of study focusing on carbon compounds and
their reactions.
**** ANSWER
organic chemistry (TWO WORD ANSWER)
*** Give                                                              :drill:
MULTI-WORD ANSWER) – The line “Do I wake or sleep” ends this John
Keats poem about a bird.
**** ANSWER
Ode to a Nightingale” (MULTI-WORD ANSWER)
*** Give                                                              :drill:
1898 battle in which British general Herbert Kitchener defeated
Sudanese troops outside the city of Khartoum.
**** ANSWER
Battle of Omdurman
** Lightning Round
*** Give                                                              :drill:
After first being issued, these items were stored in an object created
 by Oholiab (oh-HOH-lee-ab) and Bezalel (BEZ- uh-lel). The man who
 first delivered these items used a veil to block the radiance coming
 from his face. A golden calf created by Aaron was observed when these
 items were first brought down from Mount Sinai on stone tablets. The
 Ark of the Covenant housed what Biblical rules, which were revealed
 to Moses and included such decrees as “honor thy father and mother”
 and “thou shalt not kill”?
**** ANSWER:
Ten Commandments or Decalogue [prompt on “Commandments”]
*** Give                                                              :drill:
In part of an equation named after this man, the volume is subtracted
 by a constant denoting the volume taken up by a mole of gas
 particles. That equation is a modification of the ideal gas law for
 real gases. Induced and permanent dipole interactions, as well as
 London dispersion forces, are types of intermolecular forces named
 after this scientist. Name this Dutch scientist.
**** ANSWER:
Johannes Diderik van der Waals
*** Give                                                              :drill:
One provision of this legislation was proposed by Illinois Senator
 Jesse Thomas. It was passed shortly after the failure of the
 Tallmadge Amendment, and its repeal prompted Abraham Lincoln to give
 the “Peoria Speech.” Maine was admitted as a state by this
 legislation, which prohibited slavery in western U.S. territories
 north of latitude 36 degrees 30 minutes. Name this (*) 1820
 legislation that admitted a Midwestern state whose capital is
 Jefferson City?
**** ANSWER:
Missouri Compromise [prompt on “Compromise of 1820” before (*)]
*** Give                                                              :drill:
One character in this story authored a treatise on hunting snow
 leopards in Tibet. This story, which takes place on Ship- Trap
 Island, ends with the main character deciding that he had never slept
 on a better bed. During the title activity, its narrator makes a
 Ugandan knife trap to kill Ivan and a Burmese tiger-pit to trap Count
 Zaroff’s hounds. Name this Richard Connell story in which Sanger
 Rainsford is hunted during the title “game.”
**** ANSWER:
“The Most Dangerous Game”
*** Give                                                              :drill:
One region in the southeast part of this nation is home to a unique
 type of limestone hut known as a trullo. The ruins of the city of
 Stabiae (STAY-bee-“eye”) are within this nation, which contains Lake
 Como near its northern border. This nation is on the western side of
 the Strait of Otranto. The Apennine Mountains are in this nation,
 which the Strait of Messina separates from its largest island,
 Sicily. Name this boot-shaped European nation whose capital is Rome.
**** ANSWER:
Italy [or Italian Republic or Italia or Repubblica Italiana]
*** Give                                                              :drill:
Examples of these objects include the chaotic Lorenz strange attractor
 as well as the Menger (mayn-JER) Sponge.  These objects always have a
 Hausdorff (“house”-DOORF) dimension that is greater than their
 topological dimension, and they include the Cantor set, which is
 nowhere dense. The first paper to propose these objects considered
 the coastline of England and was authored by Benoit Mandelbroit
 (BAYN-wah MAN-duhl-BRAH). Name these mathematical self- similar
 shapes.
**** ANSWER:
fractals
*** Give                                                              :drill:
This artist depicted the title figure being tied up and stripped of a
 red garment prior to his crucifixion in the painting The Disrobing of
 Christ. In another of his paintings, the title figure, Don Gonzalo
 Ruiz, is held in the hands of Saints Stephen and Augustine while
 Christ opens the heavens above. A third work depicts the Castle of
 San Servando and other buildings of the title, Spanish city. Name
 this Cretan-born painter of The Burial of the Count of Orgaz and View
 of Toledo (toh-LAY-doh).
**** ANSWER:
El Greco (GREH-koh) [or Domenikos Theotokopoulos (doh-MEN-ih-kohs THAY-oh-toh-KOH-poh-lus)]
*** Give                                                              :drill:
This kingdom may have been briefly ruled by members the Abydos
 (AB-ih-“dose”) Dynasty. The Turin King List documented many of the
 early rulers of this kingdom, which constructed the Karnak Temple
 Complex. The Ptolemaic (TOL-uh-mey-ik) Dynasty was the last to rule
 this kingdom, which buried many of its rulers in the Valley of the
 Kings; in 1922, Howard Carter discovered the tomb of one of those
 rulers, Tutankhamun (TOO-tan-kah-men). Name this ancient African
 civilization ruled by pharaohs.
**** ANSWER:
ancient Egypt [or Egyptian civilization]
*** Give                                                              :drill:
One character in this novel, Monsieur Noirtier (muh-SYUR nor-TEE-ay),
 communicates through blinking. Another character is betrayed by
 Caderousse (CAH-duh-roose) and rides off into the sunset with Haydee
 (high-day) at the end of the novel. Earlier, that character is
 imprisoned in the Chateau D’if (shaa-TOH deef), where he meets the
 Abbe Faria (uh- BAY fuh-REE-uh), who informs him of a secret cache of
 treasure on the title island. Edmond Dantes extracts revenge against
 his enemies in what novel written by Alexander Dumas (DEW-mah)?
**** ANSWER:
The Count of Monte Cristo [Le Comte de Monte-Cristo]
*** Give                                                              :drill:
This thinker observed a war between the Kasekala (KAH-say-kall-uh) and
the Kahama (kuh-HAHM-uh) from 1974 to
 1978. This thinker first travelled to Africa to do fieldwork after reading The Story of Dr. Doolittle by Hugh Lofting, as
 related in her memoir Through a Window. This social scientist established a namesake institute to do field work in Gombe
 (GAHM-bay) National Park, where she first observed a certain type of primate. Name this British female anthropologist
 best known for her work on chimpanzees.
**** ANSWER:
Dame Valerie Jane Morris Goodall [that war was actually a war between two rivaling groups of chimpanzees]
*** Give                                                              :drill:
When this goddess does not return from one task, her attendant
 Ninshubur seeks out Enki for help. She removes a piece of clothing
 after passing through each of seven gates and reaching the
 underworld, where her sister Ereshkigal (eh- RESH-kih-gall) inflicts
 her with sixty diseases. Tammuz (tah-MOOZ) was married to this
 goddess, who sends the Bull of Heaven to attack Gilgamesh after he
 rejects her. Name the Mesopotamian goddess of love.
**** ANSWER:
Ishtar [or Inanna or Astarte or Ashtoreth]
*** Give                                                              :drill:
To measure the angle of a ligament near this bone, one can draw the
 Blumensaat line. On the posterior side of this bone, muscles such as
 the adductor magnus are bound to a long ridge called the linea
 aspera. The greater and lesser trochanters (troh-KAN-turz) are found
 near the head of this bone. It joins the patella and tibia at its
 bottom, while its top is connected to the pelvis. Name the longest
 bone in the human body.
**** ANSWER:
femur (FEE-mur) [or thigh bone]
*** Give                                                              :drill:
This leader’s father and predecessor narrowly avoided death in the
 Borki train disaster. During a celebration honoring his rise to
 power, over 1,000 people were inadvertently killed in the Khodynka
 (kah-DEEN-kah) Tragedy. Father Gapon (gah-POHN) led protesters in a
 march against this ruler that culminated in Bloody Sunday, which
 helped lead to his issuance of the October Manifesto in 1905. Grigory
 Rasputin advised this leader, who was executed alongside his family
 in 1918. Name this final Russian czar.
**** ANSWER:
Nicholas II (the second) of Russia [or Nikolay II; prompt on “Nicholas” or “Nikolay”]
*** Give                                                              :drill:
A melody in the first movement of this symphony is taken from the song
 “Swing Low, Sweet Chariot.” The most famous melody from this symphony
 is first played by the English horn in D flat major. That melody,
 found in its Largo second movement, was used as the melody for the
 spiritual “Goin’ Home.” Name this symphony that was written while in
 the United States by Antonin Dvorak (ahn-toh-NEEN d’VOR-zhahk)
**** ANSWER:
Symphony No. 9 in E minor, “From the New World” [accept either underlined portion; accept New World
*** Give                                                              :drill:
or Z noveho sveta]
 15. The protagonist of one of this author’s novels grew up in Kellynch (KELL-inch) Hall, which is run by Sir Walter, who
 believes that his daughter Anne Elliot is too good for Captain Frederick Wentworth. Another of this author’s characters,
 John Willoughby (will-OH-bee), marries Sophia Grey even though he rescued Marianne from a rainstorm at the novel’s
 opening. Name this British author of Persuasion who wrote about the Dashwood sisters in Sense and Sensibility.
**** ANSWER:
Jane Austen
*** Give                                                              :drill:
Description acceptable. One theory about this object was that it is
 currently in Pyongyang, at the request of Kim Jong Il. This object is
 the subject of the so-called “phantom cell phone hypothesis.” The
 loss of this object was formalized in a speech given by Prime
 Minister Najib Razak. Its loss of life was superseded just a few
 months later, when pro-separatist Ukrainians shot down a different
 object of the same type. A multinational search has failed to find
 what vehicle that disappeared on March 8th, 2014 in southeast Asia?
**** ANSWER:
the missing Malaysian Airlines airplane [accept Malaysian Airlines Flight 370; accept equivalent answers
*** Give                                                              :drill:
mention “Malaysia(n)” and “(air)plane”; prompt on partial answer]
 17. The Dingley Act raised U.S. tariffs during the presidency of this man, who nominated his Attorney General, Joseph
 McKenna, to serve in the Supreme Court. Garret Hobart served as vice president under this man, who became president
 by utilizing a front porch campaign organized by Mark Hanna. At the Pan-American Exposition held in Buffalo, he was
 shot by Leon Czolgosz (CHOHL-“gosh”). Name this president who served from 1897 to 1901 and was succeeded by
 Theodore Roosevelt.
**** ANSWER:
William McKinley
*** Give                                                              :drill:
Nikolai Basov used a xenon (ZEE-non) dimer to create one of these
 devices by creating fake particles called excimers (EGGS-ih-merz). A
 solid-state example of these devices is sometimes made by achieving
 optical pumping by using a ruby rod as an amplification medium. They
 work by (*) stimulating the emission of radiation to produce an
 optical amplification of light, and their color is often given in
 wavelengths. Name these devices that are sometimes used as pen- sized
 pointers.
**** ANSWER:
lasers [accept Light Amplification by Stimulated Emission of Radiation before (*)]
*** Give                                                              :drill:
This novel’s narrator plays billiards with Count Greffi, a nobleman
 who speculates that Italy will win the war in which it is
 embroiled. Its main character fights in the Battle of Caporetto and
 later rows to Switzerland, where his lover gives birth to a stillborn
 child shortly before dying herself. It was inspired by its author’s
 experiences as an ambulance driver in World War 1. Catherine Barkley
 and Frederic Henry are the protagonists of what novel by Ernest
 Hemingway?
**** ANSWER:
A Farewell to Arms
*** Give                                                              :drill:
During World War 2, this work of art was protected by Deane Keller,
 who documented how a brick dome was constructed to protect it from
 incendiary bombs. It was supposed to stand on top of Florence
 Cathedral, but it was placed outside of the Palazzo della Signoria
 (puh-LATS-oh DELL-uh SEEN-yor-ee-uh) instead. It currently stands in
 the Galleria dell’Accademia [GAL-err-ee-uh dell ACK-uh-deem-ee-uh)
 and depicts a youth standing in a contrapposto pose.  Name this
 marble sculpture of a nude Biblical hero that was created by
 Michelangelo.
**** ANSWER:
David
