** Alphabet Round – Letter M
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       54feb1c6-2a0d-4f12-8cd2-54fbb91f41fc
    :END:
(NAME AND REGNAL NUMBER REQUIRED) – Final sultan of the Ottoman Empire.
**** Answer
Mehmed VI (the sixth) (NAME AND REGNAL NUMBER REQUIRED)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       2a5b0ea9-4582-4d38-987b-2bddca19e358
    :END:
This American poet authored the play J.B. and declared “a poem should not mean, but be” in Ars Poetica.
**** Answer
Archibald MacLeish
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       7bc30a7a-6311-494a-8c88-7c2006dc2a6b
    :END:
15th century Italian artist who painted such works as The Expulsion from the Garden of Eden and Tribute Money.
**** Answer
One character in this play states “He hath borne me upon his back a
thousand times” upon learning that a certain
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       f0e2431f-f43f-4604-ad2c-7fe4d8da0a54
    :END:
(ONE OR TWO WORD ANSWER) – Name for the simplest alcohol.
**** Answer
methanol or methyl alcohol (ONE OR TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       313d5e78-55e9-4960-a009-f61a403fc7e9
    :END:
This branch of philosophy, which analytic philosophy seeks to eliminate, is concerned with the nature of being. Aristotle wrote a treatise named for this branch of philosophy that introduces his idea of “potentiality” and “actuality.”
**** Answer
metaphysics
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       9b9adca9-af5c-4eeb-90fa-29aac0da7e9d
    :END:
Musical form in 3/4 time, often paired with a Trio in symphonies.
**** Answer
minuet
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       a1d7dc6e-c879-482f-be26-bd90b306a8ee
    :END:
(TWO WORD ANSWER) – 2nd century Roman Emperor who authored the Stoic work Meditations.
**** Answer
Marcus Aurelius Antoninus Augustus (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       78528dca-7e26-4c9d-b49a-393cefbc8c47
    :END:
In Percy Shelley’s poem “Ozymandias,” the speaker finds a statue with the lines “look on my works ye ____ and despair!” Fill in the blank.
**** Answer
mighty
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       3b9ab22a-69e3-4d8b-9d90-0e58b874cd40
    :END:
Most populous port city in the country of Kenya.
**** Answer
Mombasa
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       c827c609-0a48-4f61-a9c0-718faff3876b
    :END:
Giuseppe Verdi composed an opera named for this character, whose chorus includes witches and whose characters include Fleanzio and Banquo.
**** Answer
Macbeth or Macbetto
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       618f58ed-7879-4d3f-bad9-92f5015de3af
    :END:
(MULTI-WORD ANSWER) – The parallel axis theorem is a method of computing what quantity, which is often called the rotational analog of mass?
**** Answer
mass moment of inertia or polar moment of inertia (MULTI-WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       c3a99768-fa8d-412a-8b06-8e1a4d5d11cb
    :END:
American Revolutionary War battle at which Molly Pitcher supposedly supplied water to soldiers before taking part in the battle herself.
**** Answer
Battle of Monmouth
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       fcf0db95-8d77-4535-bb14-e7d575b63afa
    :END:
This American author wrote A View from the Bridge and After The Fall but is better known for writing a play about Joe Keller, who manufactures faulty airplane parts in All My Sons.
**** Answer
Arthur Asher Miller
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       f355e7e4-b400-4b0c-8f84-5aa34baa2e0d
    :END:
In Kabbalah, this term refers to a mystical strain of thought that places emphasis on meditating on the structure of heaven. It is named for the chariot of God in the Book of Ezekiel.
**** Answer
Merkaba [or Merkavah]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       9f38e821-cf0b-4688-bccd-9efaba1a4d0f
    :END:
(TWO WORD ANSWER) – These investment schemes are a collection of bonds and stocks that are brought together by a company; they are usually more diversified and thus less risky than investing in an individual stock.
**** Answer
mutual funds (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       c70855de-2bc1-4756-bd71-fb0c84528b5c
    :END:
Term for a symbiotic relationship between a plant and fungus.
**** Answer
mycorrhizae
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       7b7868dc-83da-4d8e-8b62-4aa9dbe578ef
    :END:
16th century Flemish cartographer who developed a namesake map projection in which lines of latitude and longitude are perpendicular to each other.
**** Answer
Gerardus Mercator
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       4cdd5d57-9bc1-4907-a130-003da735e9a3
    :END:
Woman from Greek mythology who bore Adonis after tricking her own father into sleeping with her.
**** Answer
Myrrha
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       b3b6a8a9-6641-4ec5-9600-5ea81ce0ffac
    :END:
Hardness is often measured using this scale, which assigns a value of one to talc and two to gypsum.
**** Answer
Mohs scale
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       9920c6ef-84d1-47bf-8929-5a93ea92e696
    :END:
This author wrote about Gustave von Aschenbach, a writer who develops an attraction to Tadzio and eventually perishes, in his novella Death in Venice.
**** Answer
Paul Thomas Mann

** Alphabet Round – Letter G
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       d10d48fe-8ddb-4edb-aa5b-9f91033ed50f
    :END:
(TWO WORD ANSWER) – This term refers to a densely packed region of
stars, usually part of a galaxy’s core that are bound by gravity.
**** Answer
globular cluster (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       fbc50684-c5b2-4ec3-889e-081b1ce40801
    :END:
Organization co-founded in 1867 by Oliver Kelley to serve as an
advocacy group for farmers.
**** Answer
The Grange [accept The National Grange of the Order of Patrons of
Husbandry]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       13218997-0949-43ae-a55f-b85d8b25b60d
    :END:
Set of three piano pieces by Erik Satie, which were named after
Ancient Greek festivals.
**** Answer
Three Gymnopedies or Trois Gymnopedies
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       e5d7097b-a511-4a62-b694-eee46969d4e9
    :END:
    (MULTI-WORD ANSWER) – Per and Beret Hansa are the primary
characters of this 1924 novel by Ole Rolvaag.
**** Answer
Giants in the Earth (MULTI-WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       035ddbc1-2693-450f-8aee-85007e21f9e9
    :END:
This African-American suspect was killed on July 17th, 2014 after he
was put into a chokehold by the NYPD. The grand jury chose not to
indict the officer responsible for his death.
**** Answer
Eric Garner
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       2cf2dd6f-4dcf-4bd7-bc89-13e68f89ceb1
    :END:
(TWO WORD ANSWER) – Object from Greek mythology which was the
focus of a quest by Jason and the Argonauts.
**** Answer
golden fleece (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       59924af3-c085-48e5-a10b-f03153f068b8
    :END:
In ballet, this term refers to a movement in which a leg is brushed
outward, which then takes the weight while the second leg is brushed
in to meet it.
**** Answer
glissade (glee-SAHD)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       b3daba36-aca5-4034-abd1-d7caba2ae635
    :END:
Liberal 19th century British prime minister who was the primary
political rival of Benjamin Disraeli.
**** Answer
William Ewart Gladstone
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       6aeee9c3-cdbf-49c3-94cc-fbdbdf9f423c
    :END:
(MULTI-WORD ANSWER) – Formula that gives the number of degrees of
freedom for a substance based on the number of distinct species and
phases that exist.
**** Answer
Gibbs phase rule (MULTI-WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       bbe7bcdc-8e15-4868-ad1e-d80324129ec1
    :END:
This aristocratic family has been engaged in a blood feud with the
Shepherdsons in The Adventures of Huckleberry Finn.
**** Answer
Grangerfords
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       9e89a61f-d648-4d6b-8f45-a673030e8089
    :END:
This Princeton anthropologist borrowed a term from Gilbert Ryle to
describe the act of describing a cultural act and all of its
sociological implications, which he termed “thick description.”
**** Answer
Clifford James Geertz
*** Give                                                              :drill:
SCHEDULED: <2018-12-03 Mon>
    :PROPERTIES:
    :ID:       197c228e-7a12-4685-942a-d07b8d1dafba
    :DRILL_LAST_INTERVAL: 10.764
    :DRILL_REPEATS_SINCE_FAIL: 3
    :DRILL_TOTAL_REPEATS: 3
    :DRILL_FAILURE_COUNT: 1
    :DRILL_AVERAGE_QUALITY: 3.667
    :DRILL_EASE: 2.6
    :DRILL_LAST_QUALITY: 4
    :DRILL_LAST_REVIEWED: [2018-11-22 Thu 15:59]
    :END:
(TWO WORD ANSWER) – Ionizing radiation can be detected using this
type of device, which is sometimes named for Walther
Muller. Radioactive materials are often detected using it.
**** Answer
Geiger-Muller Counter (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       a15d81d9-87ed-4e38-84d8-45bbcea4520d
    :END:
    18th century English artist best known for his portrait painting
titled The Blue Boy.
**** Answer
Thomas Gainsborough
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       7595a4c4-bcff-4e83-a0ae-8bdf866f4024
    :END:
Argentine-born Cuban revolutionary leader who was executed in 1967 by
Bolivian soldier Mario Teran.
**** Answer
Ernesto “Che” Guevara
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       ea3c00e8-fd87-44e4-b5fb-ef79caf0e71d
    :END:
Large Asian desert located within China and Mongolia.
**** Answer
Gobi Desert or Govi Desert or Gebi Desert
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       ebf0ec75-ac60-4248-85aa-7012fc8c9420
    :END:
(TWO WORD ANSWER) – Although it focuses on Harry Bertram and Dirk
Hatteraick, this novel by Sir Walter Scott is named for an astrologer
who predicts Harry Bertram’s future.
**** Answer
Guy Mannering (TWO WORD ANSWER)
*** Give                                                              :drill:
    SCHEDULED: <2018-11-26 Mon>
    :PROPERTIES:
    :ID:       86e99373-accf-42f0-bfc7-5d1d3792e98b
    :DRILL_LAST_INTERVAL: 3.86
    :DRILL_REPEATS_SINCE_FAIL: 2
    :DRILL_TOTAL_REPEATS: 3
    :DRILL_FAILURE_COUNT: 2
    :DRILL_AVERAGE_QUALITY: 1.0
    :DRILL_EASE: 2.36
    :DRILL_LAST_QUALITY: 3
    :DRILL_LAST_REVIEWED: [2018-11-22 Thu 17:04]
    :END:
Biblical garden where Jesus was arrested just prior to his
crucifixion.
**** Answer
Gethsemane (geth-SEM-uh-nee)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       baaf84d9-c629-48ed-8b10-d2293ae4c7f5
    :END:
Digestive organ found in animals such as birds that is used to
mechanically grind up food.
**** Answer
gizzard
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       9a6f76af-7fe9-4999-b225-215746d8da38
    :END:
(TWO WORD ANSWER) – Term used for the collection of legislative
programs overseen by Lyndon B. Johnson.
**** Answer
Great Society (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       2169f5a3-0c5f-4037-b9a1-9d365ed6eff5
    :END:
Francois Rabelais created this literary giant, the father of
Pantagruel, who, in one episode, puts a bunch of people in a salad and
eats them.
**** Answer
Gargantua

** Alphabet Round – Letter O
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       fc9d2c75-596a-409c-8c96-e6a5010f4d00
    :END:
Hyperbolic and Parabolic are two types of these trajectories; the
Hohmann transfer is used to move between two different types of these
trajectories.
**** ANSWER
orbits
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       f2aa56fb-46c7-43c3-bc5e-ee584057fcd2
    :END:
This author of The Life You Save May Be Your Own is perhaps better
known for writing about a serial killer called the Misfit in her story
“A Good Man is Hard to Find.”
**** ANSWER
Mary Flannery O’Connor
*** Give                                                              :drill:
    SCHEDULED: <2018-11-26 Mon>
    :PROPERTIES:
    :ID:       72c8b5af-4361-47b6-8b85-db56aae0e061
    :DRILL_LAST_INTERVAL: 3.86
    :DRILL_REPEATS_SINCE_FAIL: 2
    :DRILL_TOTAL_REPEATS: 2
    :DRILL_FAILURE_COUNT: 1
    :DRILL_AVERAGE_QUALITY: 1.5
    :DRILL_EASE: 2.36
    :DRILL_LAST_QUALITY: 3
    :DRILL_LAST_REVIEWED: [2018-11-22 Thu 16:59]
    :END:
Figure from Greek mythology who was the first wife of Paris before
being abandoned in favor of Helen of Troy.
**** ANSWER
Oenone (oh-NOH-nee)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       fa5218da-229b-4306-a6e8-4c12108ef553
    :END:
Santa Fe, New Mexico contains a museum dedicated to this American
artist best known for paintings of flowers and images related to the
American west.
**** ANSWER
Georgia Totto O'Keeffe
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       bbce08a3-a12b-4307-b101-71a904d8c2ff
    :END:
Constellation which contains the stars Alnilam, Alnitak, and Mintaka.
**** ANSWER
Orion
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       45c1b02e-0160-49f0-bb80-2fbddb89445b
    :END:
British general who led troops to victory at the Battle of Bloody
Marsh during the War of Jenkins’ Ear.
**** ANSWER
James Edward Oglethorpe
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       cf2853d7-d296-438e-b9e1-7a683eaa4427
    :END:
MULTI-WORD ANSWER) – This “Hermetic” group’s leaders included Evelyn
Underhill and Aleister Crowley. The hierarchy within this movement
features so-called Secret Chiefs.
**** ANSWER
Hermetic Order of the Golden Dawn (MULTI-WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       000a7380-047a-4d70-a4b5-6e489ba7cf47
    :END:
The Black Box is one of many novels by what contemporary Israeli
novelist, born with the surname Klausner, who is a perennial
frontrunner for the literature Nobel Prize?
**** ANSWER
Amos Oz
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       353fc0f9-b1e2-45b4-9a7a-368522b8d380
    :END:
This philosophical argument, which is presented in St. Anselm’s
Proslogium, uses “levels of conception” to argue that God must exist.
**** ANSWER
ontological argument
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       f4dc3972-4f4b-447a-b0c1-f3e5ab09ba61
    :END:
Woodwind instrument to which orchestras often tune to.
**** ANSWER
oboe
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       f1d42738-0b1f-4ca7-8da0-aa4fea4e3a47
    :END:
German term for the policy that was launched by Willy Brandt in 1969
to improve relations between East and West Germany.
**** ANSWER
ostpolitik
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       1dabd65b-d49f-4130-8315-f0a125a3f999
    :END:
Body of water whose northernmost arm is the Shelikhov Gulf.
**** ANSWER
Sea of Okhotsk
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       fc9dc8da-896f-44b8-b828-00f0c7a04b53
    :END:
In arthropods, the individual unit of a compound eye.
**** ANSWER
ommatidium or ommatidia
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       54363dc7-974f-4058-8571-bfaebd8b1d57
    :END:
This sort of creature is the culprit that committed the crimes in the
first story of ratiocination about C. Auguste Dupin, “Murders in the
Rue Morgue.”
**** ANSWER
orangutang
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       db4f637d-f834-4add-84fa-a0fa683561e2
    :END:
This man, who authored Journeys and Explorations in the Cotton
Kingdom, was the landscape architect who designed much of Central Park
in New York City.
**** ANSWER
Frederick Law Olmstead
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       3288516f-79c6-4f3a-8aa3-c91d10dd2f67
    :END:
TWO WORD ANSWER) – 19th century route through the American west that
connected Independence, Missouri to the Willamette Valley.
**** ANSWER
Oregon Trail (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       cb06114d-120f-43c3-b84c-2ed2f2136d65
    :END:
This gorge in Tanzania was inhabited by Homo Habilis a million years
ago. Louis and Mary Leakey discovered some of the most notable human
fossils here.
**** ANSWER
Olduvai Gorge
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       cf82a26c-0de4-42e8-876b-d1c4e90ff5d9
    :END:
TWO WORD ANSWER) – Field of study focusing on carbon compounds and
their reactions.
**** ANSWER
organic chemistry (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       5c4a0dbe-42a1-42f6-9bef-736b20646a0d
    :END:
MULTI-WORD ANSWER) – The line “Do I wake or sleep” ends this John
Keats poem about a bird.
**** ANSWER
Ode to a Nightingale” (MULTI-WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       7c1b7287-c393-404b-ab9c-8ecc6d1cc18b
    :END:
1898 battle in which British general Herbert Kitchener defeated
Sudanese troops outside the city of Khartoum.
**** ANSWER
Battle of Omdurman

** Alphabet Round – Letter N
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       75908df6-7327-48ce-bd56-be5c0a93afc0
    :END:
In classical mechanics, this is the force that counteracts the
gravitational force on an object. It also describes vectors that are
perpendicular to a plane.
**** ANSWER:
normal force
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       8629c707-1941-4ed1-b5cc-511e0dcef140
    :END:
A.D. 532 conflict during the reign of Byzantine Emperor Justinian that
broke out amid a chariot race.
**** ANSWER:
Nika riots or Nika revolts
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       0a86ce27-7a37-4195-aad1-d3c74db77fda
    :END:
Residence on Earth is a major collection by what Chilean poet, who
more notably wrote 20 Love Poems and a Song of Despair?
**** ANSWER:
Pablo Neruda
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       9a6b4782-de52-4859-a1ba-a6bf4b76a01f
    :END:
American body of water which surrounds Aquidneck Island.
**** ANSWER:
Narragansett Bay
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       ae89cfb4-9991-4d90-b3af-01730f2cddfb
    :END:
(TWO WORD ANSWER) – In this situation, there is no way to alter an
agent’s action such that changing that agent’s action would result in
a better payoff.
**** ANSWER:
Nash equilibrium (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       d87935db-defd-4c3f-8fcf-3ebe8a8e0c22
    :END:
(TWO WORD ANSWER) – 1787 legislation which established the methods by
which the lands from America’s first organized territory would be
admitted into statehood.
**** ANSWER:
Northwest Ordinance of 1787 (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       0e15a095-454b-474b-acba-7ec756e17673
    :END:
Set in the country of Costaguana, this novel features the character of
Charles Gould, who owns a silver mine near the port of Sulaco.
**** ANSWER:
Nostromo, A Tale of the Seaboard
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       f72a9225-80d9-4814-b7a0-65e7746cb126
    :END:
Type of organic molecule with a functional group consisting of a
carbon triple bonded to a nitrogen; it is found in a namesake type of
glove commonly used in laboratories.
**** ANSWER:
nitrile
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       ea39166c-2b93-483e-87a6-987b8537d7a2
    :END:
(MULTI-WORD ANSWER) – 1912 painting which resembled “an explosion in
a shingles factory” according to art critic Julian Street.
**** ANSWER:
Nude Descending a Staircase, No. 2 (MULTI-WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       4f3223d7-243d-438f-b076-a1f0d4d606e7
    :END:
Norse god of the sea, whom Skadi married after only looking at his
feet.
**** ANSWER:
Njord (nyord) [or Njordhr or Njordh or Njordr]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       f8433b9a-2b00-4570-bd67-6799103b95a9
    :END:
Along with the Hugo Award, this is one of the two major science
fiction awards for novels in the U.S. It was won in 2014 by Ann Leckie
for her novel Ancillary Justice.
**** ANSWER:
Nebula Award
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       1e2539f4-deb8-47f7-843f-d9b694329aaa
    :END:
German city which was used to host the trials for Nazis accused of war
crimes committed during World War II.
**** ANSWER:
Nuremberg [or Nurnberg]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       85ad9055-9192-4b40-9e0e-7a5bf7d50832
    :END:
This term refers to tides that are at their minimum, unlike spring
tides.
**** ANSWER:
neap tides
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       d3da268b-3ded-4035-9d1e-5e7ad10eb46c
    :END:
The Wahhabi group Boko Haram has kidnapped many schoolchildren in this
country, such as the hundreds of schoolgirls in its town of Chibok.
**** ANSWER:
Federal Republic of Nigeria
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       0d8e902b-9ac9-4bc0-aa4e-06b881930b63
    :END:
(HYPHENATED ANSWER) – 1517 document that was authored by Martin
Luther to protest various practices of the Catholic Church and posted
to a church door in Wittenberg.
**** ANSWER:
Ninety-Five Theses on the Power and Efficacy of Indulgences (HYPHENATED ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       1af69e73-d554-437b-8eba-b8f2b3ecbbfe
    :END:
Composer of symphonies nicknamed "The Four Temperaments" and
 "Inextinguishable."
**** ANSWER:
Carl August Nielsen
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       c1b84dd5-2f89-40ae-8197-3b6401b7741f
    :END:
 1842 treaty which ended the First Opium War between the United
Kingdom and China.
**** ANSWER:
Treaty of Nanking or Treaty of Nanjing
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       e977536c-08c4-4f8c-82e7-7cbe61cc0c70
    :END:
The most common type of white blood cell in the body, which are some
of the first to react in the immune response.
**** ANSWER:
neutrophils or neutrophil granulocytes
*** Give                                                              :drill:
    SCHEDULED: <2018-11-26 Mon>
    :PROPERTIES:
    :ID:       9f3726d4-454b-4f67-babc-bb02a78dd30c
    :DRILL_LAST_INTERVAL: 3.86
    :DRILL_REPEATS_SINCE_FAIL: 2
    :DRILL_TOTAL_REPEATS: 3
    :DRILL_FAILURE_COUNT: 2
    :DRILL_AVERAGE_QUALITY: 1.0
    :DRILL_EASE: 2.36
    :DRILL_LAST_QUALITY: 3
    :DRILL_LAST_REVIEWED: [2018-11-22 Thu 17:05]
    :END:
This Japanese-American sculptor is responsible for creating many of
the stage designs of the ballets of Martha Graham.
**** ANSWER:
Isamu Noguchi
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       26d052bc-77d1-42a9-a188-52df80d2f4d1
    :END:
This author wrote a novel about a greedy dentist titled McTeague as
well a novel about a conflict between railroaders and farmers in the
San Joaquin Valley in The Octopus.
**** ANSWER:
Benjamin Franklin “Frank” Norris Jr.

** Alphabet Round – Letter A
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       0afdc115-b97f-42cc-b14c-1792e6ca8144
    :END:
(HYPHENATED ANSWER) – This former eye doctor and leader of the Ba’ath
Party is the current President of Syria.
**** ANSWER:
Bashar Hafez al-Assad (HYPHENATED ANSWER)
 2. In classical mechanics, this vector quantity is defined as the time derivative of velocity.
 2. acceleration

*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       61810dbc-22b2-4424-869d-e275bf2e95ca
    :END:
This historian wrote the novels Esther and Democracy, but he is best
known for a Pulitzer Prize-winning account of his own “Education.”
**** ANSWER:
Henry Brooks Adams
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       d85c209f-fb49-4bdf-b9f1-d1328b16c744
    :END:
(TWO WORD ANSWER) – Term used to describe singing without
accompaniment.
**** ANSWER:
a cappella (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       f83258d1-75e8-45a7-9917-4d098b04c532
    :END:
Distinguished from comparative advantage, this term refers to the
ability of an agent to produce more of a good than a
competitor. Unlike comparative advantage, it does not explain why
international trade is mutually beneficial.
**** ANSWER:
absolute advantage
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       77ff29c1-d09b-4a97-b323-6c44c36c2a3f
    :END:
(MULTI-WORD ANSWER) – Document which outlined the way the
U.S. government was run before the ratification of the
U.S. Constitution.
**** ANSWER:
Articles of Confederation and Perpetual Union (MULTI-WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       fba059a8-467a-4939-b7ea-cb24ebc6c65a
    :END:
Neurodegenerative disease that causes dementia and is characterized by
beta-amyloid plaques that accumulate in the brain.
**** ANSWER:
Alzheimer’s disease
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       03ad62c9-e208-43d7-9699-11f8e8914a43
    :END:
This evil magician, who repeatedly deceives the Red Crosse Knight, is
the villain of most of book one of Edmund Spenser’s The Faerie Queene.
**** ANSWER:
Archimago
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       647190c8-af17-4c6e-a254-55bd7516a23d
    :END:
Christian season which ends on Christmas Eve.
**** ANSWER:
Advent
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       d66a852c-40d8-4361-a6c1-86fa6f49ed5a
    :END:
(TWO WORD ANSWER) – 1260 battle in which the Mongol Empire was
defeated by the Mamluks in present day Israel.
**** ANSWER:
Battle of Ain Jalut or Battle of Ayn Jalut (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       e8234a32-5df8-4fc6-85e0-88febddb4b39
    :END:
(TWO WORD ANSWER) – This film, which was directed by Francis Ford
Coppola, is a Vietnam War adaptation of Joseph Conrad’s Heart of
Darkness. It contains the line “I love the smell of napalm in the
morning.”
**** ANSWER:
Apocalypse Now (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       8f376778-475c-4d50-b30f-8e191889fb31
    :END:
This type of computer language usually involves manipulating registers
directly. Compilers typically turn a high-level language into this
kind of lower-level one.
**** ANSWER:
assembly language [accept assembler]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       a991839b-8666-44f5-96e2-343e801bdaec
    :END:
This novelist wrote a novel about Okonkwo, whose village undergoes
Westernization, titled Things Fall Apart. This man also wrote a sequel
to Things Fall Apart entitled No Longer at Ease.
**** ANSWER:
Chinua Achebe [or Albert Chinualumogu Achebe]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       ed2d2368-f015-4064-ba06-3a7fa0885097
    :END:
Spanish slave ship that was at the center of an 1841 Supreme Court
case after it landed in the U.S. following a successful slave mutiny.
**** ANSWER:
La Amistad
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       51c4a3f6-e404-4ecc-aaad-7d7af25be9eb
    :END:
Evil Egyptian deity who attacks Ra and the solar barge each day, but
ultimately fails.
**** ANSWER:
Apep or Apophis
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       6fd40b83-95f3-4ff2-a5f9-2817f335ef14
    :END:
(ONE OR TWO WORD ANSWER) – American artistic movement associated with
a group called “The Eight”, whose members included Robert Henri and
Everett Shinn.
**** ANSWER:
Ashcan School or Ash Can School (ONE OR TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       52d5a391-ad6f-4e49-96ad-8cee72904c9f
    :END:
Peninsula on which Baku, the capital of Azerbaijan, is located.
**** ANSWER:
Absheron Peninsula
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       543f5c8f-0818-4ef8-b984-ddfb7f8d9ba9
    :END:
(NAME AND REGNAL NUMBER REQUIRED) – Papal name used by Nicholas
Breakspear, the only Englishman to serve as Pope.
**** ANSWER:
Adrian IV (the fourth) (NAME AND REGNAL NUMBER REQUIRED)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       c7935f09-ab92-4c91-9fac-69fc82b45caf
    :END:
This literary term refers to the repeated use of a phrase at the
beginning of multiple clauses, such as “it was the best of times, it
was the worst of times…”
**** ANSWER:
anaphora
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       c41798b0-fc13-4031-b367-8283122dc7fa
    :END:
Element that is extracted and refined through the Bayer and
Hall-Heroult processes.
**** ANSWER:
aluminum or aluminium

** Alphabet Round – Letter F
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       40f2f1e4-53f5-488e-b748-fcece10540f8
    :END:
Type of mutation in which a nucleotide base is added or deleted,
causing a change in the codon sequence.
**** ANSWER:
frameshift
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       bfa0126e-ebb6-4e29-b448-20339e570c2d
    :END:
This language group, which is spoken in a similarly named northerly
Dutch province, is the living language that is the closest
linguistically to English.
**** ANSWER:
Frisian
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       0836fa8c-a6b4-4d17-92a7-736387503d60
    :END:
Retired English professor who is too apprehensive to directly fight
against the book burners in Ray Bradbury’s Fahrenheit 451.
**** ANSWER:
Faber
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       7370047a-44b1-428f-b591-b2bbb69d9b05
    :END:
(TWO WORD ANSWER) – U.S. political party of the 1840s and 1850s which
opposed expansion of slavery into western territories.
**** ANSWER:
Free Soil Party (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       e39acd08-9ff7-416e-8d82-a5ec42cb654b
    :END:
This neoclassical sculptor is known for his sculpture The Minuteman as
well as the statue of Abraham Lincoln in the Lincoln Memorial.
**** ANSWER:
Daniel Chester French
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       199fd104-b06d-4af2-a610-b4701c161529
    :END:
(HYPHENATED OR TWO WORD ANSWER) – These diagrams in physics are used
to illustrate all the possible forces acting on an object, allowing
for the equilibrium condition or magnitude of forces to be determined.
**** ANSWER:
free body diagrams or free-body diagrams (HYPHENATED OR TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       ae8d1e82-a9ad-4095-acdc-b0ff64543c55
    :END:
After his victory in the Spanish Civil War, this man ruled as Dictator
of Spain from 1939 to 1975.
**** ANSWER:
Francisco Franco y Bahamonde
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       9a39b037-a62d-4172-a20c-d32e375ea762
    :END:
Belgian composer best-known for his Violin Sonata in A Major and
Symphony in D Minor.
**** ANSWER:
Cesar-Auguste-Jean-Guillaume-Hubert Franck
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       6e5416c1-8d8c-4bea-9039-ea24d0382868
    :END:
Klaus Mann’s novel about a clown is one of the many adaptations of the
legend of this man, who sells his soul to the devil for knowledge in a
play by Goethe.
**** ANSWER:
Faust [accept Faustus or Dr. Faust]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       7fb3aff4-317a-43d8-b8b2-b0fed752301e
    :END:
(TWO WORD ANSWER) – Occupation of the two men shown Descending the
Missouri in an 1845 painting by George Caleb Bingham.
**** ANSWER:
fur traders [accept fur trading] (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       20a83a37-d3db-425e-8ab4-7bcc8ea88bfd
    :END:
This scientist’s namesake paradox addresses the mathematical
improbability of detecting extra-terrestrial life, given the speed of
interstellar travel and potential number of stars.
**** ANSWER:
Enrico Fermi
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       10d90688-ba5f-409b-b988-ef96162d2d5d
    :END:
(TWO WORD ANSWER) – Compatibilism is defined as the philosophical
position that this idea is reconcilable with determinism. It is
commonly defined as the ability for a human to make their own
decisions.
**** ANSWER:
free will (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       193c06c7-15bd-4729-a16e-c63b4464fb70
    :END:
Group from Greek mythology whose members were Clotho, Lachesis, and
Atropos.
**** ANSWER:
Fates
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       74adf56d-f399-478a-bb4c-925a2d8b7f76
    :END:
(MULTI-WORD ANSWER) – Taking its title from Thomas Gray’s “Elegy
Written in a Country Churchyard”, this novel focuses on Bathsheba
Everdene and her three potential suitors: Gabriel Oak, Sergeant Troy,
and William Boldwood.
**** ANSWER:
Far From the Madding Crowd (MULTI-WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       e437f7dc-bfdc-472e-a5a6-f6f2878b3ea5
    :END:
Former U.S. Secretary of the Interior who was sent to prison for his
role in the Teapot Dome Scandal.
**** ANSWER:
Albert Bacon Fall
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       ec79a4cf-7b9e-480f-90cb-781a013eee9b
    :END:
(MULTI-WORD ANSWER) – “All temporary things create suffering” and “we
desire these things, thus we are constantly reincarnated” are two
statements of this Buddhist quartet of principles.
**** ANSWER:
Four Noble Truths (MULTI-WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       dfc958b9-ab24-40be-b8a7-0fdd7e229276
    :END:
European gulf which receives the Neva River.
**** ANSWER:
Gulf of Finland
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       886317b0-283a-42b6-be74-156fab54ce06
    :END:
(TWO WORD ANSWER) – Quantity equal to the number of valence electrons
minus the sum of the number of lone pairs and half the number of
bonding electrons.
**** ANSWER:
formal charge (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       db61f78f-d3fb-4231-a248-f97bd069540c
    :END:
This man, the son of Japanese parents, served as President of Peru
between 1990 and 2000.
**** ANSWER:
Alberto Fujimori
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       f9747296-ea54-47ee-8327-2e226ee39878
    :END:
This English novelist wrote a novel about Tom Jones, a lothario who
develops feelings for his neighbor’s daughter, Sophia Western.
**** ANSWER:
Henry Fielding

** Alphabet Round – Letter S
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       383051e6-fb67-43c9-8fe9-6ec27e652926
    :END:
Civil War colonel who commanded the 54th Massachusetts Infantry, an
all African-American military unit, until his death at the Second
Battle of Fort Wagner.
**** ANSWER:
Robert Gould Shaw
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       a694b74b-fa32-4d20-96e4-c43906870aa5
    :END:
This term refers to philosophical activities, such as Zeno’s tortoise
and hair race, which consist of an infinite number of little
sub-actions. Their solubility is up for philosophical debate.
**** ANSWER:
supertasks
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       dd2534bf-3d6b-41db-822d-b9320f37e9cf
    :END:
In William Blake’s “The Tyger”, the author asks “What immortal hand or
eye could frame thy fearful [this]?”
**** ANSWER:
symmetry
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       e3015528-9315-4a3e-8ce6-68bbad29f742
    :END:
Desert in northern Africa that is the world’s largest hot desert.
**** ANSWER:
Sahara Desert
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       33ba1967-d5f2-4d2f-b8f4-845cfb06d777
    :END:
Group of bacteria that have long, coiled cell shapes and include the
causative agents of syphilis and Lyme disease.
**** ANSWER:
spirochetes
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       ad8dcb36-d220-4ced-a113-430e4bbcb8c7
    :END:
(TWO WORD ANSWER) – Nation whose 26-year civil war was ended in 2009
with the defeat of the rebel group known as the Tamil Tigers.
**** ANSWER:
Democratic Socialist Republic of Sri Lanka (shree LAHN-kuh) [or Shri
Lamka Prajatantrika Samajaya di Janarajaya]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       4876314c-53e5-41fd-b244-a8a407b40e7d
    :END:
This photographer and museum curator took the photograph The
Pond-Moonlight and organized The Family of Man exhibit at the Museum
of Modern Art.
**** ANSWER:
Edward Jean Steichen
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       3e241c6b-d29a-4ed5-a412-ce7749f51bbc
    :END:
This poet wrote the influential collection Harmonium, which contains
his poem “Thirteen Ways of Looking at a Black Bird.”
**** ANSWER:
Wallace Stevens
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       a729c801-df07-40fb-9ae4-b9b0a52f98dd
    :END:
(TWO WORD ANSWER) – In probability, this is the set of all possible
outcomes of a random variable. For a die, this set consists of the
numbers {1,2,3,4,5,6}.
**** ANSWER:
sample space [do not accept “sample set”] (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       f178ff75-a0ff-4b1f-bc0c-c8b9c4d7db5c
    :END:
Egyptian God of the Nile who has the head of a crocodile.
**** ANSWER:
Sobek [or Sebek or Sochet or Sobk or Sobki or Suchos]
*** Give                                                              :drill:
    SCHEDULED: <2018-11-26 Mon>
    :PROPERTIES:
    :ID:       f9734ff0-d34b-4a0b-a3e2-772c97e46314
    :DRILL_LAST_INTERVAL: 4.14
    :DRILL_REPEATS_SINCE_FAIL: 2
    :DRILL_TOTAL_REPEATS: 3
    :DRILL_FAILURE_COUNT: 2
    :DRILL_AVERAGE_QUALITY: 2.333
    :DRILL_EASE: 2.6
    :DRILL_LAST_QUALITY: 5
    :DRILL_LAST_REVIEWED: [2018-11-22 Thu 17:03]
    :END:
Artistic technique, the name of which comes from the Italian word for
“to fade out,” in which colors are blended so as to prevent sharp
outlines, thereby resulting in a painting that looks hazy.
**** ANSWER:
sfumato
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       ae478222-a128-45d4-99fa-291121c4d171
    :END:
American woman whose engagement to British king Edward VIII resulted
in the latter’s abdication of the throne in
 1936.
**** ANSWER:
Bessie Wallis Warfield Simpson or Bessie Wallis Warfield Spencer
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       e0caf47a-aef0-4f0a-b669-cc5cb4098451
    :END:
The final words of T.S. Eliot’s “The Wasteland” are in what language,
which was also used to write The Recognition of Sakuntala?
**** ANSWER:
Sanskrit
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       159326c6-09cc-4738-aba8-92012078f347
    :END:
Discoverer of many actinide elements while at the University of
California at Berkeley.
**** ANSWER:
Glenn Theodore Seaborg
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       de8e2ca0-5da7-4caf-b306-93c42de92741
    :END:
Place that inspired Felix Mendelssohn’s 3rd symphony and a fantasy by
Max Bruch.
**** ANSWER:
Scotland
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       1fb1cdbc-b87b-404d-82f0-cb73e96d29b2
    :END:
Surname of the family that succeeded the Visconti family as rulers of
Milan during the 15th and 16th century.
**** ANSWER:
Sforza family [accept Sforzas]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       eac18ab5-3275-45fa-b254-5c17ba4e5a95
    :END:
This quantum number, the fourth one, can take on values of 1/2 or -1/2
for fermions. It is sometimes called “intrinsic angular momentum.”
**** ANSWER:
spin quantum number
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       6770e27e-4eeb-41ea-92ce-11ca24720135
    :END:
This author of Lie Down in Darkness and Darkness Visible wrote a book
narrated by Thomas Gray that was the Pulitzer-Prize winning The
Confessions of Nat Turner.
**** ANSWER:
William Clark Styron Jr.
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       fd7b9940-4fa3-40c9-90eb-8c019c62d391
    :END:
Term used to describe the Biblical Gospels of Matthew, Mark and Luke
due to their similarity to one another.
**** ANSWER:
Synoptic Gospels
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       4b834902-399e-467b-b341-8ec44a5fba3f
    :END:
Beyond Freedom and Dignity is a book by this behaviorist psychologist,
who created a namesake box for conditioning test subjects.
**** ANSWER:
Burrhus Frederic Skinner

** Alphabet Round – Letter L
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       b74a0834-7a3f-4e9c-b68b-f0ee22b70f99
    :END:
(MULTI-WORD ANSWER) – This pirate and villain of Treasure Island owns
a parrot named Captain Flint that repeats many things that are said to
it. Jim Hawkins joins his crew in search of treasure.
**** ANSWER:
Long John Silver (MULTI-WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       cbd2658b-e348-4ccf-967a-68e544d15f3e
    :END:
In mathematical proof theory, this term refers to some statement that
must be proven so that it can be used as part of a proof. One named
for Euclid is used in the proof of the fundamental theorem of
arithmetic.
**** ANSWER:
lemmata
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       355e7f0c-b0fb-460e-b2c1-936a8906e2cc
    :END:
Trojan priest from Greek mythology who was killed by sea serpents
after warning against acceptance of the Trojan horse.
**** ANSWER:
Laocoon
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       8b0138e1-3ca7-45ed-8d76-9282743551ca
    :END:
(HYPHENATED ANSWER) – 1941 act by which the U.S. provided supplies to
the Allied nations during World War II.
**** ANSWER:
Lend-Lease Act (HYPHENATED ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       947e8be4-de17-439e-b4bf-7faea6da3148
    :END:
(MULTI-WORD ANSWER) – Joseph Kony is the current leader of this
organization in Uganda which employs child soldiers and espouses a
militaristic view of Christianity.
**** ANSWER:
Lord’s Resistance Army or Lord’s Resistance Movement (MULTI-WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       16223361-4460-4675-bb29-869c4ee44410
    :END:
(TWO WORD ANSWER) – Reactant that is completely consumed at the end
of a chemical reaction.
**** ANSWER:
limiting reagent or limiting reactant (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       39ac6980-ca90-45e6-bf31-9185668d0ca9
    :END:
(MULTI-WORD ANSWER) – The artist’s wife, Aline Charigot, plays with a
dog in the foreground of this 1881 painting which depicts a meal
taking place along the Seine River.
**** ANSWER:
Luncheon of the Boating Party [title must be exact] (MULTI-WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       fc4f4567-cc4d-4a05-af80-349bbed42c1b
    :END:
(TWO WORD ANSWER) – This Edward Bellamy novel follows Julian West,
who puts himself asleep in 1887 and wakes up in the year 2000 to
discover a utopia in the U.S.
**** ANSWER:
Looking Backward: 2000-1887 (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       d1439c2b-93d7-4b50-90fd-159cfb657549
    :END:
 1925 treaties which sought to establish peace and settled
international borders in Western Europe.
**** ANSWER:
Locarno Treaties or Locarno Pact
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       fa3d4850-d185-4856-b355-5964a1ffd080
    :END:
Method of viral replication in which the virus stays latent by
incorporating itself into the host genome.
**** ANSWER:
lysogenic cycle or lysogeny
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       ca804f3a-5581-4a84-a404-7528324b7559
    :END:
This psychosurgical technique, which was developed by Antonio Egas
Moniz, was a way of treating psychological disorders. It often
involves cutting away the prefrontal cortex of a brain.
**** ANSWER:
lobotomy [or leucotomy or leucotomy]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       d0d80c0d-84bd-4dae-a6f8-eea007f64d5e
    :END:
(MULTI-WORD ANSWER) – This film is the masterpiece of Alain Resnais
and focuses on “the man” who mysteriously reunites with a woman he met
at the title location.
**** ANSWER:
Last Year at Marienbad or Last Year in Marienbad [or L'Année dernière à Marienbad] (MULTI-WORD
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       e4fb9617-a05b-4d24-9f22-ab9007b6d800
    :END:
This author’s experiences in concentration camps led him to write a
short story collection structured around the Periodic Table. He also
wrote the memoir If This is a Man, a book about his survival in
Auschwitz.
**** ANSWER:
Primo Michele Levi
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       f78cf079-663b-4475-b5ba-06e21d1430ff
    :END:
Abolitionist newspaper co-founded by William Lloyd Garrison in 1831.
**** ANSWER:
The Liberator
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       537d146a-d557-4d6f-b795-786ca716a6eb
    :END:
Nickname given to Shostakovich’s 7th symphony, which was written
during the Second World War.
**** ANSWER:
Leningrad
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       98d1b8a4-d660-4c9c-b3c1-ba83698fcbc6
    :END:
Biblical character whose wife was turned into a pillar of salt during
the destruction of Sodom and Gomorrah.
**** ANSWER:
Lot
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       d3937616-9f57-4246-82ec-34864a02f83f
    :END:
(MULTI-WORD ANSWER) – This autobiographical play, which is set at the
Monte Cristo Cottage, was written by Eugene O’Neill and follows a
single day in the life of the Tyrone family.
**** ANSWER:
Long Day’s Journey into Night (MULTI-WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       f7643c2b-239a-4da6-aa72-e8b73901f2ef
    :END:
Mountain along the China-Nepal border which, at 27,940 feet above sea
level, is the 4th highest mountain in the world.
**** ANSWER:
Lhotse
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       e1c09d5f-0b34-4ccd-acb7-5558c05a3c61
    :END:
Primary military leader in the fight for Haitian independence; he died
in a French prison in 1803.
**** ANSWER:
Francois Dominique Toussaint Louverture
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       5823943b-db0f-43a4-b324-b94b1d1d0b11
    :END:
(TWO WORD ANSWER) – This largest particle collider in the world was
built by CERN and does actually produce micro-black holes.
**** ANSWER:
Large Hadron Collider (TWO WORD ANSWER)

** Alphabet Round – Letter R
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       0000e64d-22f1-45cd-a846-bfbfb50d9185
    :END:
Eid-al-Fitr ends this period of time in Islam. A Swiss scholar with
this last name wrote To be a European Muslim and The Quest for
Meaning.
**** ANSWER:
Ramadan [accept Tariq Ramadan]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       1287e353-fc91-4fa4-83c0-16573c9b3595
    :END:
Member of Bill Clinton’s Cabinet who was the second-longest tenured
U.S. Attorney General in history.
**** ANSWER:
Janet Wood Reno
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       438634ec-9a26-4228-aed6-6251019417c6
    :END:
This Victorian art critic and fantasy writer who wrote “The King of
the Golden River” authored a three-volume treatise on Italian art
called The Stones of Venice.
**** ANSWER:
John Ruskin
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       83b1c02e-9cba-4416-a672-a32f9d3cd54a
    :END:
 20th century American artist who illustrated the cover of the
Saturday Evening Post for over 40 years.
**** ANSWER:
Norman Perceval Rockwell
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       4603c9f5-0d86-4038-b6af-fa08ac27984f
    :END:
There are 57.3 degrees for every one of these dimensionless
units. There are 2pi of these for a full circle.
**** ANSWER:
radians
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       311cbad2-deef-421c-bd3c-69685b5c67a7
    :END:
Dynasty whose reign over Russia was ended in 1598, leading to the Time
of Troubles.
**** ANSWER:
Rurikid Dynasty
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       3a5ef86a-1fd3-42a0-bdd8-6c331cb7b336
    :END:
This French dramatist authored the sublime Spiritual Canticles;
another of his works is an adaptation of the Theseus story titled
Phedre.
**** ANSWER:
Jean-Baptiste Racine
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       797f9d2d-6dcf-4aaa-8d1c-276881698fb3
    :END:
Purification method that takes advantage of the desired substance
being insoluble at low temperatures but soluble at high temperatures.
**** ANSWER:
recrystallization
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       69ef9808-71a3-4722-ad01-f8dba2e48a48
    :END:
The Fischer equation outputs this kind of interest rate, which is
formally defined as the nominal interest rate minus the rate of
inflation.
**** ANSWER:
real interest rate
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       f78abc19-99a3-4be0-a57b-5f4a4da34d56
    :END:
This jazz saxophonist recorded an album with the song “Blue 7” and a
rendition of “You Don’t Know What Love Is”; that album is titled
Saxophone Colossus.
**** ANSWER:
Theodore Walter “Sonny” Rollins
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       57008438-61bd-4cbc-9ab3-e596534f55ab
    :END:
World leader who was assassinated in 1995 by Yigal Amir.
**** ANSWER:
Yitzhak Rabin
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       dda4f02b-41d5-483a-b50d-c30fdef82a2c
    :END:
This author’s time in Native American captivity was the subject of her
work The Sovereignty and Goodness of God.
**** ANSWER:
Mary White Rowlandson Talcott
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       bd0e24c8-d8c9-41fa-8b67-d8520e0c092d
    :END:
(TWO WORD OR HYPHENATED ANSWER) – This rule of thumb allows one to
ascertain the direction of a vector generated from the cross-product;
the namesake body part is rotated in accordance with the two input
vectors.
**** ANSWER:
right hand rule or right-hand rule (TWO WORD OR HYPHENATED ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       878b1488-1c17-4170-8df8-6d3c2fc75fd4
    :END:
(MULTI-WORD ANSWER) – City that is overlooked by the Corcovado
mountain, which is located within Tijuca Forest.
**** ANSWER:
Rio de Janeiro, Brazil (MULTI-WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       243c7f64-cb5d-418f-ac6e-dea84956b189
    :END:
This character, created by Nathaniel Hawthorne, raises his child so
that she is immune to poisonous plants, but she inadvertently poisons
other people.
**** ANSWER:
Giacomo Rappaccini
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       a6aab190-bac6-4dcd-ab3c-7ae120696ccb
    :END:
(TWO WORD ANSWER) – Nickname of the cavalry unit in which Theodore
Roosevelt served during the Spanish- American War.
**** ANSWER:
Rough Riders (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       52a54358-9eb9-47ed-b023-a48880e77f80
    :END:
In Japanese mythology, god of the seas who controlled the tides with
jewels.
**** ANSWER:
Ryujin or Ryojin [do not accept “Raijin”]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       cb1fd8f2-b0e8-4311-a4a1-c91cea96af36
    :END:
(MULTI-WORD ANSWER) – Source material for a “fantasy-overture” by
Tchaikovsky and a ballet by Prokofiev, the latter of which contains
the “Dance of the Knights.”
**** ANSWER:
Romeo and Juliet (MULTI-WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       355c8106-6c11-4a3c-8670-c6ff30889d04
    :END:
This philosopher authored Discourse on Inequality and wrote “man is
born free but is everywhere in chains” in his book The Social
Contract.
**** ANSWER:
Jean-Jacques Rousseau
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       8e01c1b9-03fa-4445-8b59-d261a57fd897
    :END:
Feature of mollusks that is used to consume food.
**** ANSWER:
radula or radulae
