* 2015 OAC Regionals – Round 9
** Round One
*** American Literature: Name the following related to literary movements.
**** Team A:                                                          :drill:
What literary movement had Jack Kerouac (kair-EW-ack), Lawrence
 Ferlinghetti (“fair”-LIN-get-ee), and Allen Ginsberg as members?
***** ANSWER:
the Beat Movement [accept the Beatniks]
**** Team B:                                                          :drill:
Lawrence Ferlinghetti founded the City Lights Bookstore in what city
 which was home to the Beat movement?  Mark Twain moved to this city
 in the 1860s.
***** ANSWER:
San Francisco, California
**** Tossup:                                                          :drill:
One member of this movement wrote “Whirl up, sea, whirl your pointed
 pines” in her poem “Oread.” In addition to its member H.D., another
 member of this movement wrote “The apparition of these faces in the
 crowd; petals on a wet black bough” in his extremely short poem “In a
 Station of the Metro.” This modernist movement is associated with an
 author who wrote “So much depends upon the red wheelbarrow glazed
 with rainwater beside the white chickens.” Name this early 20th
 century literary movement, whose members included William Carlos
 Williams.
***** ANSWER:
Imagism [accept word forms]
*** Mathematics: Pencil and paper ready. Name the following related to coordinate systems. You will have 30 seconds for each team question.
**** Team B:                                                          :drill:
What is the value, in polar coordinates, of the rectangular coordinate
 (4,4) (“four comma four”). Please express your “r” coordinate as a
 positive simplified root and your azimuthal (a-zih-MOO-thall)
 coordinate in degrees as a value that is positive and less than 360.
***** ANSWER:
r = 4 root 2 and ϕ = 45 [or r = 4 times square root of 2 and ϕ = 45;
accept in either order]
**** Team A:                                                          :drill:
What is the value, in polar coordinates, of the rectangular coordinate
 (-10,10) (“negative 10 comma 10”). Please express your “r” coordinate
 as a positive simplified root and your azimuthal [a-zih-MOO-thall]
 coordinate in degrees as a value that is positive and less than 360.
***** ANSWER:
r = 10 root 2 and ϕ = 135 [or r = 10 times square root of 2 and ϕ =
135; accept in either order]
**** Tossup:                                                          :drill:
Pencil and paper will not be necessary. The “harmonics” of this
 coordinate system are the solutions to Laplace’s (LUH-plass-iz)
 equation where the radial coordinates are given by Bessel (BESS-ull)
 functions. These coordinates are useful when longitudinal symmetry is
 present, such as a system where water flows down a pipe or an
 infinite line of charge. Rho (“row”), phi (fye), and z are the
 coordinates of this system, where z is the height distance.  Name
 this three-dimensional coordinate system which uses two distance
 coordinates and one angular coordinate, and which is an alternative
 to the spherical coordinate system.
***** ANSWER:
cylindrical coordinates [accept word forms]
*** World History: Name the following related to the Roman Empire.
**** Team A:                                                          :drill:
The start of Octavian’s rule in 27 BC triggered the start of this 200
 year period of relative calm within the Empire that is most commonly
 known by a two word Latin phrase.
***** ANSWER:
Pax Romana [or Roman Peace or Pax Augusta; prompt on “Pax” or “Peace”]
**** Team B:                                                          :drill:
Toleration of Christianity within the Roman Empire was promulgated by
 Constantine the Great in this AD 313 declaration.
***** ANSWER:
Edict of Milan [or Edictum Mediolanense]
**** Tossup:                                                          :drill:
In one incident this man expelled Dolabella from the Roman Forum when
 the latter occupied it in an attempt to pass debt relief
 legislation. Starting in 40 BC, this man led an unsuccessful war
 against the Parthians; in an earlier conflict, he prompted the
 suicide of Cassius after defeating his troops in the Battle of
 Philippi. This man served in the Second Triumvirate with Lepidus and
 Augustus, the latter of whom became the first Roman Empire after
 defeating this man at the 31 BC Battle of Actium. Name this Roman
 statesman who gave Julius Caesar’s elegy and later had an affair with
 an Egyptian queen.
***** ANSWER:
Mark Antony [or Marcus Antonius or Mark Anthony]
*** Fine Arts: Name these places of historical importance to classical music.
**** Team B:                                                          :drill:
This city’s philharmonic orchestra performs a popular annual New
 Year’s concert. It rose to prominence as a musical center during the
 Classical period, when composers such as Joseph Haydn and Wolfgang
 Amadeus Mozart worked here.
***** ANSWER:
Vienna [or Wien]
**** Team A:                                                          :drill:
Nikolai Rimsky-Korsakov was inspired by the music of this country to
 write a “Capriccio” off it. A composer from this country wrote
 “Ritual Fire Dance.”
***** ANSWER:
Kingdom of Spain [or Reino de Espana]
**** Tossup:                                                          :drill:
A composer from this country developed a method of teaching music that
 focuses on the use of folk music and singing as a basis. That
 composer used folk melodies of this country in his Dances of Galanta
 and Hary Janos (YA- nohsh) Suite. Another composer from this country
 developed a style of “night music” in several of his pieces and
 arranged 153 piano pieces from easy to hard in Mikrokosmos. This
 birthplace of Zoltan Kodaly is also home to a composer who used gypsy
 melodies in a set of rhapsodies named after this country. Name this
 country, the birthplace of Bela Bartok and Franz Liszt (“list”).
***** ANSWER:
Kingdom of Hungary [accept Republic of Hungary or Magyarorszag or
 Magyar ***Kostarsasag] Life Science: Answer the following questions
 about evolution.
**** Team A:                                                          :drill:
Darwin’s finches underwent this process, since they all derive from a
 single ancestor to occupy many niches within the ecosystem.
***** ANSWER:
adaptive radiation
**** Team B:                                                          :drill:
Named after a literary character, this theory states that organisms
 evolve to not only increase their survival but also to do so against
 competitors, prey, predators, hosts, or parasites.
***** ANSWER:
Red Queen hypothesis [accept any equivalent answer with Red Queen in
it]
**** Tossup:                                                          :drill:
The Court Jester hypothesis gives a method for this evolutionary
 theory to work, as it describes randomly- occurring abiotic changes
 in the environment that cause changes to occur. This idea emphasizes
 clado·genesis over ana·genesis. This theory accounts for speciation
 events as those that drive change. It built upon Ernst Mayr’s
 observation that there were gaps in the fossil record. This idea
 opposes gradualism, which states that evolution occurs slowly but
 constantly. Niles Eldredge and Stephen Jay Gould put forth what
 theory of evolution characterized by short bursts of change followed
 by long periods of stasis?
***** ANSWER:
punctuated equilibrium
** Round Two
*** English / World Literature: Answer the following about authors who wrote epic poems.
**** Team B:                                                          :drill:
The Shield of Heracles and Works and Days are epic poems by what Greek
 author, who described the origin of the gods in Theogony
 (THEE-odj-uh-nee)?
***** ANSWER:
Hesiod
**** Team A:                                                          :drill:
Apollonius Rhodius (APP-uh-loh-nee-us ROE-dee-us) wrote an epic poem
 about what object from Greek mythology that was used in a journey
 from Iolcus (EE-oll-cuss) to Colchis (KOLL-chiss) to acquire an item
 possessed by King Aeetes (“eye”-EE-teez).
***** ANSWER:
Argo
**** Tossup:                                                          :drill:
This man wrote an epic poem about “The Death and Judgment of the
 Eternal Man” that is named for Tharmas (TAR-muss), Luvah (LOO-vuh),
 Urizen (YUR-ee-zen), and Urthona (UR-thoe-nuh). This author of The
 Four Zoas wrote a shorter poem that begins “I was angry with my
 friend; I told my wrath, my wrath did not end.” That poem ends with
 the speaker seeing his foe outstretched beneath the title
 plant. Another poem, which appears in the same collection as the
 previous one, describes an “invisible worm, that flies in the night.”
 Name this author whose poems “A Poison Tree” and “The Sick Rose”
 appear in Songs of Innocence and Experience.
***** ANSWER:
William Blake
*** American Government / Economics: Name these Articles of the Constitution.
**** Team A:                                                          :drill:
The “Full Faith and Credit” clause is mentioned within this Article,
 which notes that the Federal government will guarantee every state a
 republican form of government and protect them against invasion.
***** ANSWER:
Article Four or 4th Article
**** Team B:                                                          :drill:
This Article specifies that the Constitution must be ratified by nine
 of the original thirteen states in order to become valid.
***** ANSWER:
Article Seven or 7th Article
**** Tossup:                                                          :drill:
The Constitution’s Recommendation Clause is within this Article, which
 notes how care shall be taken to ensure “that laws be faithfully
 executed.” The text of this Article, which addresses who can
 negotiate treaties and appoint ambassadors, was revised by both the
 25th and 12th Amendments. Command over the U.S. Armed Forces is
 granted within this Article, which also requires a regular State of
 the Union address. The requirements and powers of the U.S.  President
 are outlined in what Article of the Constitution which follows the
 Article describing the government’s legislative branch?
***** ANSWER:
Article Two or 2nd Article
*** Physical Science: Name these types of chemicals.
**** Team B:                                                          :drill:
This type of solution is made of two liquids that cannot be separated
 by distillation. An example of one is 95% ethanol in water.
***** ANSWER:
azeotropes
**** Team A:                                                          :drill:
Another liquid/liquid mixture is this type of colloid, examples of
which include mayonnaise and milk.
***** ANSWER:
emulsions
**** Tossup:                                                          :drill:
One type of this substance contains a carbon-nitrogen double bond,
 with the nitrogen bound to an R group. That type of this substance is
 named after (*) Schiff. Along with being a strong nucleophile,
 n-butyl lithium is one of the strongest examples of this type of
 chemical. In the inductive effect, the strength of these substances
 is increased by nearby electropositive groups, such as in
 guani·dinium. In the Henderson-Hasselbalch equation, the numerator of
 the log term is the conjugate type. They donate electron pairs
 according to Lewis theory, and most strong types lose a hydroxide in
 solution. Name these chemicals with a pH greater than 7.
***** ANSWER:
bases [or Lewis bases; or Bronsted-Lowry bases; or Arrhenius bases;
 accept ***imine until (*)] Geography: Name these Canadian province or
 territories.
**** Team A:                                                          :drill:
The Klondike Gold Rush occurred in this territory, which borders
Alaska and has its capital at Whitehorse.
***** ANSWER:
Yukon Territory
**** Team B:                                                          :drill:
The St. Lawrence River flows past the city of Montreal within this
 province, which has been the subject of an organized sovereignty
 movement since the late 1960s.
***** ANSWER:
Quebec
**** Tossup:                                                          :drill:
The Coast Salish (SAY-lish) people are Canadian aboriginals native to
 this province. This province borders the Queen Charlotte Strait and
 contains Kootenay and Yoho National Parks on its eastern
 border. Whistler is a popular winter sports resort town in this
 province, and its most populous city is situated at the mouth of the
 Fraser River. The capital of this province is on an island separated
 from the mainland by the Strait of Georgia; that island shares its
 name with its most populous city, which hosted the 2010 Winter
 Olympics. Name Canada’s westernmost province, which has its capital
 at Victoria and contains the city of Vancouver.
***** ANSWER:
British Columbia [prompt on “BC”]
*** American History: Give the following related to notable speeches.
**** Team B:                                                          :drill:
While speaking at the 1896 Democratic National Convention prior to
 gaining the Presidential nomination, this politician delivered the
 “Cross of Gold” speech to advocate against the gold standard.
***** ANSWER:
William Jennings Bryan
**** Team A:                                                          :drill:
After being elected as President on a ticket featuring John Nance
 Garner, this New Yorker noted in his first inaugural address that
 “the only thing we have to fear is…fear itself.”
***** ANSWER:
Franklin Delano Roosevelt [or FDR; prompt on “Roosevelt”]
**** Tossup:                                                          :drill:
One speech given prior to this event included a recitation of the
 Pericles quote “the whole earth is the sepulchre (SEP-uhl-ker) of
 illustrious men.” The services of secretaries John Nicolay and John
 Hay were utilized on the day of this event, which included a
 statement that “the world will little note, nor long remember, what
 we say here.” A two hour speech by Edward Everett preceded this
 event, which referenced a “new nation, conceived in liberty, and
 dedicated to the proposition that all men are created equal.”
 Beginning with the words “four score and seven years ago,” name this
 speech given in 1863 by Abraham Lincoln to honor those who died in a
 namesake Civil War battle in Pennsylvania.
***** ANSWER:
Gettysburg Address
** Alphabet Round – Letter R
*** Give                                                              :drill:
 Eid-al-Fitr ends this period of time in Islam. A Swiss scholar with
 this last name wrote To be a European Muslim and The Quest for
 Meaning.
**** ANSWER:
Ramadan [accept Tariq Ramadan]
*** Give                                                              :drill:
 Member of Bill Clinton’s Cabinet who was the second-longest tenured
 U.S. Attorney General in history.
**** ANSWER:
Janet Wood Reno
*** Give                                                              :drill:
 This Victorian art critic and fantasy writer who wrote “The King of
 the Golden River” authored a three-volume treatise on Italian art
 called The Stones of Venice.
**** ANSWER:
John Ruskin
*** Give                                                              :drill:
 20th century American artist who illustrated the cover of the
 Saturday Evening Post for over 40 years.
**** ANSWER:
Norman Perceval Rockwell
*** Give                                                              :drill:
 There are 57.3 degrees for every one of these dimensionless
 units. There are 2pi of these for a full circle.
**** ANSWER:
radians
*** Give                                                              :drill:
 Dynasty whose reign over Russia was ended in 1598, leading to the
 Time of Troubles.
**** ANSWER:
Rurikid Dynasty
*** Give                                                              :drill:
 This French dramatist authored the sublime Spiritual Canticles;
 another of his works is an adaptation of the Theseus story titled
 Phedre.
**** ANSWER:
Jean-Baptiste Racine
*** Give                                                              :drill:
 Purification method that takes advantage of the desired substance
 being insoluble at low temperatures but soluble at high temperatures.
**** ANSWER:
recrystallization
*** Give                                                              :drill:
 The Fischer equation outputs this kind of interest rate, which is
 formally defined as the nominal interest rate minus the rate of
 inflation.
**** ANSWER:
real interest rate
*** Give                                                              :drill:
 This jazz saxophonist recorded an album with the song “Blue 7” and a
 rendition of “You Don’t Know What Love Is”; that album is titled
 Saxophone Colossus.
**** ANSWER:
Theodore Walter “Sonny” Rollins
*** Give                                                              :drill:
 World leader who was assassinated in 1995 by Yigal Amir.
**** ANSWER:
Yitzhak Rabin
*** Give                                                              :drill:
 This author’s time in Native American captivity was the subject of
 her work The Sovereignty and Goodness of God.
**** ANSWER:
Mary White Rowlandson Talcott
*** Give                                                              :drill:
 (TWO WORD OR HYPHENATED ANSWER) – This rule of thumb allows one to
 ascertain the direction of a vector generated from the cross-product;
 the namesake body part is rotated in accordance with the two input
 vectors.
**** ANSWER:
right hand rule or right-hand rule (TWO WORD OR HYPHENATED ANSWER)
*** Give                                                              :drill:
 (MULTI-WORD ANSWER) – City that is overlooked by the Corcovado
 mountain, which is located within Tijuca Forest.
**** ANSWER:
Rio de Janeiro, Brazil (MULTI-WORD ANSWER)
*** Give                                                              :drill:
 This character, created by Nathaniel Hawthorne, raises his child so
 that she is immune to poisonous plants, but she inadvertently poisons
 other people.
**** ANSWER:
Giacomo Rappaccini
*** Give                                                              :drill:
 (TWO WORD ANSWER) – Nickname of the cavalry unit in which Theodore
 Roosevelt served during the Spanish- American War.
**** ANSWER:
Rough Riders (TWO WORD ANSWER)
*** Give                                                              :drill:
 In Japanese mythology, god of the seas who controlled the tides with
 jewels.
**** ANSWER:
Ryujin or Ryojin [do not accept “Raijin”]
*** Give                                                              :drill:
 (MULTI-WORD ANSWER) – Source material for a “fantasy-overture” by
 Tchaikovsky and a ballet by Prokofiev, the latter of which contains
 the “Dance of the Knights.”
**** ANSWER:
Romeo and Juliet (MULTI-WORD ANSWER)
*** Give                                                              :drill:
 This philosopher authored Discourse on Inequality and wrote “man is
 born free but is everywhere in chains” in his book The Social
 Contract.
**** ANSWER:
Jean-Jacques Rousseau
*** Give                                                              :drill:
 Feature of mollusks that is used to consume food.
**** ANSWER:
radula or radulae
** Lightning Round
*** Give                                                              :drill:
Allowing commoners to “pursue [their] own calling so that there may be
 no discontent” was one of five stated goals of the government during
 this (*) period. The Satsuma Rebellion occurred during this period,
 which saw the promulgation of the Charter Oath. This period included
 victory in a 1904 to 1905 war with Russia, and it succeeded the Edo
 Period, which was ruled by the Tokugawa Shogunate. Name this period,
 lasting from 1868 to 1912, which saw the modernization of Japan.
**** ANSWER:
Meiji (may-EE-jee) Period or Meiji Restoration [or Meiji Ishin; accept
 equivalents to “Restoration” such as “Revolution” or “Reform”; prompt
 on “Charter Oath” or “Oath in Five Articles” or “Gokajo no Goseimon”
 before (*)]
*** Give                                                              :drill:
It doesn’t measure activity, but this equation only works well for
 dilute solutions, and it does not work with poly·chromatic
 radiation. A quantity in this equation, symbolized epsilon, is
 sometimes called the extinction coefficient.  This law takes into
 account the path length of the cell and a constant called the molar
 absorptivity. This law is used after testing samples in a
 spectro·photometer. Name this law that relates the concentration of a
 solution to its absorbance.
**** ANSWER:
Beer's law [or Beer-Lambert law or Lambert-Beer law or
Beer-Lambert-Bouguer law]
*** Give                                                              :drill:
This man only started composing after a hand injury, possibly from a
 mechanical device, ended any chances of a piano career. Motifs such
 as A-S-C-H occur repeatedly in a piano piece about commedia dell’arte
 characters. His compositions for piano include a piece about dreaming
 entitled “Traumerei” (TROW-muh-rye), which is found in his collection
 of Scenes from Childhood. Name this German composer who was married
 to the pianist Clara Wieck (veek).
**** ANSWER:
Robert Schumann (SHOO-mahn)
*** Give                                                              :drill:
This nation’s capital city is home to Binondo (be-NAHN-doh), the
 world’s oldest Chinatown, which is located along the Pasig (PAH-sig)
 River. The island of Cebu (say-BOO) is controlled by this nation,
 which is to the northeast of the Sulu Sea. Davao (DAH-“vow”) is the
 most populous city on its second largest island, Mindanao
 (min-duh-NOW). This nation’s capital and Quezon (KAY-zahn) City are
 located on its island of Luzon. Name this Pacific island nation whose
 capital is Manila.
**** ANSWER:
Republic of the Philippines [or Republika ng Pilipinas]
*** Give                                                              :drill:
One of this author’s characters is the “mad poet of Sanaa”, a Yemenese
 author named Abdul Alhazred who supposedly wrote the Kitab (KEE-tawb)
 al-Azif. This author of “The Nameless City” wrote about William
 Dyer’s adventure to Antarctica in At the Mountains of Madness, which
 features spawn of the “Great Old One”, who resembles a gigantic human
 and an octopus. Name this American horror story writer who created
 the monster Cthulhu (kuh-THEW-loo).
**** ANSWER:
Howard Philips Lovecraft
*** Give                                                              :drill:
This author, who died during the Great Flu pandemic of 1918, defined
 the state as an entity that has a monopoly on the use of force in his
 lecture “Politics as a Vocation.” This author of the late work
 Economy and Society wrote another book which links the title
 Christian spirit with the advent of mercantilism. Name this German
 sociologist who authored The Protestant Ethic and the Spirit of
 Capitalism.
**** ANSWER:
Karl Emil Maximilian “Max” Weber (VAY-bur)
*** Give                                                              :drill:
One firsthand account of this battle came from the wife of Friedrich
 Riedesel (“RYE”-dih-sool), who commanded a German regiment
 here. General Simon Fraser was killed during this battle, which
 included fighting at Freeman’s Farm and Bemis Heights. Benedict
 Arnold’s left leg was seriously wounded at this battle, which saw the
 surrender of 6,000 troops commanded by John Burgoyne (bur-GOYN). Name
 this Revolutionary War battle, a 1777 victory for Horatio Gates in
 upstate New York.
**** ANSWER:
Battle of Saratoga [prompt on “Battle of Freeman’s Farm” or “Battle of
Bemis Heights” early]
*** Give                                                              :drill:
Huchra’s (HUK-rahz) lens is actually an instance of gravitational
 lensing that is distorting a galaxy named for this man, which is
 called his “cross.” His namesake “ring” is the general astronomical
 optical illusion that occurs through lensing.  He proposed a set of
 ten equations that describe the curvature of spacetime due to
 gravitation; those are his namesake field equations. Name this
 scientist who formulated the theory of general relativity.
**** ANSWER:
Albert Einstein
*** Give                                                              :drill:
 One of this author’s books features a blind monk named Jorge
 (HOR-hay) of Burgos, who eats a poisoned copy of Aristotle’s treatise
 on comedy. He wrote about an amnesiac bookseller named Yambo in The
 Mysterious Flame of Queen Loana. Adso of Melk and William of
 Baskerville investigate a series of murders at a monastery in another
 of this novelist’s books. Name this Italian author of Foucault’s
 Pendulum and The Name of the Rose.
**** ANSWER:
Umberto Eco
*** Give                                                              :drill:
 One religious group within this country believed that all matter was
 created by Satan, and they were later exterminated by Pope Innocent
 III (the third). In addition to the Albigensian heresy, this country
 was home to a religion that venerated a godhead on the Field of
 Mars. State religions from this country included the Cult of Reason
 and the Cult of the Supreme Being, which were instituted after its
 revolution. Name this nation home to a group of Protestants known as
 Huguenots.
**** ANSWER:
France [or French Republic or Republique francaise]
*** Give                                                              :drill:
Late in life, this man made the gelatin silver print Looking Northwest
 from the Shelton, which depicts the skyline of New York City. He made
 a series of prints depicting clouds called Equivalents, and he was
 inspired by Pablo Picasso’s cubism in depicting a group of passengers
 in the third-class section of a ship. Name this photographer who took
 a photo called The Steerage and was the husband of artist Georgia
 O’Keefe.
**** ANSWER:
Alfred Stieglitz
*** Give                                                              :drill:
A dwarf named John Bean attempted to assassinate this leader, who was
 possibly fathered by John Conroy. During the reign of this ruler, the
 Bedchamber Crisis occurred after the brief resignation of Prime
 Minister Lord Melbourne. This final British ruler of the House of
 Hanover wore primarily black following the death of her husband,
 Prince Albert. The title “Empress of India” was given to what queen
 who was the longest British ruler in history, reigning from 1837 to
 1901?
**** ANSWER:
Queen Victoria [or Alexandrina Victoria Hanover]
*** Give                                                              :drill:
This is the surname of the playwright who wrote Cloud Nine, as well as
 a play about Scilla (SKILL-luh) investigating Jake Todd’s death. In
 addition to naming Caryl, who penned Serious Money, it is the surname
 of a writer whose only novel is set in the country of Laurania
 (LOR-ayn-ee-uh). That author of Savrola won the Nobel Prize in
 Literature in 1953, but he is better known for writing a six-volume
 history of World War 2. Give the surname of the British politician
 who gave the “Their Finest Hour” speech.
**** ANSWER:
Churchill [accept Caryl Churchill or Winston Leonard
Spencer-Churchill]
*** Give                                                              :drill:
In prokaryotes (PRO-“carry”-“oats”), this process is initiated by
 sigma factors. Sequences such as the Pribnow box and TATA (tah-tah)
 box allow its main enzyme to bind in the promoter region. Following
 this process, the resulting product can be modified by the addition
 of a guanidine cap and a poly-A-tail. Name this process in which mRNA
 is created out of a DNA template.
**** ANSWER:
transcription
*** Give                                                              :drill:
People supporting this head of state sing the song “Bring Me My
 Machine Gun”. While facing criminal charges in 2006, he claimed that
 he took a shower to reduce the chances of acquiring HIV after having
 unprotected sex; that testimony was given during a trial in which
 this leader was charged with rape. Name this current head of state
 and leader of the African National Congress who succeeded Thabo Mbeki
 as president of South Africa.
**** ANSWER:
Jacob Gedleyihlekisa Zuma
*** Give                                                              :drill:
It’s not Heracles, but this figure fathered the goddess Macaria
 (mahk-ah-REE-uh). Minthe (MIHN-thee) was turned into a mint plant due
 to the pursuit of this god, who several times loaned away his cap of
 invisibility. He trapped Pirithous (“pie”-RIH-thoh-uss) in a chair
 for attempting to kidnap and marry his wife, Persephone
 (per-SEF-uh-nee), whom this god had previously kidnapped and married
 himself. Poseidon and Zeus are the brothers of what Greek god, who is
 served by the ferryman Charon (KAIR-un) and guard dog Cerberus
 (SER-buh-russ) as ruler of the underworld?
**** ANSWER:
Hades (HAY-deez) [or Plouton; do not accept or prompt on “Pluto”]
 17. Soldiers who took part in an assault of this specific location were the primary recipients of the Gillmore Medal; that
 battle against this location was launched from nearby Morris Island. The ship ~Star of the West~ was prevented from
 resupplying this location, which was later surrendered by Robert Anderson in response to an attack led by P.G.T.
*** Give                                                              :drill:
(BOH-reh-gard) in April 1861. The harbor of Charleston, South Carolina
 is the site of what fort that saw the first shots of the Civil War?
**** ANSWER:
Fort Sumter
*** Give                                                              :drill:
This post has been held by Billy Collins, Donald Hall, and Charles
 Simic, the last of whom wrote The World Doesn’t End. It has also been
 held by Stephen Spender and the author of the novel Deliverance,
 James Dickey, whose work “The Strength of Fields” was read at the
 inauguration of Jimmy Carter. Charles Wright is the current holder of
 what post which promotes the awareness of American poetry?
**** ANSWER:
United States Poet Laureate [accept Poet Laureate Consultant in Poetry
 to the Library of Congress; prompt on “Poet Laureate”]
*** Give                                                              :drill:
This physicist is the second namesake of an approximation that splits
 a molecule’s wavefunction into its electronic and nuclear
 components. This researcher, whose work is discussed in the Smyth
 Report, quoted the Bhagavad Gita’s (BAH- guh-vawd GEE-tuhz) line “I
 am become Death, the destroyer of worlds” after conducting an
 experiment known by the code name “Trinity.” Name this physicist
 known as the “father of the atomic bomb” for his role in the
 Manhattan project.
**** ANSWER:
Julius Robert Oppenheimer [accept the Born-Oppenheimer approximation]
*** Give                                                              :drill:
Worthington Whittredge was used as the model for this man in a
 painting that was destroyed during a World War 2 bombing of Bremen,
 Germany. Someone pulls back a red curtain to reveal this man holding
 a hatchet in the painting Parson Weems’ Fable. In one painting, he is
 shown standing in a boat next to an American flag while crossing an
 icy river. The Athenaeum (ath-uh-NAY-um) was an unfinished portrait
 by Gilbert Stuart of what man, who was the subject of an Emanuel
 Leutze (LOYT-zuh) painting in which he was Crossing the Delaware?
**** ANSWER:
George Washington
 
