* 2015 OAC Regionals – Round 4
** Round One
*** American Literature: Name these authors who wrote about teachers.
**** Team A:                                                          :drill:
What author of The Little Foxes wrote about two teachers named Karen
 Wright and Martha Dobie, who are accused of lesbianism, in her play
 The Children’s Hour?
***** ANSWER:
Lillian Florence “Lilly” Hellman
**** Team B:                                                          :drill:
What author of O Pioneers! wrote about a teacher named Godfrey
 St. Peter moving into a new home in The Professor’s House?
***** ANSWER:
Willa Sibert Cather
**** Tossup:                                                          :drill:
This author wrote about a Professor at Waindell College who is
 interested in lepidoptery (leh-pih-DOP-tuh-ree) in his novel Pnin
 (PEE-nin). During his time in America, this author was a professor at
 Cornell College, where he apparently taught an English class to
 Thomas Pynchon. One of his books ends with the execution of
 Cincinnatus (SINN- sih-natt-us) C., who is jailed for the crime of
 gnostic (NAW-stik) turpitude. This author of Invitation to a
 Beheading created the fictional author of Clare Quilty in a novel in
 which Dolores Haze is the subject of fantasies by Humbert
 Humbert. Name this Russo-American author who penned Lolita.
***** ANSWER:
Vladimir Vladimirovich Nabokov
*** Mathematics: Pencil and paper ready. Give the following related to polynomials. You will have 45 seconds for each team question.
**** Team B:                                                          :drill:
Find all three zeros of the following polynomial: 2x3
 + 10x2
 - 28x (“two x cubed, plus ten x squared, minus
 twenty-eight x”).
***** ANSWER:
x = 0, 2, -7 [accept in any order; do not prompt on partial answers]
**** Team A:                                                          :drill:
Find all three zeros of the following polynomial: 5x3
 - 15x2
 - 90x” (“five x cubed, plus fifteen x squared, minus
 ninety x”).
***** ANSWER:
x = 0, 6, -3 [accept in any order; do not prompt on partial answers]
**** Tossup:                                                          :drill:
Pencil and paper will not be necessary. The factorization of
 polynomials is often done via Berlekamp’s (BUR- luh-camps) algorithm,
 which factors polynomials over fields with this property. Automata
 (uh-TOM-uh-tuh) theory often studies nondeterministic and
 deterministic machines that have a set of states with this
 property. Formally, a set has this property if there doesn’t exist a
 subset of that set with the same cardinality. This property is not
 possessed by the set of all primes, but it is possessed by the set of
 all even primes. Name this property of being able to be completely
 enumerated, whose opposite is represented with the lemniscate
 (LEM-nis-kayt).
***** ANSWER:
finite [accept word forms such as finitude]
*** World History: Name these 20th century European leaders.
**** Team A:                                                          :drill:
This British leader noted that “I have nothing to offer but blood,
 toil, tears, and sweat” shortly after become Prime Minister in 1940
 as the successor to Neville Chamberlain.
***** ANSWER:
Winston Leonard Spencer Churchill
**** Team B:                                                          :drill:
Konstantin Chernenko was the predecessor of this final leader of the
 Soviet Union, who instituted the liberal policies of glasnost and
 perestroika prior to the nation’s dissolution in 1991.
***** ANSWER:
Mikhail Sergeyevich Gorbachev (GOR-buh-choff)
**** Tossup:                                                          :drill:
The “last days” of this leader’s tenure was the subject of a book by
 Hugh Trevor-Roper. The Hossbach Memorandum outlined the foreign
 policies of this ruler, who approved a mass deportation policy known
 as the Madagascar Plan. This ruler’s political opponents were
 assassinated during Operation Hummingbird, also known as the Night of
 Long Knives. Before rising to power, he was jailed for a failed coup
 known as the Beer Hall Putsch; while in jail, he authored his
 autobiography, Mein Kampf (“mine” kahmpf). The 1934 death of Paul von
 Hindenburg led to a consolidation of power for what genocidal
 (jen-uh-SIDE-uhl) leader of Nazi Germany during World War II?
***** ANSWER:
Adolf Hitler
*** Fine Arts: Name these art movements.
**** Team B:                                                          :drill:
An 1872 painting of a sunrise over the Le Havre (luh hahv) harbor
 provided inspiration for the name for this art movement whose
 practitioners included Mary Cassatt and Edgar Degas.
***** ANSWER:
Impressionism [accept Impressionist and other word forms; do not accept “Post-Impressionism” or other
 word forms]
**** Team A:                                                          :drill:
This early 20th century abstract art movement was co-founded by
 Georges Braque (zhorzh brahk) and a Spanish painter who had Blue and
 Rose Periods.
***** ANSWER:
Cubism [accept Cubists and other word forms]
**** Tossup:                                                          :drill:
One painting from this movement shows a buxom, red-headed woman
 smoking next to a red drink that sits on a counter; that work is At
 the Bar by Maurice de Vlaminck (vlah-MINK). The name of this movement
 was derived from a comment made by art critic Louis Vauxcelles
 (LOO-ee voh-“SELL”). One practitioner of this movement created a
 portrait of his wife titled The Green Stripe; another practitioner
 was Andre Derain (AHN-dray duh-“RAN”). The best known artist of this
 movement created a painting with a blue and green backdrop that shows
 five nude women holding hands in a circle while frolicking; that
 painting is titled The Dance. With a name that is French for “wild
 beasts,” name this early 20th century art movement practiced by Henri
 Matisse (muh-TEESE).
***** ANSWER:
Fauvism (FOH-vizm) or Fauvists (FOH-vists) or les Fauves (fohvz)
*** Life Science: Answer the following about the mitochondria.
**** Team A:                                                          :drill:
The inner folds of a mitochondrion’s inner membrane are given this
name.
***** ANSWER:
cristae
**** Team B:                                                          :drill:
This system, the last portion of cellular respiration, takes place in
 the mitochondria and creates a proton gradient to generate ATP.
***** ANSWER:
ETC or electron transport chain [prompt on partial answers]
**** Tossup:                                                          :drill:
A mitochondrial protein involved in this cellular process normally
 transfers electrons from coenzyme Q to complex IV (four) of the
 electron transport chain. During this process, phosphatidyl
 (FOSS-fa-tuh-dil) serine is expressed on the plasma membrane. This
 process can be induced by TNF or by the Fas ligand. Cisplatin can
 cause this process to occur since it suppresses DNA repair
 mechanisms. Cyto∙chrome c is released from the mitochondria during
 this process, after which it activates caspases. This process is
 intentional, unlike necrosis. Name this process of programmed cell
 death.
***** ANSWER:
apoptosis
** Round Two
*** English / World Literature: Name these British poets.
**** Team B:                                                          :drill:
What British poet, the author of “When I was One and Twenty” wrote
 about being able to “see the cherry hung with snow” in his poem
 “Loveliest of Trees”?
***** ANSWER:
Alfred Edward Housman
**** Team A:                                                          :drill:
What other British poet described “happy bells, across the snow” in
 his poem “Ring Out”, which is part of a sequence commemorating Arthur
 Hallam?
***** ANSWER:
Alfred, Lord Tennyson [or 1st Baron Tennyson]
**** Tossup:                                                          :drill:
This author wrote about seeing his cradled infant Hartley in a poem
 that begins by describing how the title phenomenon “performs its
 secret ministry unhelped by any wind.” He addressed his “pensive
 Sara” at the beginning of a poem about a musical instrument “placed
 length-ways in the clasping casement.” This author of “Frost at
 Midnight” and “The Aeolian (ee-OH-lee-in) Harp” had one of his works
 interrupted by the Person from Porlock. That work is set where “Alph,
 the sacred river, ran” and describes a “stately pleasure-dome” in
 Xanadu (ZAN-uh-dew). Name this British poet who wrote “Kubla Khan.”
***** ANSWER:
Samuel Taylor Coleridge
*** American Government / Economics: Name these Supreme Court cases.
**** Team A:                                                          :drill:
The ruling from this 1966 case established that during an
 interrogation, criminal suspects shall be advised of their rights to
 silence and an attorney via a namesake warning.
***** ANSWER:
Ernesto Arturo Miranda v. Arizona [accept Miranda warnings or Miranda rights]
**** Team B:                                                          :drill:
The doctrine of judicial review was established in this 1803 case
 which stemmed from the sitting Secretary of State’s refusal to
 deliver the commission of a man whose appointment was made by John
 Adams on the latter’s final day in office.
***** ANSWER:
William Marbury v. James Madison
**** Tossup:                                                          :drill:
In his final appearance before the Supreme Court, former Democratic
 presidential nominee John W. Davis argued on behalf of the defense
 for this case. The rulings made four years earlier in Sweatt
 v. Painter and McLaurin v. Oklahoma State Regents were referenced in
 the unanimous opinion for this case. In a subsequent case, the
 Supreme Court ruled that its decision must be implemented “with all
 deliberate speed.” Thurgood Marshall, while working for the NAACP,
 argued for the plaintiffs in this case, which overturned the
 “separate but equal” doctrine established in Plessy v. Ferguson. Name
 this 1954 case which ruled that segregation in schools was illegal.
***** ANSWER:
Oliver Brown, et al. v. Board of Education of Topeka, Kansas, et. al.
*** Physical Science: Answer the following about the periodic table.
**** Team B:                                                          :drill:
This quantity increases as one moves left and down on the
 table. Elements with more energy levels will have a larger value of
 this, which is decreased with increased nuclear charge.
***** ANSWER:
atomic radius [or Van der Waals radius; or covalent radius; or ionic radius; prompt on “radius”]
**** Team A:                                                          :drill:
This number increases as one moves right on the periodic table, and it
 is simply defined as the number of electrons an atom has on its
 outermost shell.
***** ANSWER:
valence electrons
**** Tossup:                                                          :drill:
Two elements in this group are responsible for M+2 peaks in mass
 spectroscopy and can be distinguished from each other based on
 whether those peaks are at a 3 to 1 or 1 to 1 ratio. The rarest
 element in this group is created through attacking bismuth-209 with
 alpha particles. Along with carbon, the lightest of this group of
 elements is found in Teflon.  Another element in this group can be
 used to test for starch. The two lightest elements of this group form
 diatomic gases at STP, while another is the only nonmetal to be
 liquid at room temperature. Name these group (*) 17 elements which
 include iodine, chlorine, and fluorine.
***** ANSWER:
halogens [accept group 17 before (*)]
*** Geography: Name these South American nations.
**** Team A:                                                          :drill:
The Rio Negro bisects this nation before flowing into a namesake
 river, that then empties into the Rio de la Plata estuary along this
 nation’s southern border.
***** ANSWER:
Oriental Republic of Uruguay (YOOR-uh-gway) [or Republica Oriental del Uruguay]
**** Team B:                                                          :drill:
The Gulf of Guayaquil (GWY-ah-keel) takes its name from the most
 populous city in this nation within the Andes Mountains that controls
 the Galapagos Islands.
***** ANSWER:
Republic of Ecuador [or Republica del Ecuador]
**** Tossup:                                                          :drill:
This nation borders a series of straits known as the Dragon’s
 Mouths. The southeast portion of this nation contains Canaima
 National Park, which is dominated by mesa-like formations known as
 tepuis (TAY-pweez). This nation controls the Tablazo Strait and a
 body of water that sees frequent lightning strikes at the mouth of
 the Catatumbo River.  Its longest river, the Orinoco, receives the
 water that flows through this nation’s Angel Falls, which is the
 highest waterfall in the world. The island nation of Trinidad and
 Tobago is just off the coast of what country which controls Lake
 Maracaibo and has its capital at Caracas (kah-RAH-kahs)?
***** ANSWER:
Bolivarian Republic of Venezuela [or Republica Bolivariana de Venezuela]
*** American History: Name the following things related to the Cold War.
**** Team B:                                                          :drill:
Operation Vittles was the codename for this eleven month event in
 which the U.S. and its allies flew in supplies to a certain city
 after all of its land accesses were blocked in 1948 by the Soviet
 Union.
***** ANSWER:
Berlin airlift
**** Team A:                                                          :drill:
Michael Collins and “Buzz” Aldrin were two of the three members of
 this NASA space mission that fulfilled the “Space Race” goal of being
 the first to land a man on the moon.
***** ANSWER:
Apollo 11 [prompt on “Apollo”]
**** Tossup:                                                          :drill:
It was revealed in 2002 that Vasili Arkhipov played a large role in
 preventing escalation during this event. Soviet spy Alexander
 Feklisov acted as a negotiator during this event, which prompted the
 creation of group known as ExComm.  This event occurred in response
 to actions taken during Operation Anadyr, and Rudolf Anderson was
 killed while flying a U-2 spy plane during this event. A hotline
 between Washington D.C. and Moscow was created in response to this
 event, which was ended when the U.S. agreed to remove Jupiter MRBM’s
 from Italy and Turkey. Name this 1962 event in which the U.S. set up
 a blockade after discovering Soviet nuclear weapons on a certain (*)
 Caribbean island.
***** ANSWER:
Cuban missile crisis [accept October crisis or The Missile Scare; accept Caribbean crisis before (*)]
** Alphabet Round – Letter N
*** Give                                                              :drill:
 In classical mechanics, this is the force that counteracts the
 gravitational force on an object. It also describes vectors that are
 perpendicular to a plane.
**** ANSWER:
normal force
*** Give                                                              :drill:
 A.D. 532 conflict during the reign of Byzantine Emperor Justinian
 that broke out amid a chariot race.
**** ANSWER:
Nika riots or Nika revolts
*** Give                                                              :drill:
 Residence on Earth is a major collection by what Chilean poet, who
 more notably wrote 20 Love Poems and a Song of Despair?
**** ANSWER:
Pablo Neruda
*** Give                                                              :drill:
 American body of water which surrounds Aquidneck Island.
**** ANSWER:
Narragansett Bay
*** Give                                                              :drill:
 (TWO WORD ANSWER) – In this situation, there is no way to alter an
 agent’s action such that changing that agent’s action would result in
 a better payoff.
**** ANSWER:
Nash equilibrium (TWO WORD ANSWER)
*** Give                                                              :drill:
 (TWO WORD ANSWER) – 1787 legislation which established the methods by
 which the lands from America’s first organized territory would be
 admitted into statehood.
**** ANSWER:
Northwest Ordinance of 1787 (TWO WORD ANSWER)
*** Give                                                              :drill:
 Set in the country of Costaguana, this novel features the character
 of Charles Gould, who owns a silver mine near the port of Sulaco.
**** ANSWER:
Nostromo, A Tale of the Seaboard
*** Give                                                              :drill:
 Type of organic molecule with a functional group consisting of a
 carbon triple bonded to a nitrogen; it is found in a namesake type of
 glove commonly used in laboratories.
**** ANSWER:
nitrile
*** Give                                                              :drill:
 (MULTI-WORD ANSWER) – 1912 painting which resembled “an explosion in
 a shingles factory” according to art critic Julian Street.
**** ANSWER:
Nude Descending a Staircase, No. 2 (MULTI-WORD ANSWER)
*** Give                                                              :drill:
 Norse god of the sea, whom Skadi married after only looking at his
 feet.
**** ANSWER:
Njord (nyord) [or Njordhr or Njordh or Njordr]
*** Give                                                              :drill:
 Along with the Hugo Award, this is one of the two major science
 fiction awards for novels in the U.S. It was won in 2014 by Ann
 Leckie for her novel Ancillary Justice.
**** ANSWER:
Nebula Award
*** Give                                                              :drill:
 German city which was used to host the trials for Nazis accused of
 war crimes committed during World War II.
**** ANSWER:
Nuremberg [or Nurnberg]
*** Give                                                              :drill:
 This term refers to tides that are at their minimum, unlike spring
 tides.
**** ANSWER:
neap tides
*** Give                                                              :drill:
 The Wahhabi group Boko Haram has kidnapped many schoolchildren in
 this country, such as the hundreds of schoolgirls in its town of
 Chibok.
**** ANSWER:
Federal Republic of Nigeria
*** Give                                                              :drill:
 (HYPHENATED ANSWER) – 1517 document that was authored by Martin
 Luther to protest various practices of the Catholic Church and posted
 to a church door in Wittenberg.
**** ANSWER:
Ninety-Five Theses on the Power and Efficacy of Indulgences (HYPHENATED ANSWER)
*** Give                                                              :drill:
 Composer of symphonies nicknamed "The Four Temperaments" and
 "Inextinguishable."
**** ANSWER:
Carl August Nielsen
*** Give                                                              :drill:
 1842 treaty which ended the First Opium War between the United
 Kingdom and China.
**** ANSWER:
Treaty of Nanking or Treaty of Nanjing
*** Give                                                              :drill:
 The most common type of white blood cell in the body, which are some
 of the first to react in the immune response.
**** ANSWER:
neutrophils or neutrophil granulocytes
*** Give                                                              :drill:
 This Japanese-American sculptor is responsible for creating many of
 the stage designs of the ballets of Martha Graham.
**** ANSWER:
Isamu Noguchi
*** Give                                                              :drill:
 This author wrote a novel about a greedy dentist titled McTeague as
 well a novel about a conflict between railroaders and farmers in the
 San Joaquin Valley in The Octopus.
**** ANSWER:
Benjamin Franklin “Frank” Norris Jr.
** Lightning Round
*** Give                                                              :drill:
One character in this film repeatedly states “I stick my neck out for
 nobody.” This film, which won an Academy Award for director Michael
 Curtiz, opens with Ugarte (ew-GAR-tee) claiming that he has letters
 of transit from German couriers.  At another point, a character
 becomes upset when the song “As Time Goes By” plays. It ends with
 Rick Blaine telling Ilsa Lund to board a plane with her husband
 Victor Lazlo. The line “Louis, I think this is the beginning of a
 beautiful friendship” ends what 1942 movie that stars Humphrey Bogart
 and is set in a Moroccan city?
**** ANSWER:
Casablanca
*** Give                                                              :drill:
One of these events was documented by the crew of the Big Stink. The
 Genbaku (ghen-BAH-koo) Dome memorializes one of these events,
 survivors of which are known as hibakusha (hee-bah-KOO-shah). The
 first of these events occurred during the Trinity Test, and the two
 most notable of these events were carried out by aircraft named
 Bockscar (BOX-car) and Enola Gay. Name these destructive events which
 were the objective of the Manhattan Project and most notably
 implemented at Nagasaki and Hiroshima, Japan in August 1945.
**** ANSWER:
detonation of a nuclear weapon or detonation of an atomic weapon [generously accept any equivalent
 answers that mention nuclear or atomic weapons/bombs/etc. being deployed/utilized/dropped/set off/etc. at White Sands
 Missile Range/Hiroshima/Nagasaki]
*** Give                                                              :drill:
In his own time, this author was famed for horror novels such as The
 Jewel of Seven Stars and The Lair of the White Worm. Inspired by
 Sheridan Le Fanu’s “Carmilla”, he wrote a novel in which the title
 character is stabbed to death by Quincey Morris. That novel’s title
 character infects Jonathan Harker’s fiancee (fee-AHN-say) Mina and is
 tracked by Abraham van Helsing. Name this British author who was
 inspired by the historical figure Vlad the Impaler to write Dracula.
**** ANSWER:
Abraham “Bram” Stoker
*** Give                                                              :drill:
Mordehai Milgrom’s MOND (mahnd) theory alters this force to explain
 the anomalous rotation curves of certain galaxies. The equivalence
 principle states that inertial mass and this type of mass is
 indistinguishable. The first measure of a constant that is used in
 calculating this force’s strength was given by Henry Cavendish, who
 measured the earth using a torsion balance. The weakest of the four
 fundamental forces is what force that gives rise to weight?
**** ANSWER:
gravity [or gravitation or gravitational force]
*** Give                                                              :drill:
One text about this religion features an emperor named Wonton, who
 dies after a hole is bored within him. A man who is unsure if he is a
 butterfly when he dreams about a butterfly is central to this
 religion’s philosophy. A text of this religion states “the name that
 can be named is not the eternal name.” This religion emphasizes a
 principle of non-action through action, which is termed wu wei (woo
 way). Name this religion, sometimes called “The (*) Way,” which was
 popular in ancient China.
**** ANSWER:
Taoism (DOW-izm or THOW-izm) [or Daoism; accept word forms; prompt on “The Way” before (*)]
*** Give                                                              :drill:
In his work On Generation and Corruption, this philosopher proposed
 the existence of aether (EE-thur) as the quintessence. His theory of
 the four elements divided them into the qualities of dryness,
 wetness, hotness, and coldness.  This man wrote about the nature of
 tragedy in his Poetics and outlined a theory of virtue in a work
 named for his son, the Nicomachean Ethics. Name this ancient Greek
 philosopher who tutored Alexander the Great.
**** ANSWER:
Aristotle
*** Give                                                              :drill:
This president was the target of an impeachment attempt led by
 Representative John Botts, and he signed into law legislation known
 as the Black Tariff. Two of his Cabinet members were killed in the
 USS Princeton explosion, and he died in 1862 after being elected to
 serve in the Confederate government. He signed a treaty to annex
 Texas, which officially occurred during the presidency of his
 successor, James Polk. Name this president dubbed “His Accidency”
 after taking over for the deceased William Henry Harrison in 1841.
**** ANSWER:
John Tyler
*** Give                                                              :drill:
This man’s last work, Letters from the Black Sea, contains a series of
 requests to Germanicus to rescind a certain punishment. His poem
 Fasti is structured around the Roman calendar. He spent the last
 years of his life in Tomis after he was exiled due to one of his own
 errors. One of his books, which contains the stories of Baucis
 (BAW-kiss) and Philemon (FILL-uh-mon) and Vertumnus and Pomona,
 centers on mythological translations. Name this Latin author of
 Metamorphoses.
**** ANSWER:
Publius Ovidius Naso
*** Give                                                              :drill:
Ten small scenes from the Passion of Christ adorn the edge of a mirror
 included in this painting. In this work a blooming cherry tree can be
 seen on the left through an open window, below which sits four
 oranges. A pair of clogs and a dog appear on the floor in front of
 the two figures in this painting, who are shown holding hands. Name
 this 1434 painting by Jan van Eyck (yahn van ike) which depicts the
 title Italian merchant and his presumed wife.
**** ANSWER:
The Arnolfini Marriage [accept The Arnolfini Wedding or any answer with Arnolfini and the suggestion of
 marriage; accept Arnolfini Portrait or Arnolfini Double Portrait]
*** Give                                                              :drill:
During the so-called Great Debate, Harlow Shapley argued that this
 structure was actually part of the Milky Way. This astronomical
 object, sometimes called (*) M31, has “arms” that Walter Baade
 (bah-duh) infamously called “beads on a string.” This is the largest
 member of the Local Cluster, and it appears blueshifted towards us,
 indicating that it will eventually collide with our galaxy. Name this
 spiral galaxy which is the closest to the Milky Way.
**** ANSWER:
Andromeda galaxy [accept M31 before (*)]
*** Give                                                              :drill:
Inspired by Friedrich Nietzsche (NEET-shuh), this social scientist
 argued that the creative spirit can be split into an Apollonian and
 Dionysian component in his book Toward a Psychology of Being. In that
 book, this man discusses self- validating peak-experiences. In his
 paper “A Theory of Human Motivation” he argued that physio·logical
 concerns fell below safety, love, esteem, and
 self-actualization. Name this psychologist who created a pyramid that
 illustrates a hierarchy of human needs.
**** ANSWER:
Abraham Harold Maslow
*** Give                                                              :drill:
One character in this book, Mr. Dolphus Raymond, drinks from a bottle
 in a paper bag and surprises the narrator when he reveals the drink
 to be Coca-Cola. This novel’s narrator, who is served by the maid
 Calpurnia, is attacked while dressed in a costume consisting of a
 piece of ham while returning back from a Halloween pageant. Its
 characters include Sheriff Tate and Boo Radley, who intervenes when
 Bob Ewell (“YOU”-wool) assaults Jem and Scout Finch. Name this lone
 novel by Harper Lee.
**** ANSWER:
To Kill a Mockingbird
*** Give                                                              :drill:
This figure names a bridge which was the site of a battle that incited
 the start of the Second Sino-Japanese War. This figure was captured
 at the Battle of Curzola and imprisoned with Rustichello
 (roo-stih-KEH-loh) da Pisa, who authored Il Milione (eel
 meel-YOH-nay), or The Million, an account of this man’s
 travels. Those travels occurred with his father and uncle, Niccolo
 and Maffeo, over a period of 24 years and included a visit to Kublai
 (KOO-bluh) Khan. Name this Italian merchant who visited China in the
 13th century.
**** ANSWER:
Marco Polo
*** Give                                                              :drill:
It’s not concentration, but the partition coefficient describes the
 difference in this property between two different phases. Henry’s law
 describes the strength of this property for gases, relating it to
 partial pressure. Its namesake constant is abbreviated Ksp. This
 property is decreased by the common ion effect and generally
 increases with temperature. Name this property of a substance to
 dissolve in a solvent.
**** ANSWER:
solubility [accept word forms; do not accept “solubilization”]
*** Give                                                              :drill:
This state’s Poverty Point National Monument protects 3,000 year old
 Native American mounds. Much of the supply of Tabasco sauce comes
 from this state’s Avery Island, and part of its western border lies
 along the Toledo Bend Reservoir and Sabine River. This state’s most
 populous city borders Lake Pontchartrain and is home to an annual
 Mardi Gras (graw) celebration centered around Bourbon Street in its
 French Quarter. Name this U.S. state that is home to New Orleans.
**** ANSWER:
Louisiana
*** Give                                                              :drill:
Gabriel Faure’s (“FOUR”-aze) piece of this genre ends with an “In
 Paradisum” seventh movement. Situated in each corner of the stage in
 another piece of this type are four brass bands; that piece was
 written by Hector Berlioz. Johannes Brahms wrote a “German” one of
 these pieces. Franz Sussmayer completed Wolfgang Mozart’s piece of
 this type. Name this type of composition which is a (*) mass for the
 dead.
**** ANSWER:
requiem mass [prompt on “mass” before (*)]
*** Give                                                              :drill:
After landing on the island of Mysia, this figure wounded and was
 later talked into healing King Telephus (TELL-uh- “fuss”). At the
 behest of this figure’s ghost, Polyxena (pah-lee-ZEE-nuh) was
 sacrificed at his tomb by his son, Neoptolemus
 (nee-ahp-TAH-luh-muss). Ajax the Great killed himself after being
 denied the armor belonging to this man, who was prompted by the death
 of Patroclus (PAH-troh-klus) to murder the Trojan prince Hector. Name
 this Greek fighter of the Trojan War who was killed by Paris with an
 arrow that hit his lone weak spot, his heel.
**** ANSWER:
Achilles (uh-“KILL”-eez)
*** Give                                                              :drill:
One poem by this writer describes Parson Thirdly, who states “Instead
 of preaching forty year, I wish I had stuck to pipes and beer.” This
 author of “Channel Firing” set another of his poems on the last day
 of the 19th century; that poem begins “I leant upon a coppice
 (COP-iss) gate.” This poet of “The Darkling Thrush” used the
 fictional region of Wessex as the setting of many of his novels,
 including one about Michael Henchard. Name this Victorian novelist
 who wrote The Mayor of Casterbridge.
**** ANSWER:
Thomas Hardy
*** Give                                                              :drill:
One commander with this surname had a longstanding feud with Jesse
 Elliott, stemming from a battle in which he took over command of the
 USS Niagara. Another commander with this surname established the 1854
 Convention of Kanagawa, which opened up U.S. trade with Japan. In
 2014, a U.S. governor with this surname, who has since retired, was
 indicted on two charges after trying to coerce a District Attorney to
 resign. Give this surname of U.S. Commodores Matthew and Oliver
 Hazard, as well as recently retired Texas governor Rick.
**** ANSWER:
Perry [accept Oliver Hazard Perry or Matthew Calbraith Perry or James Richard “Rick” Perry]
*** Give                                                              :drill:
Large amounts of CGG repeats on this structure cause a mutation in the
 FMR1 gene, leading to a disease that causes developmental
 disorders. When inactivated, this structure is called a Barr body. At
 least one extra one is found in Kline∙felter’s syndrome, while only
 one of these is present in Turner syndrome. Name this sex chromosome
 found in both males and females.
**** ANSWER:
X chromosome [prompt on “chromosome” before “chromosome”; prompt on
 “sex chromosome” before “sex”]
 
