* 2015 OAC Regionals – Round 1
** Round One
***  American Literature: Give the following related to characters with intellectual disabilities in literature.
    :PROPERTIES:
    :ID:       a16c502b-51b8-4a03-b0c6-b8fe0160f7b4
    :END:
****  Team A:                                                         :drill:
     :PROPERTIES:
     :ID:       b48580ce-127e-4f2b-8a82-650486080da3
     :END:
A mentally deficient character named Lennie Small is shot by his
   companion George Milton at the end of what John Steinbeck novel?
***** Answer
Of Mice and Men
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       a0d10c54-420b-49ba-8074-19ad75816ab4
     :END:
What Daniel Keyes novel and short story of the same name focuses on a
   namesake lab mouse and Charlie Gordon, both of whom are given a
   surgery to greatly increase intelligence which they eventually
   slowly lose?pp
***** Answer
“Flowers for Algernon”
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       bba79436-9342-42cb-8db8-f48d716088b8
     :END:
This author wrote a novel about a mentally depressed woman who
   befriends Doreen and has a relationship with Buddy Willard. That
   novel’s protagonist gets a summer internship at a magazine named
   Ladies’ Day, undergoes electroconvulsive therapy, and is named
   Esther Greenwood. In one of this author’s poems, the speaker states
   “There’s a stake in your fat black heart and the villagers never
   liked you”; that poem by her ends “you bastard, I’m through.” Name
   this author who wrote the novel The Bell Jar and the poem “Daddy.”
***** Answer
Sylvia Plath
***  Mathematics: Pencil and paper ready. Give the following related to trigonometric functions. You will have 20 seconds for each team question.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       b21a9763-ab3c-4a6a-a3f1-4fb791fceb4d
     :END:
Simplify, as much as possible, the following trigonometric expression:
   tan x / sec x (“tangent of x divided by secant of x”).
***** Answer
sine of x
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       1f06bd73-73a8-4bf4-a32e-df3124d51107
     :END:
Simplify, as much as possible, the following trigonometric expression:
   “sin x cot x” (“sin of x times cotangent of x”).
***** Answer
cosine of x
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       b25d64d1-4188-4186-8f90-dfa959f3512c
     :END:
Pencil and paper will not be necessary. The derivative of the
   hyperbolic version of this trigonometric function is (ex – e-x ) /
   2 (“e to the x minus e to the negative x, all divided by 2”). The
   Taylor series expansion of this function consists of terms in which
   a variable raised to an odd power is divided by the factorial of
   that power. The equation stating that a triangle side’s length
   divided by this function of its opposite angle is equal for all
   combinations of angles and sides is known as the “law of” this
   function. This trigonometric function is the reciprocal of the
   cosecant. Name this function that, for a given angle in a right
   triangle, is equal to “opposite over hypotenuse.”
***** Answer
sine of x
*** World History: Name these English or British monarchs.
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       5b140ca3-e26c-42c9-b93b-c58e3330bffe
     :END:
This youngest son of Eleanor of Aquitaine is best remembered for
   meeting at Runnymede to sign the Magna Carta in 1215.
***** Answer
King John of England [accept John Plantagenet or John Lackland] 
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       fea4f05f-473b-4623-bed5-d38f1f4cd783
     :END:
The Acts of Union, which combined England and Scotland into the
Kingdom of Great Britain, took effect in 1707 during the reign of this
woman, who was the last monarch of the House of Stuart.
***** Answer
Queen Anne of Great Britain
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       949ff05c-5b10-435b-800e-f8add9bf07b7
     :END:
This monarch was recognized as ruler by the Treaty of Abernethy two
years after waging a war known as the Harrying of the North. This
monarch’s greatest military victory occurred at Senlac Hill, and
shortly thereafter he established the Tower of London. A property
survey known as the Domesday (“doomsday”) Book was ordered by this
king, who came to power following a battle that was depicted in the
Bayeux (“BYE”-“you”) Tapestry and included the death of Harold
Godwinson. Name this first Norman king who won the 1066 Battle of
Hastings.
***** Answer
William the Conqueror [or William I of England or William the Bastard
 or William II of Normandy; prompt on "William"; do not accept or
 prompt on "William II"]
*** Fine Arts: Name these paintings which feature animals.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       fe757a03-db6a-4785-b3d8-7cac891baff3
     :END:
Ants are seen crawling on an orange timepiece in this Salvador Dali
 painting with three drooping clocks.
***** Answer
The Persistence of Memory [or La persistencia de la memoria]
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       8500954f-27df-4585-ae65-67794cfa3625
     :END:
A child puts her left foot on top of a sitting dog in this Diego
 Velazquez painting which depicts the artist creating a portrait of
 Spanish King Philip IV (the fourth).
***** Answer
Las Meninas (meh-NEE-nahss) [or The Maids of Honor]
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       8a5051ba-0050-4a74-8baa-11a81876a9db
     :END:
Shortly after its creation, Gerrit Lundens created a copy of this
 painting, the left side of which shows a boy holding onto a railing
 that has since been cut out of the original. After it was painted,
 the artist added a shield to an archway in the background which lists
 the names of eighteen people in this work. In this painting, a
 well-dressed man in red loads a musket while standing in front of a
 girl who holds a dead chicken. A yellow and blue flag is being waved
 behind the primary figures, Willem van Ruytenburch and Frans Banning
 (*) Cocq. Name this Rembrandt painting of a Dutch militia that is
 actually set during the day.
***** Answer
The Night Watch [or De Nachtwacht; before (*) accept The Shooting
  Company of Captain Frans Banning Cocq and Lieutenant Willem van
  Ruytenburch or The Militia of Captain Frans Banning Cocq and
  Lieutenant Willem van Ruytenburch or De compagnie van kapitein Frans
  Banning Cocq en luitenant Willem van Ruytenburgh maakt zich gereed
  om uit te marcheren; prompt thereafter] 
*** Life Science: Name these diseases caused by bacteria.  
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       6faa96e1-0272-4e8d-b19f-435724a523cb
     :END:
A scare in 2001 came in the form of mailed letters containing powder
 that would cause this disease. This often- fatal disease is caused by
 a bacterium of the genus Bacillus.  
***** Answer
anthrax 
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       62ff684a-c882-4d29-9edf-3c868990d1b0
     :END:
This disease, caused by species of the genus Borrelia, is carried by a
 tick and named after a town in Connecticut.  
***** Answer
Lyme disease
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       0df3767b-5d14-45db-86d0-3455c71dc4f2
     :END:
In 2013, a new form of this disease was discovered and named type
 H. In this disease, a toxin splits into its heavy and light chains,
 allowing it to degrade SNARES and prevent vesicle fusion, which stops
 neurotransmitter release. This disease is usually contracted when
 spores of the causative bacteria are ingested or directly enter the
 bloodstream, and it is classified into foodborne, infant, and wound
 types. This disease causes muscle weakness that can escalate to
 paralysis and respiratory failure. It is caused by a species of genus
 Clostridium. Name this disease that is caused by the same toxin used
 in botox (BOH-tox).  
***** Answer
botulism (BOTCH-uh-lizm)
** Round Two
*** English / World Literature: In this set of questions, you will name writers who wrote about alchemy.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       a484851e-0998-4ba3-9dc8-f23bb78217dd
     :END:

 What writer, the husband of Elizabeth Barrett, wrote about an
 alchemist who contemplates his achievements in Paracelsus
 (“PAIR”-uh-SELL-suss)?  
***** Answer
Robert Browning 
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       eb39d039-600e-4891-ae67-9c6b5ff0fba6
     :END:
What author, the wife of Percy, wrote about a scientist named Victor
 who creates a monster through assemblages and alchemy?  
***** Answer
Mary
  Wollstonecraft Shelley 
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       e4ab1f80-c0ee-4d33-a622-0cb0e0c8b567
     :END:
This writer wrote a story about a canon who tricks a clergyman into
 thinking mercury can be alchemized into quicksilver. Another story by
 this writer concerns a fox getting outwitted by a proud cock named
 Chauntecleer (CHAWN- tih-“clear”). In another story by this author,
 Nicholas farts into the face of Absolon (ab-SO-lawn), who then uses a
 red hot poker to singe Nicholas’ rear end. All of those stories by
 this author appear in a collection that opens with a General Prologue
 in which pilgrims stay at the Tabard Inn. Name this medieval English
 author who included “The Miller’s Tale” as one of his many Canterbury
 Tales.  
***** Answer
Geoffrey Chaucer
*** American Government / Economics: Name the following related to the U.S. Congress.
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       9028dd35-82da-45ce-90fc-e99389e88891
     :END:
The Constitution’s “Necessary and Proper” clause is used as
 justification to give Congress powers of this type, which are not
 expressly granted by the Constitution.  
***** Answer
implied powers 
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       c661a879-610e-403e-a820-27cae5faee41
     :END:
When combining the House of Representatives and Senate, this is
 the number of voting members of which Congress is comprised.  
***** Answer
five hundred thirty-five or 535 
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       f161e845-7d79-4fdd-bf63-b428e7176a66
     :END:
Proceedings related to this action are not subject to judicial review
 according to the ruling of a 1993 Supreme Court case involving Walter
 Nixon. William Belknap was the only Cabinet member to whom this
 action was applied, and in 15 of the 19 times in which this action
 took place, the target was a federal judge. It first occurred to a
 U.S. president after a violation of the Tenure of Office Act
 in 1868. A trial overseen by the Senate occurs after the House of
 Representatives takes this action, which can be initiated due to
 “treason, bribery, or other high crimes and misdemeanors.”  Name this
 action in which a federal official is removed from office.  
***** Answer
impeachment [accept word forms]
*** Physical Science: Name these chemists.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       efaac4af-2f25-40a5-979e-5f648de3c718
     :END:
This man, who invented dynamite, lends his name to a set of annual
 prizes given out in Oslo and Stockholm.  
***** Answer
Alfred Bernhard
  Nobel (no-BELL) [accept Nobel Prizes] 
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       ba72bae9-b839-43fb-aa0f-c45387aa85f3
     :END:
This Russian scientist’s most notable contribution was his creation of
 the periodic table.  
***** Answer
Dmitri Ivanovich Mendeleyev
  (MEN-duh-LAY-eff) 
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       b2ccfc96-775b-436d-931d-a69035135264
     :END:
This scientist determined that diamond was an allotrope of carbon, and
 he correctly noted that water was not a separate element. In his
 Methods of Chemical Nomenclature, he set up the first widely-used
 chemical naming system.  After experiments in which he heated solids
 inside closed containers and found no change in weight, he formulated
 the law of conservation of matter. This scientist discredited the
 phlogiston theory and named the element that was discovered out of
 it, oxygen. Identify this “father of modern chemistry”, a French
 scientist who was guillotined (GEE-uh-teend) during the French
 Revolution.  
***** Answer
Antoine-Laurent de Lavoisier (lah-VWAH-zee-ay OR luh-vwah-ZYAY)
*** Geography: Name these Asian rivers.
**** Team A: The Kara Su and Murat                                    :drill:
     :PROPERTIES:
     :ID:       909a5fde-a8f6-467c-b5a6-eaac43d56a17
     :END:
 Su co mbine to form this river which, along with the Tigris River,
flows through the region known as Mesopotamia.  
***** Answer
Euphrates
 (yoo-FRAY-teez) River [or al-Furat] 
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       525241d4-76db-484c-bbe7-de9de832687b
     :END:
The Bay of Bengal receives the delta of this chief river of
northeastern India that is holy to practitioners of Hinduism.  
***** Answer
Ganges (GAN-jeez) River [or Ganga River] 
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       4e6ead6f-bb88-4be2-8428-e917e832fd35
     :END:
The Fengdu Ghost City is a notable tourist attraction along this
river, into which the Poyang Lake empties. This river was the last
known home of the baiji (“bye”-JEE) dolphin, which was declared
functionally extinct in 2006. The world’s longest bridge, the
Danyang-Kunshan, runs along this river’s delta. This river flows
through the cities of Wuhan, where it meets the Han River, and
Chongqing (CHONG-ching) before emptying into the East China Sea. The
Three Gorges Dam was constructed on what Chinese river that flows past
the city of Shanghai and is the world’s third longest?  
***** Answer
Yangtze River [or Chang Jiang]
*** American History: Name the following related to slavery in the United States.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       5a3a45a2-e2b0-43c8-906f-087ff79163c9
     :END:
The Fugitive Slave Act was one of several provisions of this 19th
 century legislation which was drafted by Henry Clay and Stephen
 Douglas and resulted in California being admitted to the Union as a
 free state.  
***** Answer
Compromise of 1850 
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       c1576db2-7810-4bb6-adb9-441d558a9088
     :END:
Attorney Thomas Gray published the Confessions of this slave best
 remembered for leading a Virginia slave rebellion in August 1831.
***** Answer
Nathaniel Turner 
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       c788e5cd-abb1-40a7-8434-05e6f91d94fb
     :END:
Prior to this man’s most notable action, he used the alias Isaac Smith
 while lodging at the Robert Kennedy Farmhouse. This man fought
 against Henry Pate at the Battle of Black Jack; shortly thereafter,
 he attempted but failed to prevent an attack on a town that later
 became his nickname, Osawatomie. He led a group that killed five
 pro-slavery Kansans in the Pottawatomie Massacre. During his best
 known action, he was captured by troops under Robert E. Lee in
 response to his seizure of a Federal Armory in Virginia. Name this
 abolitionist who attempted to incite a slave revolt in 1859 by
 raiding the town of Harpers Ferry.  
***** Answer
John Brown
** Alphabet Round – Letter M
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       54feb1c6-2a0d-4f12-8cd2-54fbb91f41fc
    :END:
(NAME AND REGNAL NUMBER REQUIRED) – Final sultan of the Ottoman Empire.
**** Answer
Mehmed VI (the sixth) (NAME AND REGNAL NUMBER REQUIRED)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       2a5b0ea9-4582-4d38-987b-2bddca19e358
    :END:
This American poet authored the play J.B. and declared “a poem should not mean, but be” in Ars Poetica.
**** Answer
Archibald MacLeish
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       7bc30a7a-6311-494a-8c88-7c2006dc2a6b
    :END:
15th century Italian artist who painted such works as The Expulsion from the Garden of Eden and Tribute Money.
**** Answer
 One character in this play states “He hath borne me upon his back a thousand times” upon learning that a certain
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       f0e2431f-f43f-4604-ad2c-7fe4d8da0a54
    :END:
(ONE OR TWO WORD ANSWER) – Name for the simplest alcohol.
**** Answer
methanol or methyl alcohol (ONE OR TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       313d5e78-55e9-4960-a009-f61a403fc7e9
    :END:
This branch of philosophy, which analytic philosophy seeks to eliminate, is concerned with the nature of being. Aristotle wrote a treatise named for this branch of philosophy that introduces his idea of “potentiality” and “actuality.”
**** Answer
metaphysics
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       9b9adca9-af5c-4eeb-90fa-29aac0da7e9d
    :END:
Musical form in 3/4 time, often paired with a Trio in symphonies.
**** Answer
minuet
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       a1d7dc6e-c879-482f-be26-bd90b306a8ee
    :END:
(TWO WORD ANSWER) – 2nd century Roman Emperor who authored the Stoic work Meditations.
**** Answer
Marcus Aurelius Antoninus Augustus (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       78528dca-7e26-4c9d-b49a-393cefbc8c47
    :END:
In Percy Shelley’s poem “Ozymandias,” the speaker finds a statue with the lines “look on my works ye ____ and despair!” Fill in the blank.
**** Answer
mighty
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       3b9ab22a-69e3-4d8b-9d90-0e58b874cd40
    :END:
Most populous port city in the country of Kenya.
**** Answer
Mombasa
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       c827c609-0a48-4f61-a9c0-718faff3876b
    :END:
Giuseppe Verdi composed an opera named for this character, whose chorus includes witches and whose characters include Fleanzio and Banquo.
**** Answer
Macbeth or Macbetto
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       618f58ed-7879-4d3f-bad9-92f5015de3af
    :END:
(MULTI-WORD ANSWER) – The parallel axis theorem is a method of computing what quantity, which is often called the rotational analog of mass?
**** Answer
mass moment of inertia or polar moment of inertia (MULTI-WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       c3a99768-fa8d-412a-8b06-8e1a4d5d11cb
    :END:
American Revolutionary War battle at which Molly Pitcher supposedly supplied water to soldiers before taking part in the battle herself.
**** Answer
Battle of Monmouth
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       fcf0db95-8d77-4535-bb14-e7d575b63afa
    :END:
This American author wrote A View from the Bridge and After The Fall but is better known for writing a play about Joe Keller, who manufactures faulty airplane parts in All My Sons.
**** Answer
Arthur Asher Miller
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       f355e7e4-b400-4b0c-8f84-5aa34baa2e0d
    :END:
In Kabbalah, this term refers to a mystical strain of thought that places emphasis on meditating on the structure of heaven. It is named for the chariot of God in the Book of Ezekiel.
**** Answer
Merkaba [or Merkavah]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       9f38e821-cf0b-4688-bccd-9efaba1a4d0f
    :END:
(TWO WORD ANSWER) – These investment schemes are a collection of bonds and stocks that are brought together by a company; they are usually more diversified and thus less risky than investing in an individual stock.
**** Answer
mutual funds (TWO WORD ANSWER)
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       c70855de-2bc1-4756-bd71-fb0c84528b5c
    :END:
Term for a symbiotic relationship between a plant and fungus.
**** Answer
mycorrhizae
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       7b7868dc-83da-4d8e-8b62-4aa9dbe578ef
    :END:
16th century Flemish cartographer who developed a namesake map projection in which lines of latitude and longitude are perpendicular to each other.
**** Answer
Gerardus Mercator
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       4cdd5d57-9bc1-4907-a130-003da735e9a3
    :END:
Woman from Greek mythology who bore Adonis after tricking her own father into sleeping with her.
**** Answer
Myrrha
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       b3b6a8a9-6641-4ec5-9600-5ea81ce0ffac
    :END:
Hardness is often measured using this scale, which assigns a value of one to talc and two to gypsum.
**** Answer
Mohs scale
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       9920c6ef-84d1-47bf-8929-5a93ea92e696
    :END:
This author wrote about Gustave von Aschenbach, a writer who develops an attraction to Tadzio and eventually perishes, in his novella Death in Venice.
**** Answer
Paul Thomas Mann
** Lightning Round
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       d73422a1-ccf3-45bc-ba14-8fea28e1c360
    :END:
Prokaryotes (PRO-“carry”-“oats”) and eukaryotes (“YOU”-“carry”-“oats”)
    have differing forms of this organelle, as they are either 70 or
    80 Svedberg units in size. Amino·acyl-tRNAs occupy the A, P, and E
    sites in this organelle, which is also the destination for
    mRNA. These organelles are often found near the endo·plasmic
    reticulum (reh-TIK-“you”-lum).  Name this organelle that is the
    site of protein synthesis.  
**** Answer
ribosomes
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       6007c643-4555-4fbf-8d04-d0c277542c14
    :END:
In a tone poem by this composer, the “blues” sections represent
      homesickness. In the score to that piece, he included taxi
      horns. This composer’s most famous piece was written for the
      program “An Experiment in Modern Music” and opens with a
      glissando from the clarinet. Name this American composer who
      wrote An American in Paris and Rhapsody in Blue.  
**** Answer
George
       Gershwin [or Jacob Gershvin or Jacob Gershovitz]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       d6ec7026-1828-40d5-b901-9509c60b4e37
    :END:
One character in this play states “He hath borne me upon his back a
	thousand times” upon learning that a certain character was
	killed. In that scene, the title character calls a certain man
	that he knew well “a fellow of infinite jest.” This drama
	features a play called The Murder of Gonzago, which its
	protagonist uses to “uncover the conscience of the king.”
	Horatio and Fortinbras are characters in what Shakespeare play
	about a Prince of Denmark?  
**** Answer
The Tragedy of Hamlet,
	 Prince of Denmark
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       ad09dbdc-bd69-45aa-825f-e0b4838c87fb
    :END:
This leader purportedly castrated and married a teenage boy named
	  Sporus because he looked like this man’s deceased wife,
	  Poppaea (pah-PEE-uh). The Pisonian conspiracy sought to
	  overthrow this leader, who ruled during Boudicca’s
	  (BOO-dik-kuhz) revolt in Britain. This leader’s mother,
	  Agrippina the Younger, orchestrated the death of his
	  predecessor, Claudius, in 54 AD. Name this Roman Emperor who
	  ruled until 68 AD and did not actually play a fiddle during
	  the Great Fire of Rome.  
**** Answer
Nero Claudius Caesar
	   Augustus Drusus Germanicus
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       0175efbd-5d9f-4f5f-8fa8-b0d5e61faa36
    :END:
This model was superseded by Hantaro Nagaoka’s now incorrect Saturnian
	    ring model. It predicts a sea of positive charge with
	    negatively charge corpuscles occupying the intermediate
	    space. The Geiger-Marsden experiments disproved this model
	    through the use of gold foil and alpha particles, which
	    led to the discovery of the nucleus of the atom. Name this
	    model of the atom that was proposed by J.J. Thomson and
	    named for an English dessert.  
**** Answer
plum pudding model
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       d5c7a662-34fa-4a28-98e7-c99ff6952718
    :END:
Various Greek myths identify either Zeus or this figure burying
	      Enceladus (en-SEL-ah-dus) under Sicily following the
	      Revolt of the Giants. Erichthonius
	      (“air”-ik-THOH-nee-us) was born after an attempt by
	      Hephaestus (huh-FESS-tuhss) to rape this figure, who was
	      challenged to a weaving contest by Arachne. Tiresias was
	      blinded after seeing this goddess bathing, and this
	      goddess was born fully grown from the head of
	      Zeus. Minerva was the Roman equivalent of what Greek
	      goddess of wisdom who had the epithet Pallas?  
**** Answer
Pallas Athena [or Pallas Athene; prompt on “Pallas”
	       before mentioned]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       6ff76d72-a759-48fd-b3ea-46026717888c
    :END:
This poet’s nonfiction works include one that suggests writers should
		not use Classical Latin. In addition to “De Vulgari
		Eloquentia” (DAY wol-GAR-ee ELL-oh-quen-tee-uh), he
		wrote a poem whose speaker ascends the seven terraces
		of a mountain to find the Garden of Eden on top. One
		of his poems includes the line “Abandon all hope ye
		who enter here” and features its author meeting the
		shade of Vergil as he travels through the nine levels
		of the Inferno. Name this Italian poet who authored
		The Divine Comedy.  
**** Answer
Dante [or Durante degli
		 Alighieri]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       82eaf2c3-2910-49bf-bac9-9a5898160e77
    :END:
This city’s Isle of the Swans contains a replica of the Statue of
		  Liberty which sits next to the Grenelle (gruh-NELL)
		  Bridge. One museum in this city has wings named
		  “Sully” and “Denon” (deh-NAHN). The Sacre-Coeur
		  (SUH-kreh KUHR) Basilica is within this city’s
		  Montmartre [mon-MAR-truh] district, and its Ile de
		  la Cite (eel day lah SEE-tay) contains the
		  Notre-Dame [NOH-truh dahm] Cathedral. The
		  Champs-Elysees (shawm zay-lee-zay) runs southeast
		  from the Arc de Triomphe (ark duh tree-YOHMF) in
		  what French city that contains the Eiffel Tower?
**** Answer
Paris, France
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       c6d6cba0-88bc-4d56-a74e-db5f23451ef0
    :END:
Mississippi Governor Fielding Wright was a vice presidential candidate
		    in this election. The winner of this election
		    later survived an assassination attempt carried
		    out at the Blair House by two Puerto Rican
		    nationalists. The Dixiecrat Party nominated Strom
		    Thurmond for the presidency in this election, the
		    results of which were erroneously announced by the
		    Chicago Daily Tribune. “Give ‘em hell Harry” was
		    the campaign slogan of the winner in what election
		    in which Dewey did not defeat Truman?  
**** Answer
Presidential Election of 1948
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       b06f718a-25b0-4a92-8f2a-f91af8041e4f
    :END:
In one opera by this composer, a chorus of janissaries praise their
		      mighty pasha. In that opera, Belmonte (bell-MON-
		      tay) looks for his beloved Konstanze, who has
		      been forcibly sold into Selim’s harem. In
		      another opera by this composer, the extremely
		      tough aria “Hell’s Vengeance Boils in My Heart”
		      is sung by the Queen of the Night. In that
		      opera, Tamino and Pamina are protected by a
		      musical instrument. Name this composer of
		      Abduction from the Seraglio (sur-AH-lee-oh) and
		      The Magic Flute.  
**** Answer
Wolfgang Amadeus
		       Mozart [or Johannes Chrysostomus Wolfgangus
		       Theophilus Mozart]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       96db9fd9-8458-4c54-9b20-ee0b27670fb2
    :END:
The Winkler test is used to detect the amount of this element. In a
			Hofmann voltameter (vol-TAH-muh-ter), a gas of
			this element is produced at the anode. An atom
			of this element is double bonded to a carbon
			in a carbonyl, and in an ether it is single
			bonded to two carbons. It is the most common
			element in the Earth’s crust, and three atoms
			of this element comprise ozone. Eight is the
			atomic number of what element, which we
			breathe?  
**** Answer
oxygen
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       b71a9cda-f270-499c-802d-4ed39148a349
    :END:
Two answers required. One text identifies Azura and Awan as daughters
			  of this duo. In another text, the members of
			  this duo are told “cursed be the ground
			  because of you” and “in pain shall you bring
			  forth children.” One son of this duo asks
			  the question “am I my brother’s keeper”
			  after killing his brother. Eating fruit from
			  the Tree of Knowledge resulted in this duo
			  being banished from the Garden of Eden. Name
			  these Biblical parents of Cain and Abel who
			  were the first humans created by God.
**** Answer
Adam and Eve [accept in either
			   order; do not accept or prompt on partial
			   answers]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       4a70ec24-7741-4c54-a05a-5dd1d5453a11
    :END:
This author wrote about Georg Znaeym (GAY-org NAY-uhm) and Ulrich von
			    Gradwitz, two men who come to a truce only
			    to realize that they are about to be
			    devoured by wolves, in his short story
			    “The Interlopers.” One of his short
			    stories ends with the line “Romance at
			    short notice was her specialty.” Another
			    of his stories focuses on Conradin, a
			    menacing boy who cares for the title
			    polecat-ferret. Name this British master
			    of the short story, whose works include
			    “The Open Window” and “Sredni Vashtar.”
**** Answer
Saki [or Hector Hugh Munro]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       ac1ca32d-a4b7-4892-8267-55c2e64db8d7
    :END:
In the aftermath of this nation’s 1891 civil war, two members of the
			      U.S. Navy were killed here during the
			      USS Baltimore crisis. This nation
			      acquired the province of Arica following
			      its victory in the War of the
			      Pacific. Bernardo O’Higgins helped
			      secure independence for this nation,
			      which was ruled by Salvador Allende
			      (ah-YEN-day) until he was replaced
			      during a 1973 coup by Augusto Pinochet
			      (ow-“GOOSE”-toh PEE-noh-shay). Name this
			      South American nation ruled from the
			      city of Santiago.  
**** Answer
Republic of
			       Chile (CHEE-lay) [or Republica de Chile]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       1c30ad67-6b37-4436-ad95-4f1af64e0e44
    :END:
One controversy about these things was whether the agent found in them
				called thiomersal (“thigh”-OM-er-sahl)
				was hazardous. One opponent of these
				things claimed that chelation therapy
				cured her son of a condition induced
				by one of these tools; that opponent
				was Jenny McCarthy. Recent comments
				from Rand Paul revealed that he wanted
				to give parents the right to determine
				whether to use these things on their
				children. Name these preventative
				agents that some believe are
				responsible for autism.  
**** Answer
vaccines [accept any specific types of
				 vaccines mentioned]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       a1c1aa18-5af1-4766-a53d-d1412abc397c
    :END:
One painting by this artist is a portrait of Cecilia Gallerani holding
				  a weasel. Another of his paintings
				  was utilized in the Marcel Duchamp
				  (mahr-SELL doo-SHAHMP) readymade
				  L.H.O.O.Q. This artist of Lady with
				  an Ermine created a portrait of the
				  wife of Francesco del Giocondo, as
				  well as a fresco within a Milan,
				  Italy church that shows Jesus and
				  his twelve apostles gathered around
				  a table. Name this Florentine
				  Renaissance artist of The Last
				  Supper and Mona Lisa.  
**** Answer
Leonardo di ser Piero da Vinci
				   [accept either underlined name]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       f94ee5dc-6c3f-415f-ac92-7f983fd2d1c6
    :END:
The presence of the body Pan orbiting this body led to the formation
				    of the Encke (ENK-ay) Gap. A probe
				    that was sent to investigate this
				    planet is known as the
				    Cassini-Huygens (kuh-SEE-nee
				    HOY-gens) spacecraft. Patches of
				    phosphine (foz-FEEN) characterize
				    this planet’s periodic storms,
				    known as the Great White Spot. Its
				    largest moon is the only satellite
				    known to have an atmosphere. Mimas
				    and Titan are moons of what large,
				    gaseous planet noted for its giant
				    rings?  
**** Answer
Saturn
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       a8e858ca-bf7d-4d69-9800-192b9ad7b2e6
    :END:
Reporter Mark Kellogg was killed while covering this battle. The
				      Battle of the Rosebud, which
				      occurred eight days prior,
				      prevented George Crook’s
				      involvement in this battle. The
				      losers in this battle employed
				      three battalions – Frederick
				      Benteen and Marcus Reno led two
				      of them, and a horse named
				      Comanche was the sole survivor
				      of the third. Lakota leaders
				      Crazy Horse and Sitting Bull
				      helped win what 1876 battle
				      against the U.S. 7th Cavalry
				      that included “Custer’s Last
				      Stand”?  
**** Answer
Battle of the
				       Little Bighorn River [or Battle
				       of Greasy Grass Creek; prompt on
				       “Custer’s Last Stand” before
				       mentioned]      
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       b053b5f3-a837-4168-9e82-85f4cb0151a0
    :END:
According to Sigmund Freud’s structural model, these entities are used
					by the ego to diffuse the
					tension spread via the
					super-ego. Anna Freud wrote a
					book titled for these
					psychological constructs,
					which she enumerated as
					isolation, projection,
					introjection, regression, and
					rationalization. Name these
					unconscious mental tendencies
					that distort reality to
					protect oneself from painful
					emotions.  
**** Answer
defense
					 mechanisms [accept mechanisms
					 of defense]
*** Give                                                              :drill:
    :PROPERTIES:
    :ID:       6ce0ac07-2945-4f4f-9c94-1fbd03dff72d
    :END:
One character in this novel signs letters as “Irving Washington” and
					  “Washington Irving.” Its
					  main character sees acts of
					  brutal madness while in Rome
					  and escapes to Sweden after
					  being affected by Snowden’s
					  death. Its other characters
					  include Doc Daneeka, who is
					  mistakenly declared dead
					  after he disappears from the
					  island of Pianosa
					  (PEE-uh-no-suh).  Milo
					  Minderbender and John
					  Yossarian are characters in
					  what satiric, anti-war novel
					  by Joseph Heller?  
**** Answer
Catch-22     
