* 2015 OAC Regionals – Round 5
** Round One
*** American Literature: Name these American authors who wrote about butterflies.
**** Team A:                                                          :drill:
What author of “Dr. Heidegger’s Experiment” wrote about Owen Warland’s
 creation of a mechanical butterfly in “The Artist of the Beautiful”?
***** ANSWER:
Nathaniel Hawthorne [accept Nathaniel Hathorne]
**** Team B:                                                          :drill:
The young Jay Follett appreciates the nature of death as he sees a
 butterfly in what author’s novella A Death in the Family?
***** ANSWER:
James Rufus Agee
**** Tossup:                                                          :drill:
This author wrote about a character who sees a raindrop fall on a
 butterfly in “Two Minute Seduction.” This author wrote about the
 fashion model Jadine and her love interest Son, who begin a
 relationship, in her novel Tar Baby.  She wrote about Pecola
 Breedlove in a book named for a body part that Pecola
 desires. Margaret Garner inspired another of this author’s novels,
 which opens “124 was spiteful.” In that book by this author, Sethe
 (seth-uh) murders her own daughter so that she does not go back into
 slavery. Name this African-American female author who wrote The
 Bluest Eye and Beloved.
***** ANSWER:
Toni Morrison [or Chloe Ardelia Wofford]
*** Mathematics: Answer some questions about prime numbers.
**** Team B:                                                          :drill:
What French scientist gives his name to numbers of the form 2^2^n + 1
 (“two to the two to the n, plus one”), which he wrongly conjectured
 were all primes? Prime numbers also figure into his namesake “little
 theorem.”
***** ANSWER:
Pierre de Fermat [accept Fermat number]
**** Team A:                                                          :drill:
What French mathematician gives his name to primes of the form “2^n –
1” (“two to the n, minus one”)?
***** ANSWER:
Marin Mersenne [or Marin Mersennus; accept Mersenne primes]
**** Tossup:                                                          :drill:
A one-to-one correspondence exists between the Mersenne (MER-senn)
 primes and these numbers, all of which are hexagonal and triangular
 numbers. The Euclid-Euler (“YOU”-clid OY-lur) theorem governs the
 existence of these numbers, which are not deficient and not abundant,
 and which have aliquot (AL-ih-kwott) sums equal to themselves. All
 known examples of these numbers are even; it has not been established
 whether odd ones exist. Eight thousand one hundred twenty-eight, four
 hundred ninety-six, and twenty-eight are examples of these numbers,
 whose smallest member is six. Name these numbers that equal the sum
 of all of their proper divisors.
***** ANSWER:
perfect numbers
*** World History: Name these former African leaders.
**** Team A:                                                          :drill:
This 14th century ruler of the Mali Empire devalued gold in North
 Africa and the Middle East for around a decade because of the large
 amounts of gold that he distributed during a 1324 hajj.
***** ANSWER:
Mansa Musa [accept Musa I (the first)]
**** Team B:                                                          :drill:
Assassinated and succeeded by his brother Dingane (din-GAH-nay) in
 1828, this man is the founder and best known leader of the Zulu
 Kingdom.
***** ANSWER:
Shaka Zulu [or Chaka Zulu or Shaka kaSenzangakhona]
**** Tossup:                                                          :drill:
This leader bestowed the title of “First Arab Citizen” upon Shukri
 al-Quwatli after their two polities were merged. This man was the
 target of a planned coup by his former chief military commander,
 Abdel Hakim Amer. He was one of the leaders of the July 23rd
 Revolution along with Muhammad Naguib (nah-GEEB), whom he succeeded
 as ruler four years later. This founder and lone leader of the United
 Arab Republic briefly resigned after being defeated by Israel in the
 Six-Day War. He oversaw construction of the Aswan High Dam and
 sparked the Suez Crisis by nationalizing the Suez Canal after coming
 to power in 1956. Name this Egyptian President who ruled until 1970,
 when he was succeeded by Anwar Sadat.
***** ANSWER:
Gamal Abdel Nasser (NAH-sir)
*** Fine Arts: Name these composers, all of whom wrote tone poems.
**** Team B:                                                          :drill:
This composer drew on mythology of his home country for pieces such as
 “The Swan of Tuonela” and also composed the nationalistic piece
 Finlandia.
***** ANSWER:
Jean Sibelius (zhahn sih-BAY-lee-us) [or Johan Julius Christian Sibelius]
**** Team A:                                                          :drill:
“The Moldau” (“MOLE”-dow) is one of six tone poems in this composer’s
 cycle Ma Vlast, which depicts his homeland of Bohemia in the
 modern-day Czech (“CHECK”) Republic.
***** ANSWER:
Bedrich Smetana (BED-rik SMEH-tah-nah)
**** Tossup:                                                          :drill:
In a tone poem by this composer, the end of night is signaled by an E
 flat, B flat, B flat, E flat, G, from the oboe.  In that piece, this
 composer has the solo violinist tune the E string down to an E flat
 to create a triton with the A string. In another piece, he depicts
 two pianists practicing their scales. This composer used the
 xylophone to depict dancing skeletons in a tone poem in which Death
 summons the dead, as well as in the “Fossils” movement of a different
 piece.  This composer used a cello with piano accompaniment to depict
 a swan. Name the French composer of Danse Macabre (dawnss
 muh-KAHB-ruh) and Carnival of the Animals.
***** ANSWER:
Charles-Camille Saint-Saens (caa-meel san-sahnss)
*** Life Science: Name these parts of the human body.
**** Team A:                                                          :drill:
This gland produces calcitonin, and it is affected in Grave’s disease
 and goiter, the latter of which occurs with an iodine deficiency.
***** ANSWER:
thyroid gland
**** Team B:                                                          :drill:
This organ, in which old red blood cells are destroyed, consists of
red pulp and white pulp.
***** ANSWER:
spleen
**** Tossup:                                                          :drill:
Problems in this organ can be detected if high amounts of
 trans·aminases are found within it. A process that occurs primarily
 in this organ converts two lactate molecules into one glucose
 molecule, then sends the glucose back to muscle cells. The falci·form
 ligament divides this organ into two parts. Macro·phages named
 Kupffer cells are located here. The Cori cycle, gluco·neo·genesis,
 and the urea cycle occur primarily in this organ. This organ converts
 bilirubin to a more water-soluble form. This organ secretes bile,
 which can be stored in the nearby gallbladder. It is damaged by
 cirrhosis (sir-ROH-sis) and hepatitis. Name this largest internal
 organ of the body.
***** ANSWER:
liver
** Round Two
*** English / World Literature: Name the following related to East Asian literature.
**** Team B:                                                          :drill:
What work by Lady Murasaki (MUR-uh-sah-kee), sometimes considered to
 be the first novel, is a depiction of classical Japanese court life?
***** ANSWER:
The Tale of Genji or [Genji monogatari]
**** Team A:                                                          :drill:
Zeami (zay-AHM-ee) is considered to be a practitioner of what medieval
 Japanese art form, which emphasizes a slow, stylized performance and
 actors with masks?
***** ANSWER:
noh [or nogaku or noh drama or noh play or noh theater]
**** Tossup:                                                          :drill:
In this work, a character causes fiery bricks to fall from heaven,
 leading to the creation of Flaming Mountain. A group of characters in
 this work make a pilgrimage to Vulture Peak. This novel’s main
 character was born from a magic stone infused with the power of
 heaven on top of a mountain. This novel’s characters include Pigsy,
 Sandy, and Sun Wukong, who sometimes provides the alternate name of
 this novel, (*) Monkey. Name this novel, one of the four Chinese
 classics, which is named for a voyage to India.
***** ANSWER:
Journey to the West [or Xi You Ji or Hsi-yu chi; prompt on “Adventures of the ***Monkey God” or “Monkey
 to the West” or “The Adventures of Monkey”; prompt on “Monkey” before (*)]
 American Government / Economics: Name these current U.S. governors.
**** Team A:                                                          :drill:
Raised as Sikh, this Indian-American woman and youngest current
 governor has served as South Carolina’s Governor since succeeding
 Mark Sanford in 2011.
***** ANSWER:
Nimrata Nikki Randhawa Haley
**** Team B:                                                          :drill:
This other Indian-American, who has served as the Governor of
 Louisiana since 2008, made headlines in January 2015 for criticizing
 Western European governments for allegedly allowing Muslim-controlled
 “no-go zones.”
***** ANSWER:
Piyush “Bobby” Jindal (JIN-dul)
**** Tossup:                                                          :drill:
In 2011 this governor pulled his state out of the environmental
 organization Regional Greenhouse Gas Initiative.  Shortly before
 being re-elected as governor over Barbara Buono, he authorized over
 ten million dollars to be spent on a special election to fill the
 seat left by deceased U.S. Senator Frank Lautenberg, which was won by
 Cory Booker. In January 2015 he was criticized for accepting
 all-expense paid trips to several Dallas Cowboys football games. This
 governor was embroiled in a 2013 scandal in which members of his
 staff were involved in the closure of traffic lanes that provided
 residents of Fort Lee access to the George Washington Bridge. Name
 this current Governor of New Jersey.
***** ANSWER:
Christopher James Christie
*** Physics: This set of questions will deal with the nature of light.
**** Team B:                                                          :drill:
Since light behaves like a wave at times, it will often exhibit what
 phenomenon, in which waves superpose to create a new wave with a
 different amplitude?
***** ANSWER:
interference [accept word forms]
**** Team A:                                                          :drill:
What physicist used a “grating” to conduct the double-slit experiment,
 in which he showed that light behaves like a wave and a particle?
***** ANSWER:
Thomas Young
**** Tossup:                                                          :drill:
Mantis shrimp are one of the few species that can detect light with
 this property. Dichroism (DYE-cro-ism) induced by light with this
 property is commonly used in a form of spectroscopy that examines the
 secondary structure of proteins. Light with a related planar property
 can be turned into light with this property by using a quarter
 wave-plate.  Like its “linear” counterpart, the intensity of light
 that has this property is given by Malus’ (MAL-iss-iz) law. Name this
 property of light, in which its electric field oscillates in a
 corkscrew fashion.
***** ANSWER:
circular polarization [accept word forms, prompt on “polarization”]
*** Geography: Name these mountain ranges.
**** Team A:                                                          :drill:
The Novaya Zemlya (NOH-vuh-yuh zem-lee-YAH) archipelago is a northern
 extension of this mountain range that lies along the continental
 border that splits Russia into European and Asian sides.
***** ANSWER:
Ural Mountains [or Urals or Uralsky Khrebet]
**** Team B:                                                          :drill:
Mont Blanc is the highest peak in this European mountain range that
 dominates the geography of Switzerland and western Austria.
***** ANSWER:
Alps [accept Alpine Mountains]
**** Tossup:                                                          :drill:
Longs Peak is one of most notable features within this mountain
 range’s namesake national park. This range is at the west end of the
 Laurentian Divide, and one part of this range is traversed by the
 Icefields Parkway, which runs north from Lake Louise into Jasper
 National Park. The Sawatch [suh-“WATCH”] and Bitterroot Ranges are
 sub-ranges of these mountains, which include both Mount Elbert and
 Pikes Peak. These mountains contain the world’s largest concentration
 of geysers within Yellowstone National Park. Name this North American
 mountain range which runs from British Columbia to New Mexico.
***** ANSWER:
Rocky Mountains or Rockies [accept Canadian Rocky Mountains or Canadian Rockies]
*** American History: Name these battles of the Civil War.
**** Team B:                                                          :drill:
Joseph Hooker was defeated by Robert E. Lee at this May 1863 battle
 best remembered as the battle at which “Stonewall” Jackson was
 wounded by friendly fire, ultimately leading to his death.
***** ANSWER:
Battle of Chancellorsville
**** Team A:                                                          :drill:
The Union Army regained control of the Mississippi River with Ulysses
 Grant’s victory at this nearly two month long battle, which was ended
 when John Pemberton surrendered on July 4th, 1863.
***** ANSWER:
Battle of Vicksburg or Siege of Vicksburg
**** Tossup:                                                          :drill:
One commander at this battle located his headquarters at the Philip
 Pry House. This skirmish was preceded by the Battle of South
 Mountain, and A.P. Hill arrived at this battle with reinforcements
 following the Confederate victory two days earlier at the Battle of
 Harpers Ferry. Prior to this skirmish, Union soldier Barton Mitchell
 discovered the Confederate battle plans, known as Special Order 191,
 wrapped around three cigars. Fighting locations at this battle
 included the “Bloody Lane” and “Burnside’s Bridge.” The result of
 this battle prompted Abraham Lincoln to announce the Emancipation
 Proclamation. Name this single-day bloodiest battle of the Civil War
 in which George McClellan halted Robert E. Lee’s advance into
 Maryland.
***** ANSWER:
Battle of Antietam (an-“TEE”-tum) [or Battle of Sharpsburg]
** Alphabet Round – Letter A
*** Give                                                              :drill:
 (HYPHENATED ANSWER) – This former eye doctor and leader of the Ba’ath
 Party is the current President of Syria.
**** ANSWER:
Bashar Hafez al-Assad (HYPHENATED ANSWER)
 2. In classical mechanics, this vector quantity is defined as the time derivative of velocity.
 2. acceleration

*** Give                                                              :drill:
 This historian wrote the novels Esther and Democracy, but he is best
 known for a Pulitzer Prize-winning account of his own “Education.”
**** ANSWER:
Henry Brooks Adams
*** Give                                                              :drill:
 (TWO WORD ANSWER) – Term used to describe singing without
 accompaniment.
**** ANSWER:
a cappella (TWO WORD ANSWER)
*** Give                                                              :drill:
 Distinguished from comparative advantage, this term refers to the
 ability of an agent to produce more of a good than a
 competitor. Unlike comparative advantage, it does not explain why
 international trade is mutually beneficial.
**** ANSWER:
absolute advantage
*** Give                                                              :drill:
 (MULTI-WORD ANSWER) – Document which outlined the way the
 U.S. government was run before the ratification of the
 U.S. Constitution.
**** ANSWER:
Articles of Confederation and Perpetual Union (MULTI-WORD ANSWER)
*** Give                                                              :drill:
 Neurodegenerative disease that causes dementia and is characterized
 by beta-amyloid plaques that accumulate in the brain.
**** ANSWER:
Alzheimer’s disease
*** Give                                                              :drill:
 This evil magician, who repeatedly deceives the Red Crosse Knight, is
 the villain of most of book one of Edmund Spenser’s The Faerie
 Queene.
**** ANSWER:
Archimago
*** Give                                                              :drill:
 Christian season which ends on Christmas Eve.
**** ANSWER:
Advent
*** Give                                                              :drill:
 (TWO WORD ANSWER) – 1260 battle in which the Mongol Empire was
 defeated by the Mamluks in present day Israel.
**** ANSWER:
Battle of Ain Jalut or Battle of Ayn Jalut (TWO WORD ANSWER)
*** Give                                                              :drill:
 (TWO WORD ANSWER) – This film, which was directed by Francis Ford
 Coppola, is a Vietnam War adaptation of Joseph Conrad’s Heart of
 Darkness. It contains the line “I love the smell of napalm in the
 morning.”
**** ANSWER:
Apocalypse Now (TWO WORD ANSWER)
*** Give                                                              :drill:
 This type of computer language usually involves manipulating
 registers directly. Compilers typically turn a high-level language
 into this kind of lower-level one.
**** ANSWER:
assembly language [accept assembler]
*** Give                                                              :drill:
 This novelist wrote a novel about Okonkwo, whose village undergoes
 Westernization, titled Things Fall Apart. This man also wrote a
 sequel to Things Fall Apart entitled No Longer at Ease.
**** ANSWER:
Chinua Achebe [or Albert Chinualumogu Achebe]
*** Give                                                              :drill:
 Spanish slave ship that was at the center of an 1841 Supreme Court
 case after it landed in the U.S. following a successful slave mutiny.
**** ANSWER:
La Amistad
*** Give                                                              :drill:
 Evil Egyptian deity who attacks Ra and the solar barge each day, but
 ultimately fails.
**** ANSWER:
Apep or Apophis
*** Give                                                              :drill:
 (ONE OR TWO WORD ANSWER) – American artistic movement associated with
 a group called “The Eight”, whose members included Robert Henri and
 Everett Shinn.
**** ANSWER:
Ashcan School or Ash Can School (ONE OR TWO WORD ANSWER)
*** Give                                                              :drill:
 Peninsula on which Baku, the capital of Azerbaijan, is located.
**** ANSWER:
Absheron Peninsula
*** Give                                                              :drill:
 (NAME AND REGNAL NUMBER REQUIRED) – Papal name used by Nicholas
 Breakspear, the only Englishman to serve as Pope.
**** ANSWER:
Adrian IV (the fourth) (NAME AND REGNAL NUMBER REQUIRED)
*** Give                                                              :drill:
 This literary term refers to the repeated use of a phrase at the
 beginning of multiple clauses, such as “it was the best of times, it
 was the worst of times…”
**** ANSWER:
anaphora
*** Give                                                              :drill:
 Element that is extracted and refined through the Bayer and
 Hall-Heroult processes.
**** ANSWER:
aluminum or aluminium
** Lightning Round
*** Give                                                              :drill:
This poem was written as a series of stanzas that each end with a “bob
 and wheel”. One of its title characters is given a kiss one day, two
 kisses the next, and three kisses on a third day, and they’re all
 from a lady who gives him a magic girdle. Earlier, that man had
 beheaded a visitor to King Arthur’s court with the agreement that he
 is beheaded a year later.  The “Pearl Poet” is thought to have
 authored what medieval poem centering on the two, title knights?
**** ANSWER:
Sir Gawain and the Green Knight
*** Give                                                              :drill:
This artist depicted a procession of men in suits and top hats behind
 a girl in an orange cap in the painting Anxiety. A red-headed woman
 is shown sinking her mouth into the neck of a man in his painting
 Vampire. This artist of the Frieze of Life series is best known for a
 painting with a body of water and red sky behind the primary figure,
 who stands next to a roadway railing with his hands on the side of
 his head and his mouth agape. Name this Norwegian painter of The
 Scream.
**** ANSWER:
Edvard Munch (ED-vard MOONK)
*** Give                                                              :drill:
Securin (suh-KYOO-rin) is not cleaved until after this stage of the
 cell cycle, since separase (SEP-uh-“race”) and the APC are inhibited
 until the cell advances past its namesake checkpoint. Right before
 this phase begins, the mitotic spindle binds to kineto·chores
 (kih-NET-oh-“cores”). In this stage, the centromeres of each
 chromosome line up on a namesake plate. Name this stage of (*)
 mitosis that follows prophase.
**** ANSWER:
metaphase [prompt on “mitosis” before (*)]
*** Give                                                              :drill:
During one military campaign, this leader transferred power to Jean
 Kleber (zhahn CLAY-“bear”) after his victory at the Battle of Abukir
 (AH-boo-keer). This leader’s victory at the Battle of Friedland ended
 the War of the Fourth Coalition and resulted in the favorable
 Treaties of Tilsit. He won the Battle of Borodino during his failed
 invasion of Russia, and he lost all power when the Duke of Wellington
 defeated him at the 1815 Battle of Waterloo. Name this diminutive
 leader of early 19th century France.
**** ANSWER:
Napoleon Bonaparte [or Napoleone Buonaparte; accept any underlined name; accept Napoleon I]
*** Give                                                              :drill:
This religion’s eschatology (ess-kuh-TAHL-uh-jee) includes the Chinvat
 (CHEEN-vat) Bridge, which separates the world of the living from the
 world of the dead. A now-extinct branch of this religion venerated
 its purely neutral god Zurvan. It venerates its dead in so-called
 “Towers of Silence” and imagines that six Amesha Spentas (uh-MESH-uh
 SPEN-tuhz) are opposed by the evil god Ahriman (AH-ree-mawn), who is
 continuously fighting with Ahura Mazda (uh- HUR-uh MAHZ-duh). Name
 this Persian dualistic religion that was founded by Zarathustra
 (zair-uh-THEW-struh).
**** ANSWER:
Zoroastrianism (zoh-roh-AST-ree-un-izm) [accept Magianism or Parsiism; accept Mazdaism before
 “Mazda”; accept Zarathustraism before “Zarathustra”; accept word forms of all acceptable answers]
*** Give                                                              :drill:
One character in this play is the subject of a novel by Marsye Conde
 (MAR-cee-yay CON-day), in which that character falls in love with
 John Indian. Another character in this play is unable to remember the
 commandment that forbids adultery. Its characters include Judge
 Hathorne and Rebecca Nurse, the latter of whom is sentenced to be
 hanged. Other characters include the slave Tituba (teh-TOO-bah) and
 John Proctor. Name this play by Arthur Miller about the Salem
 Witchcraft Trials.
**** ANSWER:
The Crucible
*** Give                                                              :drill:
A piece by this composer begins with two violas and four cellos
 playing the tune to a troparion. A tone poem by him was written for
 wounded soldiers from the Turko-Serbian War. That piece contains the
 anthem “God Save the Tsar,” which, with “La Marseillaise” (lah
 mar-SAY-ez), is found within another composition by him that includes
 cannons.  Name the Russian composer of Marche Slave and the 1812
 Overture.
**** ANSWER:
Peter Ilich Tchaikovsky (chy-KOFF-skee) [or Pyotr Ilyich Tchaikovsky]
*** Give                                                              :drill:
Followers of this mathematician did not believe in the existence of
 irrational numbers, which is why they supposedly drowned Hippasus
 (hi-PAH-sus) for proving that the square root of two was
 irrational. His belief that music and planetary motion were linked is
 a doctrine called the music of the spheres. Before becoming
 president, James Garfield proved the theorem named for this
 man. Identify this mathematician who names a theorem about right
 triangles which states that the square of the hypotenuse is equal to
 the sum of the squares of the other two sides.
**** ANSWER:
Pythagoras [accept Pythagorean theorem]
*** Give                                                              :drill:
This ruler sent one of his generals, Arnaldo Ochoa, to lead troops
 during the Ethio-Somali War. Operation Mongoose was an attempt to
 overthrow this leader. The Moncada (mohn-KAH-dah) Barracks were the
 target of an attack by this man, who came to power after the 26th of
 July Movement overthrew Fulgencio (fool-HAYN-see-oh) Batista. The Bay
 of Pigs invasion tried to topple this leader, who was succeeded in
 2008 by his brother Raul. Name this man who, from 1959 to 2008, ruled
 Communist Cuba.
**** ANSWER:
Fidel Alejandro Castro Ruz
*** Give                                                              :drill:
The normal form representation of these scenarios include listing out
 all possibilities in a payoff matrix, as well as listing all
 conceivable strategies. Some of these situations, such as nim and
 Kuhn poker, are of the “zero-sum” type.  Another one of these
 situations, known as the stag hunt, is similar to one of these
 scenarios in which two people must choose to cooperate or
 defect. Name these hypothetical situations that give their name to a
 field of study and include the prisoner’s dilemma.
**** ANSWER:
game theory games
*** Give                                                              :drill:
This nation contains an “east” and “west” area settled by and named
 after the Griqua (GREE-khuw) people. The Highveld is a large plateau
 area within this nation, which has part of its northern border formed
 by the Limpopo River.  This is the largest nation that contains part
 of the Drakensberg Mountains, and its southernmost point is near the
 Cape of Good Hope. Lesotho is surrounded by what African nation whose
 three capitals are Bloemfontein, Pretoria, and Cape Town?
**** ANSWER:
Republic of South Africa [prompt on “RSA”]
*** Give                                                              :drill:
One character in this novel lied about the disappearance of Sarah
 Dunkirk so that he could acquire her family fortune.  John Raffles
 appears in this book to reveal the devious nature of Nicholas
 Bulstrode. Another character in this work was writing the book The
 Key to All Mythologies. The will of that man, Edward Casaubon
 (CAH-suh-bon), forbids Dorothea Brooke from marrying Will
 Ladislaw. Name this “study of provincial life,” a novel by George
 Eliot.
**** ANSWER:
Middlemarch: A Study of Provincial Life
*** Give                                                              :drill:
This scientist built the first homopolar (ho-MAH-puh-lur) motor, which
 generates a certain force in one direction. This scientist gives his
 name to a protective enclosure of metal that is designed to shield
 objects from electromagnetic radiation. Lenz’s law gives the
 direction of the induced EMF that is given by his namesake law, which
 describes the behavior of a magnetic field when it interacts with an
 electric circuit. Name this scientist known for his law of induction.
**** ANSWER:
Michael Faraday
*** Give                                                              :drill:
This politician was elected governor three times as the successor to
 Culbert Olson. This man was the running mate of Thomas Dewey in the
 Election of 1948. He succeeded Fred Vinson in his highest position,
 which saw him issue decisions in such cases as Baker v. Carr and
 Gideon v. Wainwright; in that same position, he headed a namesake
 commission that investigated the assassination of John
 F. Kennedy. Name this Chief Justice of the Supreme Court from 1953
 to 1969.
**** ANSWER:
Earl Warren
*** Give                                                              :drill:
One religious structure designed by this architect is in Garden Grove,
 California and is where the weekly Hour of Power show is
 produced. This non-German architect of the Crystal Cathedral designed
 the building in New York City which contains the Four Seasons
 Restaurant. A housing structure in New Canaan designed by this
 architect was inspired by Mies’s (MEEZ-iz) Farnsworth House. Name
 this American architect who designed the Seagram Building and the
 Glass House.
**** ANSWER:
Philip Cortelyou Johnson
*** Give                                                              :drill:
While folding a sheet, one member of this family ascends to
 heaven. Another member of this family named Rebecca is known for
 eating whitewash from walls. While facing the firing squad, another
 member of this family recalls the afternoon that his father took him
 to discover ice. This family includes many members named Aureliano
 (or-“ale”-ee-AN- oh). Name this family that is at the center of the
 Gabriel Garcia Marquez novel 100 Hundred Years of Solitude.
**** ANSWER:
Buendia family
 17. According to one myth, late in life this figure married Astymedusa. Prior to his birth, this figure’s father kidnapped
 and raped Chrysippus (cry-SIP-iss). King Polybus was the adoptive father of this figure, who determined that “man” was
 the answer to the riddle of the sphinx. He was succeeded as king by his uncle, Creon, after he blinded himself upon
 learning that his parents were Laius (LAY-us) and Jocasta. Name this mythical King of Thebes who fulfilled a prophecy
 that he would kill his father and marry his mother.
*** Give                                                              :drill:
Oedipus (ED-ih-puss) [or Oidipous; accept Oedipus Rex or Oidipous
Tyrannos or Oedipus the King]
 18. In lyo·phili·zation, this phenomenon is used to remove water from the desired material. Either this process or
 recrystallization is used in the final step of purifying caffeine. This process is the opposite of deposition, which, along
 with this process, occurs at temperatures and pressures below the triple point. At STP, dry ice undergoes what type of
 phase change in which a solid changes directly into a gas?
**** ANSWER:
sublimation [accept word forms]
*** Give                                                              :drill:
This philosopher attacked the bizarre mysticism of Emmanuel Swedenborg
 in Dreams of a Spirit Seer. He distinguished between the phenomenon
 and the noumenon (“NEW”-muh-non) in a work that proposes humanity has
 innate categories of knowledge; that work argues that synthetic a
 priori truths are possible, using the example of seven plus five
 equals twelve. Name this German philosopher who wrote the Critique of
 Pure Reason.
**** ANSWER:
Immanuel Kant
*** Give                                                              :drill:
One contributing cause to this event was Henry Wilde’s replacement of
 David Blair. Senator William Alden Smith chaired an inquiry into this
 event, survivors of which were rescued by the RMS Carpathia. J. Bruce
 Ismay was criticized for his actions during this event, which was the
 subject of the book A Night To Remember. Millionaire Molly Brown was
 given the nickname “unsinkable” following what 1912 event in which
 the world’s largest ship hit an iceberg and sank?
**** ANSWER:
sinking of the RMS Titanic [accept equivalents that mention the RMS
 Titanic]
