** Round Two
*** English / World Literature: In this set of questions, you will name writers who wrote about alchemy.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       a484851e-0998-4ba3-9dc8-f23bb78217dd
     :END:

What writer, the husband of Elizabeth Barrett, wrote about an
alchemist who contemplates his achievements in Paracelsus
(“PAIR”-uh-SELL-suss)?
***** Answer
Robert Browning 
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       eb39d039-600e-4891-ae67-9c6b5ff0fba6
     :END:
What author, the wife of Percy, wrote about a scientist named Victor
who creates a monster through assemblages and alchemy?
***** Answer
Mary Wollstonecraft Shelley
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       e4ab1f80-c0ee-4d33-a622-0cb0e0c8b567
     :END:
This writer wrote a story about a canon who tricks a clergyman into
thinking mercury can be alchemized into quicksilver. Another story by
this writer concerns a fox getting outwitted by a proud cock named
Chauntecleer (CHAWN- tih-“clear”). In another story by this author,
Nicholas farts into the face of Absolon (ab-SO-lawn), who then uses a
red hot poker to singe Nicholas’ rear end. All of those stories by
this author appear in a collection that opens with a General Prologue
in which pilgrims stay at the Tabard Inn. Name this medieval English
author who included “The Miller’s Tale” as one of his many Canterbury
Tales.
***** Answer
Geoffrey Chaucer
*** American Government / Economics: Name the following related to the U.S. Congress.
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       9028dd35-82da-45ce-90fc-e99389e88891
     :END:
The Constitution’s “Necessary and Proper” clause is used as
justification to give Congress powers of this type, which are not
expressly granted by the Constitution.
***** Answer
implied powers 
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       c661a879-610e-403e-a820-27cae5faee41
     :END:
When combining the House of Representatives and Senate, this is the
number of voting members of which Congress is comprised.
***** Answer
five hundred thirty-five or 535 
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       f161e845-7d79-4fdd-bf63-b428e7176a66
     :END:
Proceedings related to this action are not subject to judicial review
according to the ruling of a 1993 Supreme Court case involving Walter
Nixon. William Belknap was the only Cabinet member to whom this action
was applied, and in 15 of the 19 times in which this action took
place, the target was a federal judge. It first occurred to a
U.S. president after a violation of the Tenure of Office Act
in 1868. A trial overseen by the Senate occurs after the House of
Representatives takes this action, which can be initiated due to
“treason, bribery, or other high crimes and misdemeanors.”  Name this
action in which a federal official is removed from office.
***** Answer
impeachment [accept word forms]
*** Physical Science: Name these chemists.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       efaac4af-2f25-40a5-979e-5f648de3c718
     :END:
This man, who invented dynamite, lends his name to a set of annual
prizes given out in Oslo and Stockholm.
***** Answer
Alfred Bernhard Nobel (no-BELL) [accept Nobel Prizes]
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       ba72bae9-b839-43fb-aa0f-c45387aa85f3
     :END:
This Russian scientist’s most notable contribution was his creation of
the periodic table.
***** Answer
Dmitri Ivanovich Mendeleyev
  (MEN-duh-LAY-eff) 
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       b2ccfc96-775b-436d-931d-a69035135264
     :END:
This scientist determined that diamond was an allotrope of carbon, and
he correctly noted that water was not a separate element. In his
Methods of Chemical Nomenclature, he set up the first widely-used
chemical naming system.  After experiments in which he heated solids
inside closed containers and found no change in weight, he formulated
the law of conservation of matter. This scientist discredited the
phlogiston theory and named the element that was discovered out of it,
oxygen. Identify this “father of modern chemistry”, a French scientist
who was guillotined (GEE-uh-teend) during the French Revolution.
***** Answer
Antoine-Laurent de Lavoisier (lah-VWAH-zee-ay OR luh-vwah-ZYAY)
*** Geography: Name these Asian rivers.
**** Team A: The Kara Su and Murat                                    :drill:
     :PROPERTIES:
     :ID:       909a5fde-a8f6-467c-b5a6-eaac43d56a17
     :END:
Su co mbine to form this river which, along with the Tigris River,
flows through the region known as Mesopotamia.
***** Answer
Euphrates
 (yoo-FRAY-teez) River [or al-Furat] 
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       525241d4-76db-484c-bbe7-de9de832687b
     :END:
The Bay of Bengal receives the delta of this chief river of
northeastern India that is holy to practitioners of Hinduism.  
***** Answer
Ganges (GAN-jeez) River [or Ganga River] 
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       4e6ead6f-bb88-4be2-8428-e917e832fd35
     :END:
The Fengdu Ghost City is a notable tourist attraction along this
river, into which the Poyang Lake empties. This river was the last
known home of the baiji (“bye”-JEE) dolphin, which was declared
functionally extinct in 2006. The world’s longest bridge, the
Danyang-Kunshan, runs along this river’s delta. This river flows
through the cities of Wuhan, where it meets the Han River, and
Chongqing (CHONG-ching) before emptying into the East China Sea. The
Three Gorges Dam was constructed on what Chinese river that flows past
the city of Shanghai and is the world’s third longest?  
***** Answer
Yangtze River [or Chang Jiang]
*** American History: Name the following related to slavery in the United States.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       5a3a45a2-e2b0-43c8-906f-087ff79163c9
     :END:
The Fugitive Slave Act was one of several provisions of this 19th
century legislation which was drafted by Henry Clay and Stephen
Douglas and resulted in California being admitted to the Union as a
free state.
***** Answer
Compromise of 1850 
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       c1576db2-7810-4bb6-adb9-441d558a9088
     :END:
Attorney Thomas Gray published the Confessions of this slave best
remembered for leading a Virginia slave rebellion in August 1831.
***** Answer
Nathaniel Turner 
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       c788e5cd-abb1-40a7-8434-05e6f91d94fb
     :END:
Prior to this man’s most notable action, he used the alias Isaac Smith
while lodging at the Robert Kennedy Farmhouse. This man fought against
Henry Pate at the Battle of Black Jack; shortly thereafter, he
attempted but failed to prevent an attack on a town that later became
his nickname, Osawatomie. He led a group that killed five pro-slavery
Kansans in the Pottawatomie Massacre. During his best known action, he
was captured by troops under Robert E. Lee in response to his seizure
of a Federal Armory in Virginia. Name this abolitionist who attempted
to incite a slave revolt in 1859 by raiding the town of Harpers Ferry.
***** Answer
John Brown

** Round Two
*** English / World Literature: Name the following related to William Shakespeare.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       72b7e3be-f1b7-4813-9be0-7f1c0245cc94
     :END:
Antonio is the title character of what play by William Shakespeare
that includes a moneylender named Shylock?
***** ANSWER:
The Merchant of Venice
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       5eecde9f-c003-495e-bf04-9a7d94e0542f
     :END:
What play by William Shakespeare includes Goneril [GAHN-er-uhl] and
Regan, who are two ungrateful daughters of the title character?
***** ANSWER:
The Tragedy of King Lear
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       91097654-48d0-4a4d-9afc-5c1a07580309
     :END:
This writer imagined a fictional sister of William Shakespeare who is
denied the opportunity to write because she lacks “a room of one’s
own.” This author wrote about six friends, including Bernard and
Neville (neh-VUHL), who soliloquize on the nature of life, in an
experimental work in which the theme of water provides a
backdrop. Lily Briscoe visits the Ramsays (RAM-seez), who live on the
Isle of Skye, in a book by this author named for a sea-side structure
that Mr. Ramsay wishes to visit. Name this author of the Bloomsbury
Group who penned The Waves and To the Lighthouse.
***** ANSWER:
Adeline Virginia Woolf [accept Virginia Stephen]
*** American Government / Economics: Name these amendments to the U.S. Constitution.
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       6c1af57e-40fa-4f4d-a009-164b99904680
     :END:
Ratified in 1961, this amendment gave citizens of the District of
Columbia the ability to vote in presidential elections by granting
Washington D.C. members in the Electoral College.
***** ANSWER:
      23rd Amendment
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       26ec4e51-6cc6-47cd-969e-911574a04663
     :END:
Ratified in 1913, this amendment allows for the direct election of
U.S. Senators, who had previously been chosen by state legislatures.
***** ANSWER:
      17th Amendment
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       144f0037-7b5a-45d9-ba1f-8cfe532ed386
     :END:
Joseph McKenna argued that this amendment had an “expansive and vital
character” in the majority opinion for Weems v. United States. Since
the 1958 case Trop v. Dulles, the “evolving standards of decency” test
has been applied in cases dealing with this amendment, which, along
with the 14th amendment, was at the center of a 1972 case involving
William Furman. In the case Gregg v. Georgia, the Supreme Court ruled
that this amendment was not automatically violated by sentences
involving the death penalty. Name this Bill of Rights amendment which
outlaws “excessive bail, “excessive fines,” and “cruel and unusual
punishments.”
***** ANSWER:
      8th Amendment
*** Physics: Name these scientists.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       e8171298-a652-4c7f-9c58-488cb9387f96
     :END:
What Swedish astronomer gives his name to a scale that is defined by
adding -273.15 units to the Kelvin scale?
***** ANSWER:
Anders Celsius
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       30ff75bb-848a-4d1f-ab46-5ac5ebf52c9c
     :END:
What German physicist, known for proving the existence of
electromagnetic waves, gives his name to the SI unit of frequency?
***** ANSWER:
Heinrich Rudolf Hertz
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       9c799da4-d68c-4151-bbbe-244b227647f9
     :END:
Like the hertz, this scientist’s namesake SI derived unit has units of
inverse seconds. This man’s father discovered that light changes the
voltage of a material in the photovoltaic effect. This scientist’s
greatest discovery involved salts that emitted rays; those rays were
captured on photographic plates. He was awarded a Nobel Prize in
Physics along with Pierre and Marie Curie (“CURE”-ee) for his
discovery of radioactivity in uranium. Name this scientist who gives
his name to the SI unit of radioactivity, which is abbreviated “Bq”
(“B” “Q”).
***** ANSWER:
Antoine Henri Becquerel
*** Geography: Name these African nations.
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       4db2aff9-a0a7-4503-9803-44584f3b8d67
     :END:
The western terminus of the Atlas Mountains is in this nation that is
directly to the north of the territory of Western Sahara, over which
this nation disputes ownership.
***** ANSWER:
Kingdom of Morocco [or al-Mamlakah al-Maghribiyah]
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       67021100-da79-4ac2-b880-2adecd176af8
     :END:
The southwestern shores of Lake Chad border what largest oil-producing
nation in Africa that is directly north of the Bight of Biafra, an arm
of the Gulf of Guinea.
***** ANSWER:
Federal Republic of Nigeria
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       5f736e7b-0029-4b41-8301-04b870de85c8
     :END:
The extreme north part of this nation contains colorful hot springs
within a volcanic crater named Dallol, which is within the Danakil
Depression and recognized as having the hottest average temperature in
the world. UNESCO established a World Heritage Site at the ancient
ruins of its city of Axum (AHK-soom). The north end of Lake Turkana is
controlled by this nation, as is all of Lake Tana, which is the source
of the Blue Nile River. It disputes a border with its northern
neighbor, Eritrea, which gained independence from this nation. Sudan,
South Sudan, Kenya, Djibouti (jih-BOO- tee), and Somalia also share
borders with what East African nation whose capital is Addis Ababa?
***** ANSWER:
Federal Democratic Republic of Ethiopia [or Ityop'iya Federalawi
Demokrasiyawi Ripeblik]
*** American History: Name these 19th century events.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       c8dcc8ec-1118-4983-bfe6-548b267a9107
     :END:
Fort Clatsop was constructed in 1805 as part of this expedition,
during which Sacagawea aided in the exploration of lands recently
acquired by the U.S. in the Louisiana Purchase.
***** ANSWER:
Lewis and Clark expedition [accept similar answers mentioning
Meriwether Lewis and William Clark; accept Corps of Discovery
expedition]
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       cc5cf43e-96ca-4a15-a4a6-4bbca80bd406
     :END:
This event, the participants in which were often referred to as 49ers,
was set off by the 1848 discovery of a certain commodity by James
Marshall at Sutter’s Mill.
***** ANSWER:
California Gold Rush [prompt on “gold rush”]
**** Tossup:                                                         :drill:
     :PROPERTIES:
     :ID:       dd359ff8-9cc9-44da-b49a-220395a6371e
     :END:
One man injured during this event later killed his wife, Clara Harris,
while serving as a U.S. Consul; that man was Henry Rathbone. The
target of this event died at the Peterson House. Mary Surratt became
the first woman to be executed by the U.S. government following this
event, which occurred on the same night that Lewis Powell attempted to
kill Secretary of State William Seward. Doctor Samuel Mudd was jailed
for treating the broken leg of its perpetrator, who shouted “Sic
semper tyrannis” after jumping onto the stage during a showing of the
play Our American Cousin. Name this 1865 event carried out at Ford’s
Theater by John Wilkes Booth.
***** ANSWER:
assassination of Abraham Lincoln [accept killing of Abraham Lincoln,
or other equivalents; prompt if Lincoln is not mentioned]

** Round Two
*** English / World Literature: Name these authors who wrote about large beasts.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       f3deab2b-9402-47df-97dd-3ea02db0023b
     :END:
What soldier, prisoner, and author wrote about the “questing beast” in
his compilation of Arthurian myth, Le Morte Darthur (luh mort
DAR-thur)?
***** ANSWER:
Thomas Mallory
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       c463bd59-7f95-4319-9247-fd5308c85385
     :END:
What author wrote about a giant bear who is exposed to the politics of
the Beklan Empire in Shardik? A rabbit named Hazel is the protagonist
of his novel Watership Down.
***** ANSWER:
Richard George Adams
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       f4302e61-0a0a-4005-93e0-5eaa728f5f6f
     :END:
In one work this author wrote about Calidore (CAL-ih-door), a knight
whose mission is to slay the Blatant Beast.  In that poem by this
author, the recurring character of Colin Clout plays songs on his
bagpipe. This man’s love for Elizabeth Boyle inspired his sonnet
sequence Amoretti (ah-moh-RET-ee). Holiness, Temperance, Chastity,
Friendship, Justice, and Courtesy are the themes of his masterpiece,
which makes use of the ABABBCBCC (“A-B-A-B-B-C-B-C-C”) rhyme scheme
and idealizes Queen Elizabeth as the title figure. Name this 16th
century author of the epic poem The Faerie Queene.
***** ANSWER:
Edmund Spenser
*** American Government / Economics: These questions will involve the economics of society’s ability to make goods.
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       9e2bd429-0d49-4647-94fa-ef171d3eeb09
     :END:
What diagrams depict two goods, such as guns and butter, and a
society’s ability to make them? They are generally used to illustrate
the tradeoffs between making said two goods.
***** ANSWER:
production possibility frontier [or ppf, accept production
possibilities frontier or production possibility diagram or production
possibilities diagram]
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       ec7664cc-c5f3-49cd-9f23-b73ee1e917c2
     :END:
The production possibilities frontier illustrates this type of cost of
making a good, which is defined as the alternatives one foregoes to
engage in an activity.
***** ANSWER:
opportunity cost
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       7f1fa33c-10f6-4610-b362-9d2463c18a90
     :END:
In agreement with the views of the libertarian Richard Cobden, this
economist argued that England’s ability to make technological advances
were hampered by its desire to keep import duties high. He extended
Ferdinand Lasalle’s (LUH-“Sal’s”) argument that payments to laborers
would, in the long run, tend toward the level necessary for
subsistence, which became known as his iron law of wages. Name this
British economist who wrote Principles of Political Economy and
Taxation and Rent in addition to developing a theory of international
trade.
***** ANSWER:
David Ricardo
*** Physics: Answer the following related to James Clerk Maxwell.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       bf2ad9b6-9b5e-4b22-98f0-01666ce5f007
     :END:
What scientist names the one of Maxwell’s equations that states that
the divergence of a magnetic field must equal zero?
***** ANSWER:
Johann Carl Friedrich Gauss (gowss)
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       48abad59-a2c8-40cb-9260-8fc02bec06b4
     :END:
This French scientist’s namesake law, which Maxwell re-derived,
relates the current passing through a circuit to the strength of the
magnetic field in the circuit.
***** ANSWER:
Andre-Marie Ampere (am-PEER)
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       e46a75d3-d994-4e67-8ded-dab6c85f6ca9
     :END:
Along with James Clerk Maxwell, Wilhelm Wien (veen) names a type of
this device that is unusually used to measure inductance. A
Kelvin-Varley divider is an analog of this device that is used to
split a circuit’s voltage. They were invented by Samuel Christie and
rely on Kirchoff’s (KEER-coffz) laws to measure an unknown
quantity. They are similar to a potentiometer
(poh-TEN-“she”-om-ih-tur) and are used to measure the electrical
resistance of an unknown component. Name these diamond-shaped
configurations that consist of four resistors and are a type of bridge
circuit.
***** ANSWER:
Wheatstone bridge [prompt on “bridge” or “bridge circuits”]
*** Geography: Name these American rivers.
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       7a8bca27-ca5b-490c-8ba9-4702df81c27d
     :END:
The cities of Laredo and El Paso lie along the banks of this river
which forms the border between Texas and Mexico.
***** ANSWER:
Rio Grande [or Rio Bravo del Norte]
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       b7175e90-4284-423e-9e5d-8d1612b34152
     :END:
The Shenandoah and Anacostia Rivers are tributary to this waterway
that empties into Chesapeake Bay and separates Arlington County,
Virginia from Washington D.C.
***** ANSWER:
Potomac (puh-TOH-mik) River
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       d91a6b99-c6bd-46d5-a2ea-1accd0113d43
     :END:
The shipwreck of the Peter Iredale is visible near the mouth of this
river, which forms the southern and eastern borders of the Colville
Indian Reservation. This river receives flow from the Multnomah Falls
just downstream from the Bonneville Dam within its namesake gorge. The
cities of The Dalles and Astoria border this river, on which the
Franklin D. Roosevelt Lake is located. The Snake River is this river’s
largest tributary, and it is harnessed for hydroelectric power by the
Grand Coulee Dam. Name this chief river of the Pacific Northwest which
forms much of the border between Oregon and Washington.
***** ANSWER:
Columbia River
*** American History: Name these military generals.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       2138e41d-73b1-4c03-9dc0-d95330ae015d
     :END:
The American Expeditionary Forces during World War I were commanded by
this general, nicknamed “Black Jack,” who also led the Punitive
Expedition that sought to capture Mexican revolutionary Pancho Villa
(PAHN-choh VEE-yah).
***** ANSWER:
John Joseph Pershing
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       f77097fb-3496-4177-83f1-4b72762d8d47
     :END:
This general, who was called upon by Herbert Hoover to intervene
against the Bonus Army in 1932, was commander of the U.N. forces that
took part in the Korean War until being controversially replaced by
Matthew Ridgway.
***** ANSWER:
Douglas MacArthur
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       33b9aba3-fbe4-4c76-93bb-1d92b8cb973f
     :END:
Early in his military career, this man served as an aide on the
Braddock Expedition. This commander was victorious at the Battle of
Jumonville Glen, which led directly to an attack against him and his
ultimate surrender at the Battle of Fort Necessity. The Conway Cabal
became opposed to this commander after he lost a series of battles,
including Brandywine, during the Philadelphia Campaign. This leader
encamped his troops at Valley Forge a year after surprising Hessian
troops at the Battle of Trenton. Name this commander-in-chief of the
Continental Army during the Revolutionary War who went on to become
the first U.S. President.
***** ANSWER:
George Washington
** Round Two
*** English / World Literature: Name these British poets.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       32ae53c6-5e78-468e-97dd-c469ee39b2c0
     :END:
What British poet, the author of “When I was One and Twenty” wrote
about being able to “see the cherry hung with snow” in his poem
“Loveliest of Trees”?
***** ANSWER:
Alfred Edward Housman
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       e9c157b1-4668-4256-ac3c-f5425735d33a
     :END:
What other British poet described “happy bells, across the snow” in
his poem “Ring Out”, which is part of a sequence commemorating Arthur
Hallam?
***** ANSWER:
Alfred, Lord Tennyson [or 1st Baron Tennyson]
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       3fdf90e3-53cb-4a4f-940d-f3ed60b8a649
     :END:
This author wrote about seeing his cradled infant Hartley in a poem
that begins by describing how the title phenomenon “performs its
secret ministry unhelped by any wind.” He addressed his “pensive Sara”
at the beginning of a poem about a musical instrument “placed
length-ways in the clasping casement.” This author of “Frost at
Midnight” and “The Aeolian (ee-OH-lee-in) Harp” had one of his works
interrupted by the Person from Porlock. That work is set where “Alph,
the sacred river, ran” and describes a “stately pleasure-dome” in
Xanadu (ZAN-uh-dew). Name this British poet who wrote “Kubla Khan.”
***** ANSWER:
Samuel Taylor Coleridge
*** American Government / Economics: Name these Supreme Court cases.
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       f697656c-0668-4808-a34c-b3dbd694b9e2
     :END:
The ruling from this 1966 case established that during an
interrogation, criminal suspects shall be advised of their rights to
silence and an attorney via a namesake warning.
***** ANSWER:
Ernesto Arturo Miranda v. Arizona [accept Miranda warnings or Miranda rights]
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       0366211a-97a6-4eb0-921c-3c6afaa1b89d
     :END:
The doctrine of judicial review was established in this 1803 case
which stemmed from the sitting Secretary of State’s refusal to deliver
the commission of a man whose appointment was made by John Adams on
the latter’s final day in office.
***** ANSWER:
William Marbury v. James Madison
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       e4db3d09-d378-4742-86aa-5bac9581d8a1
     :END:
In his final appearance before the Supreme Court, former Democratic
presidential nominee John W. Davis argued on behalf of the defense for
this case. The rulings made four years earlier in Sweatt v. Painter
and McLaurin v. Oklahoma State Regents were referenced in the
unanimous opinion for this case. In a subsequent case, the Supreme
Court ruled that its decision must be implemented “with all deliberate
speed.” Thurgood Marshall, while working for the NAACP, argued for the
plaintiffs in this case, which overturned the “separate but equal”
doctrine established in Plessy v. Ferguson. Name this 1954 case which
ruled that segregation in schools was illegal.
***** ANSWER:
Oliver Brown, et al. v. Board of Education of Topeka, Kansas, et. al.
*** Physical Science: Answer the following about the periodic table.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       51099c30-4def-40b0-ba47-07ae9fbfecc8
     :END:
This quantity increases as one moves left and down on the
table. Elements with more energy levels will have a larger value of
this, which is decreased with increased nuclear charge.
***** ANSWER:
atomic radius [or Van der Waals radius; or covalent radius; or ionic radius; prompt on “radius”]
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       386ca5f7-702b-481c-8fb8-f06e73f63ce0
     :END:
This number increases as one moves right on the periodic table, and it
is simply defined as the number of electrons an atom has on its
outermost shell.
***** ANSWER:
valence electrons
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       227e0455-9ff1-49c6-9a40-3e52d619121e
     :END:
Two elements in this group are responsible for M+2 peaks in mass
spectroscopy and can be distinguished from each other based on whether
those peaks are at a 3 to 1 or 1 to 1 ratio. The rarest element in
this group is created through attacking bismuth-209 with alpha
particles. Along with carbon, the lightest of this group of elements
is found in Teflon.  Another element in this group can be used to test
for starch. The two lightest elements of this group form diatomic
gases at STP, while another is the only nonmetal to be liquid at room
temperature. Name these group (*) 17 elements which include iodine,
chlorine, and fluorine.
***** ANSWER:
halogens [accept group 17 befor]
*** Geography: Name these South American nations.
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       7ac22759-515a-4ed8-98d8-ec0b3f381005
     :END:
The Rio Negro bisects this nation before flowing into a namesake
river, that then empties into the Rio de la Plata estuary along this
nation’s southern border.
***** ANSWER:
Oriental Republic of Uruguay (YOOR-uh-gway) [or Republica Oriental del Uruguay]
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       75ddc342-c2ba-4f92-8849-f4c4e58cc2de
     :END:
The Gulf of Guayaquil (GWY-ah-keel) takes its name from the most
populous city in this nation within the Andes Mountains that controls
the Galapagos Islands.
***** ANSWER:
Republic of Ecuador [or Republica del Ecuador]
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       d898b565-b268-4271-b5b4-50ddd625d811
     :END:
This nation borders a series of straits known as the Dragon’s
Mouths. The southeast portion of this nation contains Canaima National
Park, which is dominated by mesa-like formations known as tepuis
(TAY-pweez). This nation controls the Tablazo Strait and a body of
water that sees frequent lightning strikes at the mouth of the
Catatumbo River.  Its longest river, the Orinoco, receives the water
that flows through this nation’s Angel Falls, which is the highest
waterfall in the world. The island nation of Trinidad and Tobago is
just off the coast of what country which controls Lake Maracaibo and
has its capital at Caracas (kah-RAH-kahs)?
***** ANSWER:
Bolivarian Republic of Venezuela [or Republica Bolivariana de Venezuela]
*** American History: Name the following things related to the Cold War.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       648d6e7b-1c10-46e9-b85e-2c504e532858
     :END:
Operation Vittles was the codename for this eleven month event in
which the U.S. and its allies flew in supplies to a certain city after
all of its land accesses were blocked in 1948 by the Soviet Union.
***** ANSWER:
Berlin airlift
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       35cdb18d-9e11-4dda-951d-9711b6f679d4
     :END:
Michael Collins and “Buzz” Aldrin were two of the three members of
this NASA space mission that fulfilled the “Space Race” goal of being
the first to land a man on the moon.
***** ANSWER:
Apollo 11 [prompt on “Apollo”]
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       7dfb72dc-b327-4c35-be59-ecc12606a397
     :END:
It was revealed in 2002 that Vasili Arkhipov played a large role in
preventing escalation during this event. Soviet spy Alexander Feklisov
acted as a negotiator during this event, which prompted the creation
of group known as ExComm.  This event occurred in response to actions
taken during Operation Anadyr, and Rudolf Anderson was killed while
flying a U-2 spy plane during this event. A hotline between Washington
D.C. and Moscow was created in response to this event, which was ended
when the U.S. agreed to remove Jupiter MRBM’s from Italy and
Turkey. Name this 1962 event in which the U.S. set up a blockade after
discovering Soviet nuclear weapons on a certain (*) Caribbean island.
***** ANSWER:
Cuban missile crisis [accept October crisis or The Missile Scare; accept Caribbean crisis before (*)]

** Round Two
*** English / World Literature: Name the following related to East Asian literature.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       382659bb-4b87-4f7b-9b82-c7436d9475a7
     :END:
What work by Lady Murasaki (MUR-uh-sah-kee), sometimes considered to
be the first novel, is a depiction of classical Japanese court life?
***** ANSWER:
The Tale of Genji or [Genji monogatari]
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       284d8a9a-ba0a-4da5-993b-da81c97e1333
     :END:
Zeami (zay-AHM-ee) is considered to be a practitioner of what medieval
Japanese art form, which emphasizes a slow, stylized performance and
actors with masks?
***** ANSWER:
noh [or nogaku or noh drama or noh play or noh theater]
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       07e1e23e-30df-4dd0-969f-b9670a10dce0
     :END:
In this work, a character causes fiery bricks to fall from heaven,
leading to the creation of Flaming Mountain. A group of characters in
this work make a pilgrimage to Vulture Peak. This novel’s main
character was born from a magic stone infused with the power of heaven
on top of a mountain. This novel’s characters include Pigsy, Sandy,
and Sun Wukong, who sometimes provides the alternate name of this
novel, (*) Monkey. Name this novel, one of the four Chinese classics,
which is named for a voyage to India.
***** ANSWER:
Journey to the West [or Xi You Ji or Hsi-yu chi; prompt on “Adventures
of the Monkey God” or “Monkey to the West” or “The Adventures of
Monkey”; prompt on “Monkey” before (*)]
*** American Government / Economics: Name these current U.S. governors.
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       d2af5422-f351-4a11-b95a-77f06032e294
     :END:
Raised as Sikh, this Indian-American woman and youngest current
governor has served as South Carolina’s Governor since succeeding Mark
Sanford in 2011.
***** ANSWER:
Nimrata Nikki Randhawa Haley
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       39d9381a-d121-402e-a67f-1e691286eb79
     :END:
This other Indian-American, who has served as the Governor of
Louisiana since 2008, made headlines in January 2015 for criticizing
Western European governments for allegedly allowing Muslim-controlled
“no-go zones.”
***** ANSWER:
Piyush “Bobby” Jindal (JIN-dul)
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       068ea81f-663a-4d9f-a094-8a54f5d496fc
     :END:
In 2011 this governor pulled his state out of the environmental
organization Regional Greenhouse Gas Initiative.  Shortly before being
re-elected as governor over Barbara Buono, he authorized over ten
million dollars to be spent on a special election to fill the seat
left by deceased U.S. Senator Frank Lautenberg, which was won by Cory
Booker. In January 2015 he was criticized for accepting all-expense
paid trips to several Dallas Cowboys football games. This governor was
embroiled in a 2013 scandal in which members of his staff were
involved in the closure of traffic lanes that provided residents of
Fort Lee access to the George Washington Bridge. Name this current
Governor of New Jersey.
***** ANSWER:
Christopher James Christie
*** Physics: This set of questions will deal with the nature of light.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       57ad698a-14ca-42a1-9fba-abb631e21ce5
     :END:
Since light behaves like a wave at times, it will often exhibit what
phenomenon, in which waves superpose to create a new wave with a
different amplitude?
***** ANSWER:
interference [accept word forms]
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       2e053867-515b-41e1-a652-aa7d54ea9d3a
     :END:
What physicist used a “grating” to conduct the double-slit experiment,
in which he showed that light behaves like a wave and a particle?
***** ANSWER:
Thomas Young
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       4d92b78b-87e5-4c7c-9d50-cd02e96cdb1f
     :END:
Mantis shrimp are one of the few species that can detect light with
this property. Dichroism (DYE-cro-ism) induced by light with this
property is commonly used in a form of spectroscopy that examines the
secondary structure of proteins. Light with a related planar property
can be turned into light with this property by using a quarter
wave-plate.  Like its “linear” counterpart, the intensity of light
that has this property is given by Malus’ (MAL-iss-iz) law. Name this
property of light, in which its electric field oscillates in a
corkscrew fashion.
***** ANSWER:
circular polarization [accept word forms, prompt on “polarization”]
*** Geography: Name these mountain ranges.
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       77f64657-ecfb-451f-9e27-80fd3c8f1285
     :END:
The Novaya Zemlya (NOH-vuh-yuh zem-lee-YAH) archipelago is a northern
extension of this mountain range that lies along the continental
border that splits Russia into European and Asian sides.
***** ANSWER:
Ural Mountains [or Urals or Uralsky Khrebet]
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       6cb3c81e-8f3f-4da6-9c3e-ac8490094ad5
     :END:
Mont Blanc is the highest peak in this European mountain range that
dominates the geography of Switzerland and western Austria.
***** ANSWER:
Alps [accept Alpine Mountains]
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       114184ef-21e1-459b-9f70-fce519c70b0f
     :END:
Longs Peak is one of most notable features within this mountain
range’s namesake national park. This range is at the west end of the
Laurentian Divide, and one part of this range is traversed by the
Icefields Parkway, which runs north from Lake Louise into Jasper
National Park. The Sawatch [suh-“WATCH”] and Bitterroot Ranges are
sub-ranges of these mountains, which include both Mount Elbert and
Pikes Peak. These mountains contain the world’s largest concentration
of geysers within Yellowstone National Park. Name this North American
mountain range which runs from British Columbia to New Mexico.
***** ANSWER:
Rocky Mountains or Rockies [accept Canadian Rocky Mountains or Canadian Rockies]
*** American History: Name these battles of the Civil War.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       1b88214e-2f69-4aad-9c25-bb054beab583
     :END:
Joseph Hooker was defeated by Robert E. Lee at this May 1863 battle
best remembered as the battle at which “Stonewall” Jackson was wounded
by friendly fire, ultimately leading to his death.
***** ANSWER:
Battle of Chancellorsville
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       7794a4e8-e59e-4b83-87ee-4bc7e638cd2e
     :END:
The Union Army regained control of the Mississippi River with Ulysses
Grant’s victory at this nearly two month long battle, which was ended
when John Pemberton surrendered on July 4th, 1863.
***** ANSWER:
Battle of Vicksburg or Siege of Vicksburg
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       76ea8615-8566-45a8-86a4-e833f54da3d2
     :END:
One commander at this battle located his headquarters at the Philip
Pry House. This skirmish was preceded by the Battle of South Mountain,
and A.P. Hill arrived at this battle with reinforcements following the
Confederate victory two days earlier at the Battle of Harpers
Ferry. Prior to this skirmish, Union soldier Barton Mitchell
discovered the Confederate battle plans, known as Special Order 191,
wrapped around three cigars. Fighting locations at this battle
included the “Bloody Lane” and “Burnside’s Bridge.” The result of this
battle prompted Abraham Lincoln to announce the Emancipation
Proclamation. Name this single-day bloodiest battle of the Civil War
in which George McClellan halted Robert E. Lee’s advance into
Maryland.
***** ANSWER:
Battle of Antietam (an-“TEE”-tum) [or Battle of Sharpsburg]

** Round Two
*** English / World Literature: Give the following related to lunar references in works of literature.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       2d1c37fe-be53-46f8-a384-7d9d8b2f19e8
     :END:
From the Earth to the Moon is one of the many science fiction novels
in which what author depicts journeys to the moon?
***** ANSWER:
Jules Gabriel Verne
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       1d231027-1965-4603-8d9b-a037d214325a
     :END:
What author of Comical History of the States and Empires of the Moon
is better known for appearing in a 19th century play in which he
secretly loves Roxane?
***** ANSWER:
Hercule-Savinien Cyrano De Bergerac
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       d9736766-46ca-4815-830d-a5dd148b8ca1
     :END:
The oldest piece of prose in this country’s literary tradition
describes a girl that is found in a plant leaf as a youth and raised
by human foster-parents before becoming Princess of the Moon. A
novelist from this country wrote about an old man, who visits an
establishment in which all of the young girls have been drugged, in
the novella The House of the Sleeping Beauties. That author from this
nation also wrote Snow Country, which is set in a hot springs town, or
onsen.  Name this country that was home to the writer Yasunari
Kawabata.
***** ANSWER:
Japan [or Nihon-koku or Nippon-koku]
*** American Government / Economics: Name the following related to the economics of living.
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       7c2cd709-74ea-4fa2-b21a-8a32fd67bdcb
     :END:
The Case-Shiller metric is an example of what measure of the cost of
living, which is calculated for a “basket of goods”?
***** ANSWER:
consumer price index or CPI
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       56469b08-2ae7-4d30-b0d5-d193818346fe
     :END:
What economic variable in the cost of living is often controlled
through the use of namesake price ceilings? For a business, this cost
is often tax-deductible.
***** ANSWER:
rent
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       d96151c0-3067-48bd-a762-7fb5623004f0
     :END:
The golden rule of this quantity is used to figure out what is the
ideal macroeconomic level of it for growth. This quantity, which is
the S in the IS-LM model, is the upper bound on the so-called “reserve
ratio”, which is defined as the amount of money the Federal Reserve
mandates that banks keep on hand. A financial institution that
specializes in mortgages is called a “[this] and loan bank”. Accounts
named for this quantity feature a rate of return that ideally beats
the inflation rate. Name this quantity, which is defined as the
portion of income one keeps for future use.
***** ANSWER:
savings rate
*** Physical Science: Name these acids.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       b1fd7f04-296d-410e-896c-7973925c5f51
     :END:
This strong acid, which was called oil of vitriol in antiquity, is
made by the lead chamber and contact processes.
***** ANSWER:
sulfuric acid [or H2SO4]
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       1cc9fa5c-b978-412f-ad7a-1b75c068d8ec
     :END:
This other strong acid, which is formed from the Ostwald process, can
come in red and white fuming varieties.
***** ANSWER:
nitric acid [or HNO3]
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       ae7154ce-5471-48b6-a64e-0e3ccc19699f
     :END:
A “trifluoro” derivative of this acid is used in reverse phase HPLC to
increase resolution. When combined with sodium bi·carbonate, this acid
reacts to form short-lived carbonic acid as one of its products. If no
water is present in a solution of this acid, it is termed “glacial.”
An outdated process for synthesizing this acid makes use of a catalyst
containing rhodium, and that process was supplanted by one that uses
an iridium catalyst; both of those processes add a carbonyl group to
methanol. This acid is made through the Monsanto and Cativa
processes. Name this carboxylic acid, which is found in low
concentrations in vinegar.
***** ANSWER:
acetic (uh-SEE-tik) acid [or ethanoic acid or CH3COOH or CH3CO2H or C2H4O2]
*** Geography: Name these islands.
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       4e3dbf58-b73f-42bf-b7b4-ba4874a2e8e0
     :END:
The Mona Passage separates Puerto Rico from this Caribbean island that
contains the nations of Haiti and Santo Domingo.
***** ANSWER:
Hispaniola (hih-span-YOH-lah) [or La Espanola]
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       21198d0b-44e9-45f8-8c49-77b2238e3c32
     :END:
The Strait of Malacca separates the Malay Peninsula from this largest
all-Indonesian island whose most populous city is Medan.
***** ANSWER:
Sumatra [or Sumatera]
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       2d732e24-9e5f-41f2-a61f-f9a64fd7891c
     :END:
The remains of a human known as the Cheddar Man were discovered in a
namesake gorge on this island. To the northwest of this island is a
strait known as The Minch, and the western terminus of its Penwith
Peninsula is known as “Land’s End.” The body of water directly east of
this island has a shallow area known as Dogger Bank. Ben Nevis is the
highest mountain on this island, which is directly south of the Orkney
Islands. The Severn is the longest river on this island, which the
Strait of Dover separates from France. The River Thames (temz) flows
through the most-populous city on what largest European island which
is directly east of Ireland?
***** ANSWER:
Great Britain [do not accept or prompt on “United Kingdom,” “England,” “Scotland,” or “Wales”]
*** American History: Name these events in which many people were killed.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       3e5bd215-876a-4d5d-b7b7-a1853243ac78
     :END:
Several hundred members of the Lakota tribe were killed during this
1890 skirmish which began after an attempt to disarm a Lakota man
named Black Coyote led to the discharge of a rifle.
***** ANSWER:
Wounded Knee Massacre [or Battle of Wounded Knee Creek or Chankpe Opi Wakpala]
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       8f1b12bf-61f6-4f33-b245-1fc555e0fb4e
     :END:
Thirty-six people were killed in this 1937 incident in Lakehurst, New
Jersey that prompted reporter Herbert Morrison, whose news team was
recording at the time, to exclaim “Oh the humanity!”
***** ANSWER:
Hindenburg disaster [accept Hindenburg explosion or other equivalent answers that mention Hindenburg]
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       74430e1e-2f83-4617-8910-b9a83a1aec78
     :END:
The remains of many of those killed during this event were first
discovered at the Fresh Kills landfill. Operation Yellow Ribbon was
initiated in response to this event, which was the subject of an
investigation by a group headed by Thomas Kean. One casualty of this
event was Todd Beamer, who spoke the phrase “let’s roll” shortly
before being killed outside of Shanksville, Pennsylvania. This event
was chiefly planned by Khalid Sheikh Mohammed (kah-LEED “shake”
moh-HAH-med), and it led directly to passage of the PATRIOT Act. Name
this 2001 event in which al-Qaeda (al-KYE- duh) terrorists flew
airplanes into the Pentagon and World Trade Center towers.
***** ANSWER:
9/11 attacks [accept equivalents such as September 11th attacks or
more specific equivalents such as the World Trade Center attacks]

** Round Two
*** English / World Literature: Name these European authors.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       0228d74f-0a6f-4df2-bd8f-9dfe7daa110f
     :END:
What Czech author never finished his novel about K., who tries to
enter the title structure, titled The Castle?
***** ANSWER:
Franz Kafka [or Franz Anschel]
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       617220f1-b0e9-43d4-aa1c-11d764dd1f09
     :END:
What Czech author wrote about Tomas and Teresa, who live during the
Prague Spring, in The Unbearable Lightness of Being?
***** ANSWER:
Milan Kundera
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       d66d909f-be6d-4fbf-920f-a83957412e9a
     :END:
This author adapted Arthur Schnitzler’s (SHNITZ-lurz) play The Distant
Land into his own play The Undiscovered Country. The events that lead
to the Russian Revolution are the subject of his three plays Voyage,
Shipwreck, and Salvage. In another play by this author, the title
characters and the Tragedians (tra-juh-DEE-unz) hide in barrels while
pirates attack their boat. In that play by this author, the two title
characters perform The Murder of Gonzago after flipping a coin 92
times and seeing it land on heads every time. Name this author of
Rosencrantz and Guildenstern are Dead.
***** ANSWER:
Tom Stoppard [or Tomáš Straussler]
*** American Government / Economics: Name these Cabinet-level positions
**** Team A:                                                          :drill:
     SCHEDULED: <2018-11-26 Mon>
     :PROPERTIES:
     :ID:       0d2319cb-c04f-4090-b7df-926dde8baa57
     :DRILL_LAST_INTERVAL: 4.0
     :DRILL_REPEATS_SINCE_FAIL: 2
     :DRILL_TOTAL_REPEATS: 2
     :DRILL_FAILURE_COUNT: 1
     :DRILL_AVERAGE_QUALITY: 2.0
     :DRILL_EASE: 2.5
     :DRILL_LAST_QUALITY: 4
     :DRILL_LAST_REVIEWED: [2018-11-22 Thu 15:58]
     :END:
In 2014, former Kansas Governor Kathleen Sibelius resigned from this
position, which led to the appointment of its current holder, Sylvia
Burwell.
***** ANSWER:
Secretary of Health and Human Services or Health and Human Services Secretary [prompt on “HHS”]
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       3ec9ccf5-9ed4-4840-9564-d3a5d23e02f2
     :END:
A 2014 scandal led to Eric Shinseki’s resignation of this office,
which was the most recent to be added as a Cabinet level position
until the 2001 creation of the Department of Homeland Security.
***** ANSWER:
Secretary of Veterans Affairs or Veterans Affairs Secretary [prompt on “VA”]
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       437f93c4-1906-497f-bede-ac8461c6c123
     :END:
In 1989 the U.S. Senate denied the appointment of John Tower to this
position. Charles Wilson was pressured to resign as CEO of General
Motors after being nominated for this position, which was first held
by a man who is presumed to have committed suicide by jumping out of a
hospital window. Caspar Weinberger held this office under Ronald
Reagan until his resignation amid the Iran-Contra Affair. This
position was held two separate times, twenty-four years apart, by
Donald Rumsfeld, and its longest holder was Robert McNamara. In 2015,
Chuck Hagel was replaced by Ashton Carter in what Cabinet-level office
that was created in 1947 to replace the position of Secretary of War?
***** ANSWER:
Secretary of Defense [accept Defense Secretary; prompt on “SecDef”; do
not accept or prompt on “Secretary of War”]
*** Physics: Questions in this category will deal with the physics of momentum transfer.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       e8403949-c27e-4fa6-94db-8d5ac69c398a
     :END:
What quantity, which is given as the time integral of force, is
defined as the vector change in an object’s linear momentum?
***** ANSWER:
impulse
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       45637288-7abe-4512-8264-0d0062b2e0a0
     :END:
For a two object system, this property of a system does not change in
a collision since momentum is always conserved. For a rigid body, this
property is the centroid.
***** ANSWER:
center of mass [do not accept “center of gravity”]
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       5333eea3-1ba8-4caa-8273-1c80adb183ce
     :END:
The maneuvers of these objects can be mathematically expressed by the
Tsiolkovsky (SEAL-koff-skee) equation, which is derived by the
conservation of momentum. Robert Forward proposed a specific type of
this object known as a fission sail. These objects can have their
momentum altered via staging, in which their excess weight is shed.  A
theory relating to these objects was outlined in A Method of Reaching
Extreme Altitudes by Robert Goddard. Typically, they use liquid or
solid fuel to provide thrust. Name these spacecraft which have engines
that eject propellant and were studied by Wernher von Braun (VAIR-err
vahn brahn).
***** ANSWER:
rockets
*** Geography: Name these Asian nations.
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       0d122c77-dbdb-4fc4-86ed-7bbe92f3f896
     :END:
This country’s exclave of Musandam borders the south side of the
Strait of Hormuz, which is at the west end of a gulf named after this
nation.
***** ANSWER:
Sultanate of Oman [or Saltanat Uman]
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       7b438a9d-0f81-4318-9ffb-6ed056b09ab8
     :END:
This nation, which contains Lake Balkhash, is the world’s largest
landlocked nation.
***** ANSWER:
Republic of Kazakhstan (KAH-zak-STAN) [or Qazaqstan Respublikasy]
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       a09c10aa-188d-4102-baae-6a1a0ff4fce0
     :END:
The eastern part of this nation is dominated by the Khorat
Plateau. Many tourists to this nation flock to the island of Phuket,
and its capital, which houses royalty in the Grand Palace, is located
on the Chao Phraya (“chow” PRY-uh) River. With its western neighbor,
this nation shares the Isthmus of Kra, which borders the Andaman Sea
and a gulf sharing its name with this country. This nation is at the
south end of the opium-production area known as the Golden Triangle,
which also includes the nations of Laos (“louse”) and Burma. Siam was
the former name of what Southeast Asian nation whose capital is
Bangkok?
***** ANSWER:
Kingdom of Thailand [or Prathet Thai or Ratcha Anachak Thai]
*** American History: Name these events that took place during the colonial era.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       99a64916-24ff-41d8-ac9a-46809c719d4f
     :END:
Accusations by Abigail Williams and Betty Parris helped lead to this
1692 event which resulted in the execution of Giles Corey, who
continuously asked for “more weight” during the process of being
pressed to death.
***** ANSWER:
Salem witch trials (prompt on partial answer)
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       6d9407e1-11ad-465b-83d2-12fd095ca129
     :END:
Colonial Governor William Berkeley’s failure to protect against Native
American attacks played a part in the start of this 1676 rebellion
which resulted in Jamestown, Virginia being burned to the ground.
***** ANSWER:
Bacon's Rebellion
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       62ba839a-6390-4785-bc43-20730642326b
     :END:
One trial in the aftermath of this event was impacted by the testimony
of Dr. John Jeffries, who relayed the deathbed testimony of Patrick
Carr. An investigatory committee headed by James Bowdoin (BOH-din) was
established after this event, which stemmed from a disagreement over a
wigmaker’s bill. Hugh Montgomery and Matthew Kilroy were convicted of
manslaughter and branded following this event. Eight soldiers are
shrouded in smoke on the right side of a notable engraving of this
event created by Paul Revere. John Adams defended the British soldiers
accused of murdering Crispus Attucks and four others in what 1770
event that occurred in the capital of Massachusetts?
***** ANSWER:
Boston Massacre [accept Incident on King Street]

** Round Two
*** English / World Literature: Give the following related to illustrators of English literature.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       0bcdd5d5-2f01-4e7c-8dad-c8dbb0d90ecf
     :END:
Hablot Browne illustrated the novels of what author, whose works
include Martin Chuzzlewit and Bleak House?
***** ANSWER:
Charles John Huffam Dickens
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       ab1642df-cfb4-43dc-9960-99b59c9d56d7
     :END:
John Tenniel illustrated what Lewis Carroll novel, whose characters
included the Red Queen and Tweedledum?
***** ANSWER:
Through the Looking Glass, and What Alice Found There
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       d1526326-0a0f-49f9-9c02-5881de6ec59e
     :END:
At the end of this story, which was illustrated by Sidney Paget
(PUH-jay), a sea-battered stern post with the letters “L.S.” painted
on it is discovered. This story is told through the character of John
Openshaw, who describes how his Uncle Elias is a former colonel that
is given an envelope with the title objects; that envelope causes him
to burn some secret papers and pace frantically before he is found
dead in his own pool. Name this short story in which Sherlock Holmes
deduces that a boat captain and his two mates are members of the
K.K.K. and thus responsible for two murders.
***** ANSWER:
“The Five Orange Pips”
*** American Government / Economics: Name these current U.S. Senators.
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       497b03ec-f984-40a1-9ed8-e3137de63f0f
     :END:
The most senior member of the Senate is this Democrat from Vermont who
was replaced as president pro tempore in January 2015.
***** ANSWER:
Patrick Joseph Leahy (LAY-hee)
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       c92d3ab6-920f-4447-91d7-5e94fdd0bae8
     :END:
This woman, who became Mayor of San Francisco following the 1978
assassination of George Moscone and Harvey Milk, is currently the
senior Senator from California.
***** ANSWER:
Dianne Goldman Berman Feinstein [or Dianne Emiel Goldman]
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       a373ca41-b8de-4707-8aa6-43d5f3ca6ad2
     :END:
This politician first entered the Senate by winning an election
against Richard Kimball. In September 2014, this Senator battled
rumors that he met and took a photograph with ISIS leader Abu Bakr
al-Baghdadi (AH-boo BAH-kur ahl- bahg-DAH-dee). Early in his career,
this Senator was cleared of wrongdoing after becoming embroiled in a
scandal involving Charles Keating. The memoir Faith of My Fathers
recounted the military service of this man, who co-authored a 2002
campaign finance reform law with Russ Feingold. More recently, this
Senatorial successor to Barry Goldwater ran for president on a ticket
with Sarah Palin. The loser to Barack Obama in the Election of 2008
was what former Vietnam War POW and current Senator from Arizona?
***** ANSWER:
John Sidney McCain III
*** Physical Science: Answer the following about iron.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       f46d1b58-6a25-46fe-994d-49723be4d177
     :END:
Iron is the main component of steel, which is made through this
process that creates steel out of pig iron.
***** ANSWER:
Bessemer process
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       56ffc75e-fc7c-44c0-98fd-92264abef330
     :END:
To prevent iron from rusting, one can perform galvanization on it,
which means plating the iron with this other element.
***** ANSWER:
zinc
**** Tossup:                                                          :drill:
     SCHEDULED: <2018-11-26 Mon>
     :PROPERTIES:
     :ID:       e66914d4-a3f9-4dd5-8bbe-64f79b164171
     :DRILL_LAST_INTERVAL: 3.86
     :DRILL_REPEATS_SINCE_FAIL: 2
     :DRILL_TOTAL_REPEATS: 1
     :DRILL_FAILURE_COUNT: 0
     :DRILL_AVERAGE_QUALITY: 3.0
     :DRILL_EASE: 2.36
     :DRILL_LAST_QUALITY: 3
     :DRILL_LAST_REVIEWED: [2018-11-22 Thu 16:01]
     :END:
An iron-containing chemical named after this color is used medically
to remove cesium and thallium from the body. A compound named after
this color is used to treat methemo·globinemia. In a Bradford assay,
solutions that contain protein will turn into this color; the reagent
used in Bradford assays is a dye called Coomassie brilliant. A
solution of copper in water turns this color. An iron-containing
pigment is called the Prussian type of this color. In gaseous and
liquid phases, ozone has this color. An indicator named after this
color is called bromo·thymol. Name this color that litmus paper turns
into when dipped into a basic solution.
***** ANSWER:
blue
*** Geography: Name these U.S. states.
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       ab95d21b-09a7-49a6-825a-21ab50d292bf
     :END:
Fort Pulaski National Monument is within this state, which has part of
its western border former by the Chattahoochee River.
***** ANSWER:
Georgia
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       5475a178-6152-4357-adfc-1b6040606ebc
     :END:
Most of prehistoric Lake Bonneville was located within the existing
boundaries of this state, which contains both Capital Reef and
Canyonlands National Parks.
***** ANSWER:
Utah
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       ff9e10b9-ad67-4a80-b78a-080ea1cf0451
     :END:
The Chena Hot Springs are found within a resort in this state, in
which much of the Kobuk River Valley is protected before emptying into
the Kotzebue Sound. This state controls Little Diomede (DY-uh-meed)
Island, and in 1964 the Good Friday Earthquake led to the relocation
of its city of Valdez (val-DEEZ), which receives an oil pipeline that
originates in Prudhoe Bay and crosses the Brooks Range. Prince William
Sound and Kodiak Island are off the southern coast of this state,
which is bisected by the Yukon River. Mount McKinley is the highest
point in what northernmost U.S state whose capital is Juneau?
***** ANSWER:
Alaska
*** American History: Name these things related to the American West.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       3f3a41c5-f73b-4cdd-85dc-bf85428909dc
     :END:
San Antonio, Texas and Abilene, Kansas were at either end of this 19th
century trail used primarily by cowboys for the transportation of
cattle.
***** ANSWER:
Chisholm (CHIZ-um) Trail
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       e9cf5373-f047-4225-aa83-857942f9679e
     :END:
Much of the American West was settled due to the provisions of this
1862 legislation which provided 160 acres for free to individuals
willing to improve and live on the land for five years.
***** ANSWER:
Homestead Act of 1862
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       6aa51bfc-c0f7-4ca6-b031-f212dd6df480
     :END:
Jack Walton was impeached while serving as the governor of this
state. Sarah Page and Dick Rowland were involved in an elevator
incident that triggered a 1921 race riot in this state, part of which
was the site for the proposed state of Sequoyah. Before achieving
statehood, much of its Unassigned Lands were settled by the Land Rush
of 1889. The Alfred P. Murrah Federal Building was located in this
state until it was bombed by Terry Nichols and Timothy McVeigh.  The
terminus of the Trail of Tears led to the settlement of the Indian
Territory that went on to become this state. Name this plains state
north of Texas which contains Tulsa and a namesake capital city.
***** ANSWER:
Oklahoma

** Round Two
*** English / World Literature: Answer the following about authors who wrote epic poems.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       e5fb7086-71b6-4443-8227-01192b12eb7b
     :END:
The Shield of Heracles and Works and Days are epic poems by what Greek
author, who described the origin of the gods in Theogony
(THEE-odj-uh-nee)?
***** ANSWER:
Hesiod
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       1260bda9-b176-4555-98bb-cc228925b3ec
     :END:
Apollonius Rhodius (APP-uh-loh-nee-us ROE-dee-us) wrote an epic poem
about what object from Greek mythology that was used in a journey from
Iolcus (EE-oll-cuss) to Colchis (KOLL-chiss) to acquire an item
possessed by King Aeetes (“eye”-EE-teez).
***** ANSWER:
Argo
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       1776066d-1ea6-48e7-a448-14f5299cf0cd
     :END:
This man wrote an epic poem about “The Death and Judgment of the
Eternal Man” that is named for Tharmas (TAR-muss), Luvah (LOO-vuh),
Urizen (YUR-ee-zen), and Urthona (UR-thoe-nuh). This author of The
Four Zoas wrote a shorter poem that begins “I was angry with my
friend; I told my wrath, my wrath did not end.” That poem ends with
the speaker seeing his foe outstretched beneath the title
plant. Another poem, which appears in the same collection as the
previous one, describes an “invisible worm, that flies in the night.”
Name this author whose poems “A Poison Tree” and “The Sick Rose”
appear in Songs of Innocence and Experience.
***** ANSWER:
William Blake
*** American Government / Economics: Name these Articles of the Constitution.
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       84624ef7-baf6-4243-9e95-f7c2086efbab
     :END:
The “Full Faith and Credit” clause is mentioned within this Article,
which notes that the Federal government will guarantee every state a
republican form of government and protect them against invasion.
***** ANSWER:
Article Four or 4th Article
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       4c94e042-2878-4fff-824f-e726bd10ec9d
     :END:
This Article specifies that the Constitution must be ratified by nine
of the original thirteen states in order to become valid.
***** ANSWER:
Article Seven or 7th Article
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       c62d8327-8786-4b1b-a840-407f724766e3
     :END:
The Constitution’s Recommendation Clause is within this Article, which
notes how care shall be taken to ensure “that laws be faithfully
executed.” The text of this Article, which addresses who can negotiate
treaties and appoint ambassadors, was revised by both the 25th and
12th Amendments. Command over the U.S. Armed Forces is granted within
this Article, which also requires a regular State of the Union
address. The requirements and powers of the U.S.  President are
outlined in what Article of the Constitution which follows the Article
describing the government’s legislative branch?
***** ANSWER:
Article Two or 2nd Article
*** Physical Science: Name these types of chemicals.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       57b875b5-6589-4306-b962-ae0de00ddd89
     :END:
This type of solution is made of two liquids that cannot be separated
by distillation. An example of one is 95% ethanol in water.
***** ANSWER:
azeotropes
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       7e2c8522-1f04-42a9-899b-ccb50843c1bc
     :END:
Another liquid/liquid mixture is this type of colloid, examples of
 which include mayonnaise and milk.
***** ANSWER:
emulsions
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       68203107-bc3c-4ed8-9971-3b6b6f1aef7c
     :END:
One type of this substance contains a carbon-nitrogen double bond,
with the nitrogen bound to an R group. That type of this substance is
named after (*) Schiff. Along with being a strong nucleophile, n-butyl
lithium is one of the strongest examples of this type of chemical. In
the inductive effect, the strength of these substances is increased by
nearby electropositive groups, such as in guani·dinium. In the
Henderson-Hasselbalch equation, the numerator of the log term is the
conjugate type. They donate electron pairs according to Lewis theory,
and most strong types lose a hydroxide in solution. Name these
chemicals with a pH greater than 7.
***** ANSWER:
bases [or Lewis bases; or Bronsted-Lowry bases; or Arrhenius bases;
accept imine until (*)]
*** Geography: Name these Canadian province or territories.
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       53def815-571a-4745-a2ea-7d54ed1d3b28
     :END:
The Klondike Gold Rush occurred in this territory, which borders
Alaska and has its capital at Whitehorse.
***** ANSWER:
Yukon Territory
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       72ecae56-da3f-4d6a-9d46-1e7dddde9b03
     :END:
The St. Lawrence River flows past the city of Montreal within this
province, which has been the subject of an organized sovereignty
movement since the late 1960s.
***** ANSWER:
Quebec
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       1af5dbb9-b3bc-4c0e-b135-f94a4935fe9d
     :END:
The Coast Salish (SAY-lish) people are Canadian aboriginals native to
this province. This province borders the Queen Charlotte Strait and
contains Kootenay and Yoho National Parks on its eastern
border. Whistler is a popular winter sports resort town in this
province, and its most populous city is situated at the mouth of the
Fraser River. The capital of this province is on an island separated
from the mainland by the Strait of Georgia; that island shares its
name with its most populous city, which hosted the 2010 Winter
Olympics. Name Canada’s westernmost province, which has its capital at
Victoria and contains the city of Vancouver.
***** ANSWER:
British Columbia [prompt on “BC”]
*** American History: Give the following related to notable speeches.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       0daf8369-81ba-45b5-8220-c981335002a2
     :END:
While speaking at the 1896 Democratic National Convention prior to
gaining the Presidential nomination, this politician delivered the
“Cross of Gold” speech to advocate against the gold standard.
***** ANSWER:
William Jennings Bryan
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       32f59fd0-065a-4961-8e4b-658410dd4eb6
     :END:
After being elected as President on a ticket featuring John Nance
Garner, this New Yorker noted in his first inaugural address that “the
only thing we have to fear is…fear itself.”
***** ANSWER:
Franklin Delano Roosevelt [or FDR; prompt on “Roosevelt”]
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       db1ccd94-bd82-41aa-8e69-07d47bd2949c
     :END:
One speech given prior to this event included a recitation of the
Pericles quote “the whole earth is the sepulchre (SEP-uhl-ker) of
illustrious men.” The services of secretaries John Nicolay and John
Hay were utilized on the day of this event, which included a statement
that “the world will little note, nor long remember, what we say
here.” A two hour speech by Edward Everett preceded this event, which
referenced a “new nation, conceived in liberty, and dedicated to the
proposition that all men are created equal.”  Beginning with the words
“four score and seven years ago,” name this speech given in 1863 by
Abraham Lincoln to honor those who died in a namesake Civil War battle
in Pennsylvania.
***** ANSWER:
Gettysburg Address

