*** English / World Literature: In this set of questions, you will name writers who wrote about alchemy.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       a484851e-0998-4ba3-9dc8-f23bb78217dd
     :END:

What writer, the husband of Elizabeth Barrett, wrote about an
alchemist who contemplates his achievements in Paracelsus
(“PAIR”-uh-SELL-suss)?
***** Answer
Robert Browning 
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       eb39d039-600e-4891-ae67-9c6b5ff0fba6
     :END:
What author, the wife of Percy, wrote about a scientist named Victor
who creates a monster through assemblages and alchemy?
***** Answer
Mary Wollstonecraft Shelley
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       e4ab1f80-c0ee-4d33-a622-0cb0e0c8b567
     :END:
This writer wrote a story about a canon who tricks a clergyman into
thinking mercury can be alchemized into quicksilver. Another story by
this writer concerns a fox getting outwitted by a proud cock named
Chauntecleer (CHAWN- tih-“clear”). In another story by this author,
Nicholas farts into the face of Absolon (ab-SO-lawn), who then uses a
red hot poker to singe Nicholas’ rear end. All of those stories by
this author appear in a collection that opens with a General Prologue
in which pilgrims stay at the Tabard Inn. Name this medieval English
author who included “The Miller’s Tale” as one of his many Canterbury
Tales.
***** Answer
Geoffrey Chaucer

*** English / World Literature: Name the following related to William Shakespeare.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       72b7e3be-f1b7-4813-9be0-7f1c0245cc94
     :END:
Antonio is the title character of what play by William Shakespeare
that includes a moneylender named Shylock?
***** ANSWER:
The Merchant of Venice
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       5eecde9f-c003-495e-bf04-9a7d94e0542f
     :END:
What play by William Shakespeare includes Goneril [GAHN-er-uhl] and
Regan, who are two ungrateful daughters of the title character?
***** ANSWER:
The Tragedy of King Lear
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       91097654-48d0-4a4d-9afc-5c1a07580309
     :END:
This writer imagined a fictional sister of William Shakespeare who is
denied the opportunity to write because she lacks “a room of one’s
own.” This author wrote about six friends, including Bernard and
Neville (neh-VUHL), who soliloquize on the nature of life, in an
experimental work in which the theme of water provides a
backdrop. Lily Briscoe visits the Ramsays (RAM-seez), who live on the
Isle of Skye, in a book by this author named for a sea-side structure
that Mr. Ramsay wishes to visit. Name this author of the Bloomsbury
Group who penned The Waves and To the Lighthouse.
***** ANSWER:
Adeline Virginia Woolf [accept Virginia Stephen]

*** English / World Literature: Name these authors who wrote about large beasts.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       f3deab2b-9402-47df-97dd-3ea02db0023b
     :END:
What soldier, prisoner, and author wrote about the “questing beast” in
his compilation of Arthurian myth, Le Morte Darthur (luh mort
DAR-thur)?
***** ANSWER:
Thomas Mallory
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       c463bd59-7f95-4319-9247-fd5308c85385
     :END:
What author wrote about a giant bear who is exposed to the politics of
the Beklan Empire in Shardik? A rabbit named Hazel is the protagonist
of his novel Watership Down.
***** ANSWER:
Richard George Adams
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       f4302e61-0a0a-4005-93e0-5eaa728f5f6f
     :END:
In one work this author wrote about Calidore (CAL-ih-door), a knight
whose mission is to slay the Blatant Beast.  In that poem by this
author, the recurring character of Colin Clout plays songs on his
bagpipe. This man’s love for Elizabeth Boyle inspired his sonnet
sequence Amoretti (ah-moh-RET-ee). Holiness, Temperance, Chastity,
Friendship, Justice, and Courtesy are the themes of his masterpiece,
which makes use of the ABABBCBCC (“A-B-A-B-B-C-B-C-C”) rhyme scheme
and idealizes Queen Elizabeth as the title figure. Name this 16th
century author of the epic poem The Faerie Queene.
***** ANSWER:
Edmund Spenser

*** English / World Literature: Name these British poets.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       32ae53c6-5e78-468e-97dd-c469ee39b2c0
     :END:
What British poet, the author of “When I was One and Twenty” wrote
about being able to “see the cherry hung with snow” in his poem
“Loveliest of Trees”?
***** ANSWER:
Alfred Edward Housman
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       e9c157b1-4668-4256-ac3c-f5425735d33a
     :END:
What other British poet described “happy bells, across the snow” in
his poem “Ring Out”, which is part of a sequence commemorating Arthur
Hallam?
***** ANSWER:
Alfred, Lord Tennyson [or 1st Baron Tennyson]
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       3fdf90e3-53cb-4a4f-940d-f3ed60b8a649
     :END:
This author wrote about seeing his cradled infant Hartley in a poem
that begins by describing how the title phenomenon “performs its
secret ministry unhelped by any wind.” He addressed his “pensive Sara”
at the beginning of a poem about a musical instrument “placed
length-ways in the clasping casement.” This author of “Frost at
Midnight” and “The Aeolian (ee-OH-lee-in) Harp” had one of his works
interrupted by the Person from Porlock. That work is set where “Alph,
the sacred river, ran” and describes a “stately pleasure-dome” in
Xanadu (ZAN-uh-dew). Name this British poet who wrote “Kubla Khan.”
***** ANSWER:
Samuel Taylor Coleridge

*** English / World Literature: Name the following related to East Asian literature.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       382659bb-4b87-4f7b-9b82-c7436d9475a7
     :END:
What work by Lady Murasaki (MUR-uh-sah-kee), sometimes considered to
be the first novel, is a depiction of classical Japanese court life?
***** ANSWER:
The Tale of Genji or [Genji monogatari]
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       284d8a9a-ba0a-4da5-993b-da81c97e1333
     :END:
Zeami (zay-AHM-ee) is considered to be a practitioner of what medieval
Japanese art form, which emphasizes a slow, stylized performance and
actors with masks?
***** ANSWER:
noh [or nogaku or noh drama or noh play or noh theater]
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       07e1e23e-30df-4dd0-969f-b9670a10dce0
     :END:
In this work, a character causes fiery bricks to fall from heaven,
leading to the creation of Flaming Mountain. A group of characters in
this work make a pilgrimage to Vulture Peak. This novel’s main
character was born from a magic stone infused with the power of heaven
on top of a mountain. This novel’s characters include Pigsy, Sandy,
and Sun Wukong, who sometimes provides the alternate name of this
novel, (*) Monkey. Name this novel, one of the four Chinese classics,
which is named for a voyage to India.
***** ANSWER:
Journey to the West [or Xi You Ji or Hsi-yu chi; prompt on “Adventures
of the Monkey God” or “Monkey to the West” or “The Adventures of
Monkey”; prompt on “Monkey” before (*)]

*** English / World Literature: Give the following related to lunar references in works of literature.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       2d1c37fe-be53-46f8-a384-7d9d8b2f19e8
     :END:
From the Earth to the Moon is one of the many science fiction novels
in which what author depicts journeys to the moon?
***** ANSWER:
Jules Gabriel Verne
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       1d231027-1965-4603-8d9b-a037d214325a
     :END:
What author of Comical History of the States and Empires of the Moon
is better known for appearing in a 19th century play in which he
secretly loves Roxane?
***** ANSWER:
Hercule-Savinien Cyrano De Bergerac
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       d9736766-46ca-4815-830d-a5dd148b8ca1
     :END:
The oldest piece of prose in this country’s literary tradition
describes a girl that is found in a plant leaf as a youth and raised
by human foster-parents before becoming Princess of the Moon. A
novelist from this country wrote about an old man, who visits an
establishment in which all of the young girls have been drugged, in
the novella The House of the Sleeping Beauties. That author from this
nation also wrote Snow Country, which is set in a hot springs town, or
onsen.  Name this country that was home to the writer Yasunari
Kawabata.
***** ANSWER:
Japan [or Nihon-koku or Nippon-koku]

*** English / World Literature: Name these European authors.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       0228d74f-0a6f-4df2-bd8f-9dfe7daa110f
     :END:
What Czech author never finished his novel about K., who tries to
enter the title structure, titled The Castle?
***** ANSWER:
Franz Kafka [or Franz Anschel]
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       617220f1-b0e9-43d4-aa1c-11d764dd1f09
     :END:
What Czech author wrote about Tomas and Teresa, who live during the
Prague Spring, in The Unbearable Lightness of Being?
***** ANSWER:
Milan Kundera
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       d66d909f-be6d-4fbf-920f-a83957412e9a
     :END:
This author adapted Arthur Schnitzler’s (SHNITZ-lurz) play The Distant
Land into his own play The Undiscovered Country. The events that lead
to the Russian Revolution are the subject of his three plays Voyage,
Shipwreck, and Salvage. In another play by this author, the title
characters and the Tragedians (tra-juh-DEE-unz) hide in barrels while
pirates attack their boat. In that play by this author, the two title
characters perform The Murder of Gonzago after flipping a coin 92
times and seeing it land on heads every time. Name this author of
Rosencrantz and Guildenstern are Dead.
***** ANSWER:
Tom Stoppard [or Tomáš Straussler]

*** English / World Literature: Give the following related to illustrators of English literature.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       0bcdd5d5-2f01-4e7c-8dad-c8dbb0d90ecf
     :END:
Hablot Browne illustrated the novels of what author, whose works
include Martin Chuzzlewit and Bleak House?
***** ANSWER:
Charles John Huffam Dickens
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       ab1642df-cfb4-43dc-9960-99b59c9d56d7
     :END:
John Tenniel illustrated what Lewis Carroll novel, whose characters
included the Red Queen and Tweedledum?
***** ANSWER:
Through the Looking Glass, and What Alice Found There
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       d1526326-0a0f-49f9-9c02-5881de6ec59e
     :END:
At the end of this story, which was illustrated by Sidney Paget
(PUH-jay), a sea-battered stern post with the letters “L.S.” painted
on it is discovered. This story is told through the character of John
Openshaw, who describes how his Uncle Elias is a former colonel that
is given an envelope with the title objects; that envelope causes him
to burn some secret papers and pace frantically before he is found
dead in his own pool. Name this short story in which Sherlock Holmes
deduces that a boat captain and his two mates are members of the
K.K.K. and thus responsible for two murders.
***** ANSWER:
“The Five Orange Pips”

*** English / World Literature: Answer the following about authors who wrote epic poems.
**** Team B:                                                          :drill:
     :PROPERTIES:
     :ID:       e5fb7086-71b6-4443-8227-01192b12eb7b
     :END:
The Shield of Heracles and Works and Days are epic poems by what Greek
author, who described the origin of the gods in Theogony
(THEE-odj-uh-nee)?
***** ANSWER:
Hesiod
**** Team A:                                                          :drill:
     :PROPERTIES:
     :ID:       1260bda9-b176-4555-98bb-cc228925b3ec
     :END:
Apollonius Rhodius (APP-uh-loh-nee-us ROE-dee-us) wrote an epic poem
about what object from Greek mythology that was used in a journey from
Iolcus (EE-oll-cuss) to Colchis (KOLL-chiss) to acquire an item
possessed by King Aeetes (“eye”-EE-teez).
***** ANSWER:
Argo
**** Tossup:                                                          :drill:
     :PROPERTIES:
     :ID:       1776066d-1ea6-48e7-a448-14f5299cf0cd
     :END:
This man wrote an epic poem about “The Death and Judgment of the
Eternal Man” that is named for Tharmas (TAR-muss), Luvah (LOO-vuh),
Urizen (YUR-ee-zen), and Urthona (UR-thoe-nuh). This author of The
Four Zoas wrote a shorter poem that begins “I was angry with my
friend; I told my wrath, my wrath did not end.” That poem ends with
the speaker seeing his foe outstretched beneath the title
plant. Another poem, which appears in the same collection as the
previous one, describes an “invisible worm, that flies in the night.”
Name this author whose poems “A Poison Tree” and “The Sick Rose”
appear in Songs of Innocence and Experience.
***** ANSWER:
William Blake
